@startuml
!pragma revision 1
!include AzureCommon.puml

'all svg sprites starting with A'
sprite $ActivityLog ActivityLog.svg
rectangle "ActivityLog" <<$ActivityLog>> as ActivityLog
sprite $Activity Activity.svg
rectangle "Activity" <<$Activity>> as Activity
sprite $AdaptiveApplicationControl AdaptiveApplicationControl.svg
rectangle "AdaptiveApplicationControl" <<$AdaptiveApplicationControl>> as AdaptiveApplicationControl
sprite $AdaptiveNetworkHardening AdaptiveNetworkHardening.svg
rectangle "AdaptiveNetworkHardening" <<$AdaptiveNetworkHardening>> as AdaptiveNetworkHardening
sprite $ADFSProxy ADFSProxy.svg
rectangle "ADFSProxy" <<$ADFSProxy>> as ADFSProxy
sprite $ADFS ADFS.svg
rectangle "ADFS" <<$ADFS>> as ADFS
sprite $Advisor Advisor.svg
rectangle "Advisor" <<$Advisor>> as Advisor
sprite $Alert Alert.svg
rectangle "Alert" <<$Alert>> as Alert
sprite $AllResources AllResources.svg
rectangle "AllResources" <<$AllResources>> as AllResources
sprite $AnalysisService AnalysisService.svg
rectangle "AnalysisService" <<$AnalysisService>> as AnalysisService
sprite $APIConnection APIConnection.svg
rectangle "APIConnection" <<$APIConnection>> as APIConnection
sprite $APIManagementService APIManagementService.svg
rectangle "APIManagementService" <<$APIManagementService>> as APIManagementService
sprite $ApplicationChangeAnalysis ApplicationChangeAnalysis.svg
rectangle "ApplicationChangeAnalysis" <<$ApplicationChangeAnalysis>> as ApplicationChangeAnalysis
sprite $ApplicationConfiguration ApplicationConfiguration.svg
rectangle "ApplicationConfiguration" <<$ApplicationConfiguration>> as ApplicationConfiguration
sprite $ApplicationGateway ApplicationGateway.svg
rectangle "ApplicationGateway" <<$ApplicationGateway>> as ApplicationGateway
sprite $ApplicationInsights ApplicationInsights.svg
rectangle "ApplicationInsights" <<$ApplicationInsights>> as ApplicationInsights
sprite $ApplicationRegistration ApplicationRegistration.svg
rectangle "ApplicationRegistration" <<$ApplicationRegistration>> as ApplicationRegistration
sprite $ApplicationSecurityGroup ApplicationSecurityGroup.svg
rectangle "ApplicationSecurityGroup" <<$ApplicationSecurityGroup>> as ApplicationSecurityGroup
sprite $ApplicationServiceCertificate ApplicationServiceCertificate.svg
rectangle "ApplicationServiceCertificate" <<$ApplicationServiceCertificate>> as ApplicationServiceCertificate
sprite $ApplicationServiceDomain ApplicationServiceDomain.svg
rectangle "ApplicationServiceDomain" <<$ApplicationServiceDomain>> as ApplicationServiceDomain
sprite $ApplicationServiceEnvironment ApplicationServiceEnvironment.svg
rectangle "ApplicationServiceEnvironment" <<$ApplicationServiceEnvironment>> as ApplicationServiceEnvironment
sprite $ApplicationServicePlan ApplicationServicePlan.svg
rectangle "ApplicationServicePlan" <<$ApplicationServicePlan>> as ApplicationServicePlan
sprite $ApplicationService ApplicationService.svg
rectangle "ApplicationService" <<$ApplicationService>> as ApplicationService
sprite $ArchiveStorage ArchiveStorage.svg
rectangle "ArchiveStorage" <<$ArchiveStorage>> as ArchiveStorage
sprite $ARMTemplate ARMTemplate.svg
rectangle "ARMTemplate" <<$ARMTemplate>> as ARMTemplate
sprite $AutomationAccount AutomationAccount.svg
rectangle "AutomationAccount" <<$AutomationAccount>> as AutomationAccount
sprite $AzureActiveDirectoryAuthenticationMethod AzureActiveDirectoryAuthenticationMethod.svg
rectangle "AzureActiveDirectoryAuthenticationMethod" <<$AzureActiveDirectoryAuthenticationMethod>> as AzureActiveDirectoryAuthenticationMethod
sprite $AzureActiveDirectoryB2B AzureActiveDirectoryB2B.svg
rectangle "AzureActiveDirectoryB2B" <<$AzureActiveDirectoryB2B>> as AzureActiveDirectoryB2B
sprite $AzureActiveDirectoryB2C AzureActiveDirectoryB2C.svg
rectangle "AzureActiveDirectoryB2C" <<$AzureActiveDirectoryB2C>> as AzureActiveDirectoryB2C
sprite $AzureActiveDirectoryConnectHealth AzureActiveDirectoryConnectHealth.svg
rectangle "AzureActiveDirectoryConnectHealth" <<$AzureActiveDirectoryConnectHealth>> as AzureActiveDirectoryConnectHealth
sprite $AzureActiveDirectoryDomainServices AzureActiveDirectoryDomainServices.svg
rectangle "AzureActiveDirectoryDomainServices" <<$AzureActiveDirectoryDomainServices>> as AzureActiveDirectoryDomainServices
sprite $AzureActiveDirectoryGroup AzureActiveDirectoryGroup.svg
rectangle "AzureActiveDirectoryGroup" <<$AzureActiveDirectoryGroup>> as AzureActiveDirectoryGroup
sprite $AzureActiveDirectoryIdentityProtection AzureActiveDirectoryIdentityProtection.svg
rectangle "AzureActiveDirectoryIdentityProtection" <<$AzureActiveDirectoryIdentityProtection>> as AzureActiveDirectoryIdentityProtection
sprite $AzureActiveDirectoryIdentitySecureScore AzureActiveDirectoryIdentitySecureScore.svg
rectangle "AzureActiveDirectoryIdentitySecureScore" <<$AzureActiveDirectoryIdentitySecureScore>> as AzureActiveDirectoryIdentitySecureScore
sprite $AzureActiveDirectoryPrivilegedIdentityManagement AzureActiveDirectoryPrivilegedIdentityManagement.svg
rectangle "AzureActiveDirectoryPrivilegedIdentityManagement" <<$AzureActiveDirectoryPrivilegedIdentityManagement>> as AzureActiveDirectoryPrivilegedIdentityManagement
sprite $AzureActiveDirectoryRiskDetection AzureActiveDirectoryRiskDetection.svg
rectangle "AzureActiveDirectoryRiskDetection" <<$AzureActiveDirectoryRiskDetection>> as AzureActiveDirectoryRiskDetection
sprite $AzureActiveDirectoryRiskySignIn AzureActiveDirectoryRiskySignIn.svg
rectangle "AzureActiveDirectoryRiskySignIn" <<$AzureActiveDirectoryRiskySignIn>> as AzureActiveDirectoryRiskySignIn
sprite $AzureActiveDirectoryRiskyUser AzureActiveDirectoryRiskyUser.svg
rectangle "AzureActiveDirectoryRiskyUser" <<$AzureActiveDirectoryRiskyUser>> as AzureActiveDirectoryRiskyUser
sprite $AzureActiveDirectorySecurity AzureActiveDirectorySecurity.svg
rectangle "AzureActiveDirectorySecurity" <<$AzureActiveDirectorySecurity>> as AzureActiveDirectorySecurity
sprite $AzureActiveDirectoryUser AzureActiveDirectoryUser.svg
rectangle "AzureActiveDirectoryUser" <<$AzureActiveDirectoryUser>> as AzureActiveDirectoryUser
sprite $AzureActiveDirectory AzureActiveDirectory.svg
rectangle "AzureActiveDirectory" <<$AzureActiveDirectory>> as AzureActiveDirectory
sprite $AzureAdvisor AzureAdvisor.svg
rectangle "AzureAdvisor" <<$AzureAdvisor>> as AzureAdvisor
sprite $AzureAPIForFHIR AzureAPIForFHIR.svg
rectangle "AzureAPIForFHIR" <<$AzureAPIForFHIR>> as AzureAPIForFHIR
sprite $AzureArcMachine AzureArcMachine.svg
rectangle "AzureArcMachine" <<$AzureArcMachine>> as AzureArcMachine
sprite $AzureArcService AzureArcService.svg
rectangle "AzureArcService" <<$AzureArcService>> as AzureArcService
sprite $AzureArtifact AzureArtifact.svg
rectangle "AzureArtifact" <<$AzureArtifact>> as AzureArtifact
sprite $AzureAttestation AzureAttestation.svg
rectangle "AzureAttestation" <<$AzureAttestation>> as AzureAttestation
sprite $AzureAutomationRunbook AzureAutomationRunbook.svg
rectangle "AzureAutomationRunbook" <<$AzureAutomationRunbook>> as AzureAutomationRunbook
sprite $AzureBatchAccount AzureBatchAccount.svg
rectangle "AzureBatchAccount" <<$AzureBatchAccount>> as AzureBatchAccount
sprite $AzureBatch AzureBatch.svg
rectangle "AzureBatch" <<$AzureBatch>> as AzureBatch
sprite $AzureBestPractices AzureBestPractices.svg
rectangle "AzureBestPractices" <<$AzureBestPractices>> as AzureBestPractices
sprite $AzureBlockchainService AzureBlockchainService.svg
rectangle "AzureBlockchainService" <<$AzureBlockchainService>> as AzureBlockchainService
sprite $AzureBlueprint AzureBlueprint.svg
rectangle "AzureBlueprint" <<$AzureBlueprint>> as AzureBlueprint
sprite $AzureBoard AzureBoard.svg
rectangle "AzureBoard" <<$AzureBoard>> as AzureBoard
sprite $AzureCacheForRedis AzureCacheForRedis.svg
rectangle "AzureCacheForRedis" <<$AzureCacheForRedis>> as AzureCacheForRedis
sprite $AzureCosmosDB AzureCosmosDB.svg
rectangle "AzureCosmosDB" <<$AzureCosmosDB>> as AzureCosmosDB
sprite $AzureDataExplorerCluster AzureDataExplorerCluster.svg
rectangle "AzureDataExplorerCluster" <<$AzureDataExplorerCluster>> as AzureDataExplorerCluster
sprite $AzureDatabaseForMariadb AzureDatabaseForMariadb.svg
rectangle "AzureDatabaseForMariadb" <<$AzureDatabaseForMariadb>> as AzureDatabaseForMariadb
sprite $AzureDatabaseForMysql AzureDatabaseForMysql.svg
rectangle "AzureDatabaseForMysql" <<$AzureDatabaseForMysql>> as AzureDatabaseForMysql
sprite $AzureDatabaseForPostgresql AzureDatabaseForPostgresql.svg
rectangle "AzureDatabaseForPostgresql" <<$AzureDatabaseForPostgresql>> as AzureDatabaseForPostgresql
sprite $AzureDatabaseMigrationService AzureDatabaseMigrationService.svg
rectangle "AzureDatabaseMigrationService" <<$AzureDatabaseMigrationService>> as AzureDatabaseMigrationService
sprite $AzureDatabricks AzureDatabricks.svg
rectangle "AzureDatabricks" <<$AzureDatabricks>> as AzureDatabricks
sprite $AzureDevOps AzureDevOps.svg
rectangle "AzureDevOps" <<$AzureDevOps>> as AzureDevOps
sprite $AzureFrontDoor AzureFrontDoor.svg
rectangle "AzureFrontDoor" <<$AzureFrontDoor>> as AzureFrontDoor
sprite $AzureInformationProtection AzureInformationProtection.svg
rectangle "AzureInformationProtection" <<$AzureInformationProtection>> as AzureInformationProtection
sprite $AzureLighthouseManagement AzureLighthouseManagement.svg
rectangle "AzureLighthouseManagement" <<$AzureLighthouseManagement>> as AzureLighthouseManagement
sprite $AzureLighthouseMyAuditHistory AzureLighthouseMyAuditHistory.svg
rectangle "AzureLighthouseMyAuditHistory" <<$AzureLighthouseMyAuditHistory>> as AzureLighthouseMyAuditHistory
sprite $AzureLighthouseMyCustomers AzureLighthouseMyCustomers.svg
rectangle "AzureLighthouseMyCustomers" <<$AzureLighthouseMyCustomers>> as AzureLighthouseMyCustomers
sprite $AzureLighthouseMyPermission AzureLighthouseMyPermission.svg
rectangle "AzureLighthouseMyPermission" <<$AzureLighthouseMyPermission>> as AzureLighthouseMyPermission
sprite $AzureLighthouseMyRequest AzureLighthouseMyRequest.svg
rectangle "AzureLighthouseMyRequest" <<$AzureLighthouseMyRequest>> as AzureLighthouseMyRequest
sprite $AzureLighthouseMyRole AzureLighthouseMyRole.svg
rectangle "AzureLighthouseMyRole" <<$AzureLighthouseMyRole>> as AzureLighthouseMyRole
sprite $AzureLighthouseProjection AzureLighthouseProjection.svg
rectangle "AzureLighthouseProjection" <<$AzureLighthouseProjection>> as AzureLighthouseProjection
sprite $AzureLighthouseProtection AzureLighthouseProtection.svg
rectangle "AzureLighthouseProtection" <<$AzureLighthouseProtection>> as AzureLighthouseProtection
sprite $AzureLighthouseRBAC AzureLighthouseRBAC.svg
rectangle "AzureLighthouseRBAC" <<$AzureLighthouseRBAC>> as AzureLighthouseRBAC
sprite $AzureLighthouseServiceProvider AzureLighthouseServiceProvider.svg
rectangle "AzureLighthouseServiceProvider" <<$AzureLighthouseServiceProvider>> as AzureLighthouseServiceProvider
sprite $AzureLighthouse AzureLighthouse.svg
rectangle "AzureLighthouse" <<$AzureLighthouse>> as AzureLighthouse
sprite $AzureMapsAccount AzureMapsAccount.svg
rectangle "AzureMapsAccount" <<$AzureMapsAccount>> as AzureMapsAccount
sprite $AzureMediaServices AzureMediaServices.svg
rectangle "AzureMediaServices" <<$AzureMediaServices>> as AzureMediaServices
sprite $AzureMigrate AzureMigrate.svg
rectangle "AzureMigrate" <<$AzureMigrate>> as AzureMigrate
sprite $AzureMonitorPrivateLinkScope AzureMonitorPrivateLinkScope.svg
rectangle "AzureMonitorPrivateLinkScope" <<$AzureMonitorPrivateLinkScope>> as AzureMonitorPrivateLinkScope
sprite $AzureMonitor AzureMonitor.svg
rectangle "AzureMonitor" <<$AzureMonitor>> as AzureMonitor
sprite $AzureMultifactorAuthentication AzureMultifactorAuthentication.svg
rectangle "AzureMultifactorAuthentication" <<$AzureMultifactorAuthentication>> as AzureMultifactorAuthentication
sprite $AzureNetappFiles AzureNetappFiles.svg
rectangle "AzureNetappFiles" <<$AzureNetappFiles>> as AzureNetappFiles
sprite $AzurePipelines AzurePipelines.svg
rectangle "AzurePipelines" <<$AzurePipelines>> as AzurePipelines
sprite $AzureRepo AzureRepo.svg
rectangle "AzureRepo" <<$AzureRepo>> as AzureRepo
sprite $AzureRoleBasedAccessControl AzureRoleBasedAccessControl.svg
rectangle "AzureRoleBasedAccessControl" <<$AzureRoleBasedAccessControl>> as AzureRoleBasedAccessControl
sprite $AzureSpringCloud AzureSpringCloud.svg
rectangle "AzureSpringCloud" <<$AzureSpringCloud>> as AzureSpringCloud
sprite $AzureStackBackup AzureStackBackup.svg
rectangle "AzureStackBackup" <<$AzureStackBackup>> as AzureStackBackup
sprite $AzureStackCapacity AzureStackCapacity.svg
rectangle "AzureStackCapacity" <<$AzureStackCapacity>> as AzureStackCapacity
sprite $AzureStackEdgeManagement AzureStackEdgeManagement.svg
rectangle "AzureStackEdgeManagement" <<$AzureStackEdgeManagement>> as AzureStackEdgeManagement
sprite $AzureStackOffer AzureStackOffer.svg
rectangle "AzureStackOffer" <<$AzureStackOffer>> as AzureStackOffer
sprite $AzureStackPlan AzureStackPlan.svg
rectangle "AzureStackPlan" <<$AzureStackPlan>> as AzureStackPlan
sprite $AzureStackUpdate AzureStackUpdate.svg
rectangle "AzureStackUpdate" <<$AzureStackUpdate>> as AzureStackUpdate
sprite $AzureStackUserSubscription AzureStackUserSubscription.svg
rectangle "AzureStackUserSubscription" <<$AzureStackUserSubscription>> as AzureStackUserSubscription
sprite $AzureStack AzureStack.svg
rectangle "AzureStack" <<$AzureStack>> as AzureStack
sprite $AzureSynapseAnalytics AzureSynapseAnalytics.svg
rectangle "AzureSynapseAnalytics" <<$AzureSynapseAnalytics>> as AzureSynapseAnalytics
sprite $AzureTestPlan AzureTestPlan.svg
rectangle "AzureTestPlan" <<$AzureTestPlan>> as AzureTestPlan
sprite $Azure Azure.svg
rectangle "Azure" <<$Azure>> as Azure
@enduml