@startuml
!pragma revision 1
!include AzureCommon.puml

'all svg sprites starting with B'
sprite $Bastion Bastion.svg
rectangle "Bastion" <<$Bastion>> as Bastion
sprite $BatchAI Batch-AI.svg
rectangle "BatchAI" <<$BatchAI>> as BatchAI
sprite $BlockchainABSMember Blockchain-ABS-Member.svg
rectangle "BlockchainABSMember" <<$BlockchainABSMember>> as BlockchainABSMember
sprite $BlockchainApplication Blockchain-Application.svg
rectangle "BlockchainApplication" <<$BlockchainApplication>> as BlockchainApplication
sprite $BlockchainConnection Blockchain-Connection.svg
rectangle "BlockchainConnection" <<$BlockchainConnection>> as BlockchainConnection
sprite $BlockchainConsortium Blockchain-Consortium.svg
rectangle "BlockchainConsortium" <<$BlockchainConsortium>> as BlockchainConsortium
sprite $BlockchainDataManager Blockchain-Data-Manager.svg
rectangle "BlockchainDataManager" <<$BlockchainDataManager>> as BlockchainDataManager
sprite $BlockchainDevkit Blockchain-Devkit.svg
rectangle "BlockchainDevkit" <<$BlockchainDevkit>> as BlockchainDevkit
sprite $BlockchainStreaming Blockchain-Streaming.svg
rectangle "BlockchainStreaming" <<$BlockchainStreaming>> as BlockchainStreaming
sprite $BlockchainToken Blockchain-Token.svg
rectangle "BlockchainToken" <<$BlockchainToken>> as BlockchainToken
sprite $Blueprint Blueprint.svg
rectangle "Blueprint" <<$Blueprint>> as Blueprint
sprite $BotService Bot-Service.svg
rectangle "BotService" <<$BotService>> as BotService
sprite $Budget Budget.svg
rectangle "Budget" <<$Budget>> as Budget
sprite $CDNProfile CDN-Profile.svg
@enduml