@startuml
!pragma revision 1
!include AzureCommon.puml

'all svg sprites starting with S'

sprite $SAPHANAOnAzure SAP-HANA-On-Azure.svg
rectangle "SAPHANAOnAzure" <<$SAPHANAOnAzure>> as SAPHANAOnAzure
sprite $SchedulerJobCollection Scheduler-Job-Collection.svg
rectangle "SchedulerJobCollection" <<$SchedulerJobCollection>> as SchedulerJobCollection
sprite $SearchService Search-Service.svg
rectangle "SearchService" <<$SearchService>> as SearchService
sprite $SecureScore Secure-Score.svg
rectangle "SecureScore" <<$SecureScore>> as SecureScore
sprite $SecurityBaseline Security-Baseline.svg
rectangle "SecurityBaseline" <<$SecurityBaseline>> as SecurityBaseline
sprite $SecurityCenter Security-Center.svg
rectangle "SecurityCenter" <<$SecurityCenter>> as SecurityCenter
sprite $SecurityDetonationChamber Security-Detonation-Chamber.svg
rectangle "SecurityDetonationChamber" <<$SecurityDetonationChamber>> as SecurityDetonationChamber
sprite $SendgridAccount Sendgrid-Account.svg
rectangle "SendgridAccount" <<$SendgridAccount>> as SendgridAccount
sprite $Sentinel Sentinel.svg
rectangle "Sentinel" <<$Sentinel>> as Sentinel
sprite $ServiceBus Service-Bus.svg
rectangle "ServiceBus" <<$ServiceBus>> as ServiceBus
sprite $ServiceCatalogManagedApplicationDefinition Service-Catalog-Managed-Application-Definition.svg
rectangle "ServiceCatalogManagedApplicationDefinition" <<$ServiceCatalogManagedApplicationDefinition>> as ServiceCatalogManagedApplicationDefinition
sprite $ServiceEndpointPolicy Service-Endpoint-Policy.svg
rectangle "ServiceEndpointPolicy" <<$ServiceEndpointPolicy>> as ServiceEndpointPolicy
sprite $ServiceEndpoint Service-Endpoint.svg
rectangle "ServiceEndpoint" <<$ServiceEndpoint>> as ServiceEndpoint
sprite $ServiceHealth Service-Health.svg
rectangle "ServiceHealth" <<$ServiceHealth>> as ServiceHealth
sprite $SharedDashboard Shared-Dashboard.svg
rectangle "SharedDashboard" <<$SharedDashboard>> as SharedDashboard
sprite $SharedImageGallery Shared-Image-Gallery.svg
rectangle "SharedImageGallery" <<$SharedImageGallery>> as SharedImageGallery
sprite $SignIn Sign-In.svg
rectangle "SignIn" <<$SignIn>> as SignIn
sprite $Signalr Signalr.svg
rectangle "Signalr" <<$Signalr>> as Signalr
sprite $SoftwareAsAService Software-As-A-Service.svg
rectangle "SoftwareAsAService" <<$SoftwareAsAService>> as SoftwareAsAService
sprite $SpatialAnchorsAccount Spatial-Anchors-Account.svg
rectangle "SpatialAnchorsAccount" <<$SpatialAnchorsAccount>> as SpatialAnchorsAccount
sprite $SQLDataWarehouse SQL-Data-Warehouse.svg
rectangle "SQLDataWarehouse" <<$SQLDataWarehouse>> as SQLDataWarehouse
sprite $SQLDatabaseEdge SQL-Database-Edge.svg
rectangle "SQLDatabaseEdge" <<$SQLDatabaseEdge>> as SQLDatabaseEdge
sprite $SQLDatabase SQL-Database.svg
rectangle "SQLDatabase" <<$SQLDatabase>> as SQLDatabase
sprite $SQLElasticJobAgent SQL-Elastic-Job-Agent.svg
rectangle "SQLElasticJobAgent" <<$SQLElasticJobAgent>> as SQLElasticJobAgent
sprite $SQLElasticPool SQL-Elastic-Pool.svg
rectangle "SQLElasticPool" <<$SQLElasticPool>> as SQLElasticPool
sprite $SQLInstancePool SQL-Instance-Pool.svg
rectangle "SQLInstancePool" <<$SQLInstancePool>> as SQLInstancePool
sprite $SQLManagedInstance SQL-Managed-Instance.svg
rectangle "SQLManagedInstance" <<$SQLManagedInstance>> as SQLManagedInstance
sprite $SQLServerRegistry SQL-Server-Registry.svg
rectangle "SQLServerRegistry" <<$SQLServerRegistry>> as SQLServerRegistry
sprite $SQLServer SQL-Server.svg
rectangle "SQLServer" <<$SQLServer>> as SQLServer
sprite $StorageAccountClassic Storage-Account-Classic.svg
rectangle "StorageAccountClassic" <<$StorageAccountClassic>> as StorageAccountClassic
sprite $StorageAccountContainer Storage-Account-Container.svg
rectangle "StorageAccountContainer" <<$StorageAccountContainer>> as StorageAccountContainer
sprite $StorageAccountQueue Storage-Account-Queue.svg
rectangle "StorageAccountQueue" <<$StorageAccountQueue>> as StorageAccountQueue
sprite $StorageAccountTable Storage-Account-Table.svg
rectangle "StorageAccountTable" <<$StorageAccountTable>> as StorageAccountTable
sprite $StorageAccount Storage-Account.svg
rectangle "StorageAccount" <<$StorageAccount>> as StorageAccount
sprite $StorageExplorer Storage-Explorer.svg
rectangle "StorageExplorer" <<$StorageExplorer>> as StorageExplorer
sprite $StorageSyncService Storage-Sync-Service.svg
rectangle "StorageSyncService" <<$StorageSyncService>> as StorageSyncService
sprite $StorsimpleDataManager Storsimple-Data-Manager.svg
rectangle "StorsimpleDataManager" <<$StorsimpleDataManager>> as StorsimpleDataManager
sprite $StorsimpleDeviceManager Storsimple-Device-Manager.svg
rectangle "StorsimpleDeviceManager" <<$StorsimpleDeviceManager>> as StorsimpleDeviceManager
sprite $StreamAnalyticsJob Stream-Analytics-Job.svg
rectangle "StreamAnalyticsJob" <<$StreamAnalyticsJob>> as StreamAnalyticsJob
sprite $Subscription Subscription.svg
rectangle "Subscription" <<$Subscription>> as Subscription
@enduml