@startuml
!pragma revision 1
!include AzureCommon.puml

'all svg sprites starting with U'

sprite $UniversalPrintService Universal-Print-Service.svg
rectangle "UniversalPrintService" <<$UniversalPrintService>> as UniversalPrintService
sprite $UpdateManagement Update-Management.svg
rectangle "UpdateManagement" <<$UpdateManagement>> as UpdateManagement
sprite $UsageAndQuota Usage-And-Quota.svg
rectangle "UsageAndQuota" <<$UsageAndQuota>> as UsageAndQuota
sprite $UserPrivacy User-Privacy.svg
rectangle "UserPrivacy" <<$UserPrivacy>> as UserPrivacy
@enduml