@startuml
!pragma revision 1
!include AzureCommon.puml

'all svg sprites starting with F'
sprite $FileIntegrityMonitoring File-Integrity-Monitoring.svg
rectangle "FileIntegrityMonitoring" <<$FileIntegrityMonitoring>> as FileIntegrityMonitoring
sprite $FileShare File-Share.svg
rectangle "FileShare" <<$FileShare>> as FileShare
sprite $FirewallManager Firewall-Manager.svg
rectangle "FirewallManager" <<$FirewallManager>> as FirewallManager
sprite $FirewallPolicy Firewall-Policy.svg
rectangle "FirewallPolicy" <<$FirewallPolicy>> as FirewallPolicy
sprite $Firewall Firewall.svg
rectangle "Firewall" <<$Firewall>> as Firewall
sprite $FreeServices Free-Services.svg
rectangle "FreeServices" <<$FreeServices>> as FreeServices
sprite $FunctionApp Function-App.svg
rectangle "FunctionApp" <<$FunctionApp>> as FunctionApp
@enduml