@startuml
!pragma revision 1
!include AzureCommon.puml

'all svg sprites starting with G'
sprite $GenomicsAccount Genomics-Account.svg
rectangle "GenomicsAccount" <<$GenomicsAccount>> as GenomicsAccount
sprite $GeoReplication Geo-Replication.svg
rectangle "GeoReplication" <<$GeoReplication>> as GeoReplication
sprite $HdinsightCluster Hdinsight-Cluster.svg
@enduml