@startuml
!pragma revision 1
!include AzureCommon.puml

'all svg sprites starting with I'
sprite $IdentityAndAccess Identity-And-Access.svg
rectangle "IdentityAndAccess" <<$IdentityAndAccess>> as IdentityAndAccess
sprite $IdentityGovernance Identity-Governance.svg
rectangle "IdentityGovernance" <<$IdentityGovernance>> as IdentityGovernance
sprite $ImportExportJob Import-Export-Job.svg
rectangle "ImportExportJob" <<$ImportExportJob>> as ImportExportJob
sprite $Incident Incident.svg
rectangle "Incident" <<$Incident>> as Incident
sprite $IntegrationAccount Integration-Account.svg
rectangle "IntegrationAccount" <<$IntegrationAccount>> as IntegrationAccount
sprite $IntegrationServiceEnvironment Integration-Service-Environment.svg
rectangle "IntegrationServiceEnvironment" <<$IntegrationServiceEnvironment>> as IntegrationServiceEnvironment
sprite $InternetAnalyzerProfile Internet-Analyzer-Profile.svg
rectangle "InternetAnalyzerProfile" <<$InternetAnalyzerProfile>> as InternetAnalyzerProfile
sprite $IntuneAppProtection Intune-App-Protection.svg
rectangle "IntuneAppProtection" <<$IntuneAppProtection>> as IntuneAppProtection
sprite $IntuneDeviceCompliance Intune-Device-Compliance.svg
rectangle "IntuneDeviceCompliance" <<$IntuneDeviceCompliance>> as IntuneDeviceCompliance
sprite $IntuneDeviceConfiguration Intune-Device-Configuration.svg
rectangle "IntuneDeviceConfiguration" <<$IntuneDeviceConfiguration>> as IntuneDeviceConfiguration
sprite $IntuneDeviceEnrolment Intune-Device-Enrolment.svg
rectangle "IntuneDeviceEnrolment" <<$IntuneDeviceEnrolment>> as IntuneDeviceEnrolment
sprite $IntuneDevice Intune-Device.svg
rectangle "IntuneDevice" <<$IntuneDevice>> as IntuneDevice
sprite $IntuneExchangeAccess Intune-Exchange-Access.svg
rectangle "IntuneExchangeAccess" <<$IntuneExchangeAccess>> as IntuneExchangeAccess
sprite $IntuneExchangeOnPremisesAccess Intune-Exchange-On-Premises-Access.svg
rectangle "IntuneExchangeOnPremisesAccess" <<$IntuneExchangeOnPremisesAccess>> as IntuneExchangeOnPremisesAccess
sprite $IntuneManagedDesktop Intune-Managed-Desktop.svg
rectangle "IntuneManagedDesktop" <<$IntuneManagedDesktop>> as IntuneManagedDesktop
sprite $IntuneSecurityBaseline Intune-Security-Baseline.svg
rectangle "IntuneSecurityBaseline" <<$IntuneSecurityBaseline>> as IntuneSecurityBaseline
sprite $IntuneSoftwareUpdate Intune-Software-Update.svg
rectangle "IntuneSoftwareUpdate" <<$IntuneSoftwareUpdate>> as IntuneSoftwareUpdate
sprite $IntuneTenantStatus Intune-Tenant-Status.svg
rectangle "IntuneTenantStatus" <<$IntuneTenantStatus>> as IntuneTenantStatus
sprite $Intune Intune.svg
rectangle "Intune" <<$Intune>> as Intune
sprite $IotCentral Iot-Central.svg
rectangle "IotCentral" <<$IotCentral>> as IotCentral
sprite $IotDeviceProvisioningService Iot-Device-Provisioning-Service.svg
rectangle "IotDeviceProvisioningService" <<$IotDeviceProvisioningService>> as IotDeviceProvisioningService
sprite $IotDigitalTwin Iot-Digital-Twin.svg
rectangle "IotDigitalTwin" <<$IotDigitalTwin>> as IotDigitalTwin
sprite $IotEdge Iot-Edge.svg
rectangle "IotEdge" <<$IotEdge>> as IotEdge
sprite $IotHubSecurity Iot-Hub-Security.svg
rectangle "IotHubSecurity" <<$IotHubSecurity>> as IotHubSecurity
sprite $IotHub Iot-Hub.svg
rectangle "IotHub" <<$IotHub>> as IotHub
sprite $IotSolutionAccelerator Iot-Solution-Accelerator.svg
rectangle "IotSolutionAccelerator" <<$IotSolutionAccelerator>> as IotSolutionAccelerator
sprite $IotSphere Iot-Sphere.svg
rectangle "IotSphere" <<$IotSphere>> as IotSphere
sprite $IotWindows10Core Iot-Windows-10-Core.svg
rectangle "IotWindows10Core" <<$IotWindows10Core>> as IotWindows10Core
sprite $IPGroup IP-Group.svg
rectangle "IPGroup" <<$IPGroup>> as IPGroup
@enduml