@startuml
!pragma revision 1
!include AzureCommon.puml

'all svg sprites starting with J'
sprite $Java Java.svg
rectangle "Java" <<$Java>> as Java
sprite $KeyVaultHSM Key-Vault-HSM.svg
rectangle "KeyVaultHSM" <<$KeyVaultHSM>> as KeyVaultHSM
sprite $KeyVault Key-Vault.svg
rectangle "KeyVault" <<$KeyVault>> as KeyVault
@enduml