@startuml
!pragma revision 1
!include AzureCommon.puml

'all svg sprites starting with R'
rectangle "Recent" <<$Recent>> as Recent
sprite $RecoveryServicesVault Recovery-Services-Vault.svg
rectangle "RecoveryServicesVault" <<$RecoveryServicesVault>> as RecoveryServicesVault
sprite $RegulatoryCompliance Regulatory-Compliance.svg
rectangle "RegulatoryCompliance" <<$RegulatoryCompliance>> as RegulatoryCompliance
sprite $Relay Relay.svg
rectangle "Relay" <<$Relay>> as Relay
sprite $RemoteRenderingAccount Remote-Rendering-Account.svg
rectangle "RemoteRenderingAccount" <<$RemoteRenderingAccount>> as RemoteRenderingAccount
sprite $Reservation Reservation.svg
rectangle "Reservation" <<$Reservation>> as Reservation
sprite $ReservedIPAddressClassic Reserved-IP-Address-Classic.svg
rectangle "ReservedIPAddressClassic" <<$ReservedIPAddressClassic>> as ReservedIPAddressClassic
sprite $ResourceExplorer Resource-Explorer.svg
rectangle "ResourceExplorer" <<$ResourceExplorer>> as ResourceExplorer
sprite $ResourceGraphExplorer Resource-Graph-Explorer.svg
rectangle "ResourceGraphExplorer" <<$ResourceGraphExplorer>> as ResourceGraphExplorer
sprite $ResourceGraphQuery Resource-Graph-Query.svg
rectangle "ResourceGraphQuery" <<$ResourceGraphQuery>> as ResourceGraphQuery
sprite $ResourceGroup Resource-Group.svg
rectangle "ResourceGroup" <<$ResourceGroup>> as ResourceGroup
sprite $ResourceHealth Resource-Health.svg
rectangle "ResourceHealth" <<$ResourceHealth>> as ResourceHealth
sprite $REST REST.svg
rectangle "REST" <<$REST>> as REST
sprite $ReviewAccess Review-Access.svg
rectangle "ReviewAccess" <<$ReviewAccess>> as ReviewAccess
sprite $Role Role.svg
rectangle "Role" <<$Role>> as Role
sprite $Rollout Rollout.svg
rectangle "Rollout" <<$Rollout>> as Rollout
sprite $RouteFilter Route-Filter.svg
rectangle "RouteFilter" <<$RouteFilter>> as RouteFilter
sprite $RouteTable Route-Table.svg
rectangle "RouteTable" <<$RouteTable>> as RouteTable
sprite $RunCommand Run-Command.svg
rectangle "RunCommand" <<$RunCommand>> as RunCommand
@enduml