@startuml
!pragma revision 1
!include AzureCommon.puml

'all svg sprites starting with V'

sprite $VirtualAssistant Virtual-Assistant.svg
rectangle "VirtualAssistant" <<$VirtualAssistant>> as VirtualAssistant
sprite $VirtualCluster Virtual-Cluster.svg
rectangle "VirtualCluster" <<$VirtualCluster>> as VirtualCluster
sprite $VirtualMachineAvailabilitySet Virtual-Machine-Availability-Set.svg
rectangle "VirtualMachineAvailabilitySet" <<$VirtualMachineAvailabilitySet>> as VirtualMachineAvailabilitySet
sprite $VirtualMachineClassic Virtual-Machine-Classic.svg
rectangle "VirtualMachineClassic" <<$VirtualMachineClassic>> as VirtualMachineClassic
sprite $VirtualMachineImageClassic Virtual-Machine-Image-Classic.svg
rectangle "VirtualMachineImageClassic" <<$VirtualMachineImageClassic>> as VirtualMachineImageClassic
sprite $VirtualMachineImageDefinition Virtual-Machine-Image-Definition.svg
rectangle "VirtualMachineImageDefinition" <<$VirtualMachineImageDefinition>> as VirtualMachineImageDefinition
sprite $VirtualMachineImageVersion Virtual-Machine-Image-Version.svg
rectangle "VirtualMachineImageVersion" <<$VirtualMachineImageVersion>> as VirtualMachineImageVersion
sprite $VirtualMachineImage Virtual-Machine-Image.svg
rectangle "VirtualMachineImage" <<$VirtualMachineImage>> as VirtualMachineImage
sprite $VirtualMachineLinux Virtual-Machine-Linux.svg
rectangle "VirtualMachineLinux" <<$VirtualMachineLinux>> as VirtualMachineLinux
sprite $VirtualMachineNonAzureLinux Virtual-Machine-Non-Azure-Linux.svg
rectangle "VirtualMachineNonAzureLinux" <<$VirtualMachineNonAzureLinux>> as VirtualMachineNonAzureLinux
sprite $VirtualMachineNonAzureWindows Virtual-Machine-Non-Azure-Windows.svg
rectangle "VirtualMachineNonAzureWindows" <<$VirtualMachineNonAzureWindows>> as VirtualMachineNonAzureWindows
sprite $VirtualMachineNonAzure Virtual-Machine-Non-Azure.svg
rectangle "VirtualMachineNonAzure" <<$VirtualMachineNonAzure>> as VirtualMachineNonAzure
sprite $VirtualMachineScaleSet Virtual-Machine-Scale-Set.svg
rectangle "VirtualMachineScaleSet" <<$VirtualMachineScaleSet>> as VirtualMachineScaleSet
sprite $VirtualMachineSQL Virtual-Machine-SQL.svg
rectangle "VirtualMachineSQL" <<$VirtualMachineSQL>> as VirtualMachineSQL
sprite $VirtualMachineWindows Virtual-Machine-Windows.svg
rectangle "VirtualMachineWindows" <<$VirtualMachineWindows>> as VirtualMachineWindows
sprite $VirtualMachine Virtual-Machine.svg
rectangle "VirtualMachine" <<$VirtualMachine>> as VirtualMachine
sprite $VirtualNetworkClassic Virtual-Network-Classic.svg
rectangle "VirtualNetworkClassic" <<$VirtualNetworkClassic>> as VirtualNetworkClassic
sprite $VirtualNetworkFirewall Virtual-Network-Firewall.svg
rectangle "VirtualNetworkFirewall" <<$VirtualNetworkFirewall>> as VirtualNetworkFirewall
sprite $VirtualNetworkGateway Virtual-Network-Gateway.svg
rectangle "VirtualNetworkGateway" <<$VirtualNetworkGateway>> as VirtualNetworkGateway
sprite $VirtualNetworkPeering Virtual-Network-Peering.svg
rectangle "VirtualNetworkPeering" <<$VirtualNetworkPeering>> as VirtualNetworkPeering
sprite $VirtualNetwork Virtual-Network.svg
rectangle "VirtualNetwork" <<$VirtualNetwork>> as VirtualNetwork
sprite $VirtualSubnet Virtual-Subnet.svg
rectangle "VirtualSubnet" <<$VirtualSubnet>> as VirtualSubnet
sprite $VirtualWANGateway Virtual-WAN-Gateway.svg
rectangle "VirtualWANGateway" <<$VirtualWANGateway>> as VirtualWANGateway
sprite $VirtualWAN Virtual-WAN.svg
rectangle "VirtualWAN" <<$VirtualWAN>> as VirtualWAN
sprite $VisualStudioCode Visual-Studio-Code.svg
rectangle "VisualStudioCode" <<$VisualStudioCode>> as VisualStudioCode
sprite $VisualStudio Visual-Studio.svg
rectangle "VisualStudio" <<$VisualStudio>> as VisualStudio
sprite $WAFPolicy WAF-Policy.svg
rectangle "WAFPolicy" <<$WAFPolicy>> as WAFPolicy
sprite $WindowsVirtualDesktop Windows-Virtual-Desktop.svg
rectangle "WindowsVirtualDesktop" <<$WindowsVirtualDesktop>> as WindowsVirtualDesktop
sprite $WorkAccount Work-Account.svg
rectangle "WorkAccount" <<$WorkAccount>> as WorkAccount
sprite $Workbook Workbook.svg
rectangle "Workbook" <<$Workbook>> as Workbook
@enduml