' Styling
' ##################################

skinparam defaultTextAlignment center
skinparam defaultFontName Segoe UI

skinparam rectangle {
    FontSize 12
    BorderThickness 2
    Shadowing false
    BackgroundColor white
}
