@startuml

skinparam RectangleBackgroundColor #FFFFFF
skinparam RectangleFontColor #Black
skinparam RectangleBorderColor #0078d4

skinparam RectangleStereotypeFontSize 0
skinparam RectangleCharacterFontSize 0
skinparam RectangleCharacterRadius 1
skinparam RectangleBorderThickness 1
skinparam RectangleShadowing false

rectangle Something

@enduml