@startuml
!pragma revision 1
!include ../../includes/AzureCommon.puml
sprite $KubernetesServices \Containers/10023-icon-service-Kubernetes-Services.svg
rectangle "Kubernetes Services"<<$KubernetesServices{scale=3}>> as KubernetesServices
sprite $BatchAccounts \Containers/10031-icon-service-Batch-Accounts.svg
rectangle "Batch Accounts"<<$BatchAccounts{scale=3}>> as BatchAccounts
sprite $AppServices \Containers/10035-icon-service-App-Services.svg
rectangle "App Services"<<$AppServices{scale=3}>> as AppServices
sprite $ServiceFabricClusters \Containers/10036-icon-service-Service-Fabric-Clusters.svg
rectangle "Service Fabric Clusters"<<$ServiceFabricClusters{scale=3}>> as ServiceFabricClusters
sprite $ContainerInstances \Containers/10104-icon-service-Container-Instances.svg
rectangle "Container Instances"<<$ContainerInstances{scale=3}>> as ContainerInstances
sprite $ContainerRegistries \Containers/10105-icon-service-Container-Registries.svg
rectangle "Container Registries"<<$ContainerRegistries{scale=3}>> as ContainerRegistries
@enduml