@startuml
!pragma revision 1
!include ../../includes/AzureCommon.puml
sprite $SQLDataWarehouses \Databases/00036-icon-service-SQL-Data-Warehouses.svg
rectangle "SQL Data Warehouses"<<$SQLDataWarehouses{scale=3}>> as SQLDataWarehouses
sprite $AzureSynapseAnalytics \Databases/00606-icon-service-Azure-Synapse-Analytics.svg
rectangle "Azure Synapse Analytics"<<$AzureSynapseAnalytics{scale=3}>> as AzureSynapseAnalytics
sprite $AzureSQL \Databases/02390-icon-service-Azure-SQL.svg
rectangle "Azure SQL"<<$AzureSQL{scale=3}>> as AzureSQL
sprite $SSISLiftAndShiftIR \Databases/02392-icon-service-SSIS-Lift-And-Shift-IR.svg
rectangle "SSIS Lift And Shift IR"<<$SSISLiftAndShiftIR{scale=3}>> as SSISLiftAndShiftIR
sprite $AzureCosmosDB \Databases/10121-icon-service-Azure-Cosmos-DB.svg
rectangle "Azure Cosmos DB"<<$AzureCosmosDB{scale=3}>> as AzureCosmosDB
sprite $AzureDatabaseMySQLServer \Databases/10122-icon-service-Azure-Database-MySQL-Server.svg
rectangle "Azure Database MySQL Server"<<$AzureDatabaseMySQLServer{scale=3}>> as AzureDatabaseMySQLServer
sprite $AzureDatabaseMariaDBServer \Databases/10123-icon-service-Azure-Database-MariaDB-Server.svg
rectangle "Azure Database MariaDB Server"<<$AzureDatabaseMariaDBServer{scale=3}>> as AzureDatabaseMariaDBServer
sprite $AzureSQLVM \Databases/10124-icon-service-Azure-SQL-VM.svg
rectangle "Azure SQL VM"<<$AzureSQLVM{scale=3}>> as AzureSQLVM
sprite $DataFactory \Databases/10126-icon-service-Data-Factory.svg
rectangle "Data Factory"<<$DataFactory{scale=3}>> as DataFactory
sprite $VirtualClusters \Databases/10127-icon-service-Virtual-Clusters.svg
rectangle "Virtual Clusters"<<$VirtualClusters{scale=3}>> as VirtualClusters
sprite $ElasticJobAgents \Databases/10128-icon-service-Elastic-Job-Agents.svg
rectangle "Elastic Job Agents"<<$ElasticJobAgents{scale=3}>> as ElasticJobAgents
sprite $SQLDatabase \Databases/10130-icon-service-SQL-Database.svg
rectangle "SQL Database"<<$SQLDatabase{scale=3}>> as SQLDatabase
sprite $AzureDatabasePostgreSQLServer \Databases/10131-icon-service-Azure-Database-PostgreSQL-Server.svg
rectangle "Azure Database PostgreSQL Server"<<$AzureDatabasePostgreSQLServer{scale=3}>> as AzureDatabasePostgreSQLServer
sprite $SQLServer \Databases/10132-icon-service-SQL-Server.svg
rectangle "SQL Server"<<$SQLServer{scale=3}>> as SQLServer
sprite $AzureDatabaseMigrationServices \Databases/10133-icon-service-Azure-Database-Migration-Services.svg
rectangle "Azure Database Migration Services"<<$AzureDatabaseMigrationServices{scale=3}>> as AzureDatabaseMigrationServices
sprite $SQLElasticPools \Databases/10134-icon-service-SQL-Elastic-Pools.svg
rectangle "SQL Elastic Pools"<<$SQLElasticPools{scale=3}>> as SQLElasticPools
sprite $ManagedDatabase \Databases/10135-icon-service-Managed-Database.svg
rectangle "Managed Database"<<$ManagedDatabase{scale=3}>> as ManagedDatabase
sprite $SQLManagedInstance \Databases/10136-icon-service-SQL-Managed-Instance.svg
rectangle "SQL Managed Instance"<<$SQLManagedInstance{scale=3}>> as SQLManagedInstance
sprite $AzureSQLServerStretchDatabases \Databases/10137-icon-service-Azure-SQL-Server-Stretch-Databases.svg
rectangle "Azure SQL Server Stretch Databases"<<$AzureSQLServerStretchDatabases{scale=3}>> as AzureSQLServerStretchDatabases
sprite $CacheRedis \Databases/10137-icon-service-Cache-Redis.svg
rectangle "Cache Redis"<<$CacheRedis{scale=3}>> as CacheRedis
sprite $InstancePools \Databases/10139-icon-service-Instance-Pools.svg
rectangle "Instance Pools"<<$InstancePools{scale=3}>> as InstancePools
sprite $AzureDataExplorerClusters \Databases/10145-icon-service-Azure-Data-Explorer-Clusters.svg
rectangle "Azure Data Explorer Clusters"<<$AzureDataExplorerClusters{scale=3}>> as AzureDataExplorerClusters
@enduml