@startuml
!pragma revision 1
!include ../../includes/AzureCommon.puml
sprite $EventHubs IoT/00039-icon-service-Event-Hubs.svg
rectangle " Event Hubs" <<$EventHubs{scale=3}>> as EventHubs
sprite $StreamAnalyticsJobs IoT/00042-icon-service-Stream-Analytics-Jobs.svg
rectangle " Stream Analytics Jobs" <<$StreamAnalyticsJobs{scale=3}>> as StreamAnalyticsJobs
sprite $FunctionApps IoT/10029-icon-service-Function-Apps.svg
rectangle " Function Apps" <<$FunctionApps{scale=3}>> as FunctionApps
sprite $NotificationHubs IoT/10045-icon-service-Notification-Hubs.svg
rectangle " Notification Hubs" <<$NotificationHubs{scale=3}>> as NotificationHubs
sprite $TimeSeriesInsightsEnvironments IoT/10181-icon-service-Time-Series-Insights-Environments.svg
rectangle " Time Series Insights Environments" <<$TimeSeriesInsightsEnvironments{scale=3}>> as TimeSeriesInsightsEnvironments
sprite $IoTHub IoT/10182-icon-service-IoT-Hub.svg
rectangle " IoT Hub" <<$IoTHub{scale=3}>> as IoTHub
sprite $IoTCentralApplications IoT/10184-icon-service-IoT-Central-Applications.svg
rectangle " IoT Central Applications" <<$IoTCentralApplications{scale=3}>> as IoTCentralApplications
sprite $AzureMapsAccounts IoT/10185-icon-service-Azure-Maps-Accounts.svg
rectangle " Azure Maps Accounts" <<$AzureMapsAccounts{scale=3}>> as AzureMapsAccounts
sprite $TimeSeriesInsightsEventSources IoT/10188-icon-service-Time-Series-Insights-Event-Sources.svg
rectangle " Time Series Insights Event Sources" <<$TimeSeriesInsightsEventSources{scale=3}>> as TimeSeriesInsightsEventSources
sprite $LogicApps IoT/10201-icon-service-Logic-Apps.svg
rectangle " Logic Apps" <<$LogicApps{scale=3}>> as LogicApps
sprite $DeviceProvisioningServices IoT/10369-icon-service-Device-Provisioning-Services.svg
rectangle " Device Provisioning Services" <<$DeviceProvisioningServices{scale=3}>> as DeviceProvisioningServices
@enduml