@startuml
!pragma revision 1
!include ../../includes/AzureCommon.puml
sprite $Monitor \Management + Governance/00001-icon-service-Monitor.svg
rectangle "Monitor"<<$Monitor{scale=3}>> as Monitor
sprite $Alerts \Management + Governance/00002-icon-service-Alerts.svg
rectangle "Alerts"<<$Alerts{scale=3}>> as Alerts
sprite $Advisor \Management + Governance/00003-icon-service-Advisor.svg
rectangle "Advisor"<<$Advisor{scale=3}>> as Advisor
sprite $CostManagementandBilling \Management + Governance/00004-icon-service-Cost-Management-and-Billing.svg
rectangle "Cost Management and Billing"<<$CostManagementandBilling{scale=3}>> as CostManagementandBilling
sprite $Blueprints \Management + Governance/00006-icon-service-Blueprints.svg
rectangle "Blueprints"<<$Blueprints{scale=3}>> as Blueprints
sprite $ActivityLog \Management + Governance/00007-icon-service-Activity-Log.svg
rectangle "Activity Log"<<$ActivityLog{scale=3}>> as ActivityLog
sprite $DiagnosticsSettings \Management + Governance/00008-icon-service-Diagnostics-Settings.svg
rectangle "Diagnostics Settings"<<$DiagnosticsSettings{scale=3}>> as DiagnosticsSettings
sprite $LogAnalyticsWorkspaces \Management + Governance/00009-icon-service-Log-Analytics-Workspaces.svg
rectangle "Log Analytics Workspaces"<<$LogAnalyticsWorkspaces{scale=3}>> as LogAnalyticsWorkspaces
sprite $Compliance \Management + Governance/00011-icon-service-Compliance.svg
rectangle "Compliance"<<$Compliance{scale=3}>> as Compliance
sprite $ApplicationInsights \Management + Governance/00012-icon-service-Application-Insights.svg
rectangle "Application Insights"<<$ApplicationInsights{scale=3}>> as ApplicationInsights
sprite $MyCustomers \Management + Governance/00014-icon-service-My-Customers.svg
rectangle "My Customers"<<$MyCustomers{scale=3}>> as MyCustomers
sprite $RecoveryServicesVaults \Management + Governance/00017-icon-service-Recovery-Services-Vaults.svg
rectangle "Recovery Services Vaults"<<$RecoveryServicesVaults{scale=3}>> as RecoveryServicesVaults
sprite $Metrics \Management + Governance/00020-icon-service-Metrics.svg
rectangle "Metrics"<<$Metrics{scale=3}>> as Metrics
sprite $Solutions \Management + Governance/00021-icon-service-Solutions.svg
rectangle "Solutions"<<$Solutions{scale=3}>> as Solutions
sprite $AutomationAccounts \Management + Governance/00022-icon-service-Automation-Accounts.svg
rectangle "Automation Accounts"<<$AutomationAccounts{scale=3}>> as AutomationAccounts
sprite $OperationLogClassic \Management + Governance/00024-icon-service-Operation-Log-Classic.svg
rectangle "Operation Log Classic"<<$OperationLogClassic{scale=3}>> as OperationLogClassic
sprite $ServiceProviders \Management + Governance/00025-icon-service-Service-Providers.svg
rectangle "Service Providers"<<$ServiceProviders{scale=3}>> as ServiceProviders
sprite $Education \Management + Governance/00026-icon-service-Education.svg
rectangle "Education"<<$Education{scale=3}>> as Education
sprite $AzureLighthouse \Management + Governance/00471-icon-service-Azure-Lighthouse.svg
rectangle "Azure Lighthouse"<<$AzureLighthouse{scale=3}>> as AzureLighthouse
sprite $AzureArc \Management + Governance/00756-icon-service-Azure-Arc.svg
rectangle "Azure Arc"<<$AzureArc{scale=3}>> as AzureArc
sprite $UserPrivacy \Management + Governance/10303-icon-service-User-Privacy.svg
rectangle "User Privacy"<<$UserPrivacy{scale=3}>> as UserPrivacy
sprite $ManagedApplicationsCenter \Management + Governance/10313-icon-service-Managed-Applications-Center.svg
rectangle "Managed Applications Center"<<$ManagedApplicationsCenter{scale=3}>> as ManagedApplicationsCenter
sprite $Policy \Management + Governance/10316-icon-service-Policy.svg
rectangle "Policy"<<$Policy{scale=3}>> as Policy
sprite $ResourceGraphExplorer \Management + Governance/10318-icon-service-Resource-Graph-Explorer.svg
rectangle "Resource Graph Explorer"<<$ResourceGraphExplorer{scale=3}>> as ResourceGraphExplorer
sprite $MachinesAzureArc \Management + Governance/10450-icon-service-MachinesAzureArc.svg
rectangle "MachinesAzureArc"<<$MachinesAzureArc{scale=3}>> as MachinesAzureArc
@enduml