@startuml
!pragma revision 1
!include ../../includes/AzureCommon.puml
sprite $CDNProfiles \Networking/00056-icon-service-CDN-Profiles.svg
rectangle "CDN Profiles"<<$CDNProfiles{scale=3}>> as CDNProfiles
sprite $AzureFirewallManager \Networking/00271-icon-service-Azure-Firewall-Manager.svg
rectangle "Azure Firewall Manager"<<$AzureFirewallManager{scale=3}>> as AzureFirewallManager
sprite $PrivateLink \Networking/00427-icon-service-Private-Link.svg
rectangle "Private Link"<<$PrivateLink{scale=3}>> as PrivateLink
sprite $IPGroups \Networking/00701-icon-service-IP-Groups.svg
rectangle "IP Groups"<<$IPGroups{scale=3}>> as IPGroups
sprite $PrivateLinkService \Networking/01105-icon-service-Private-Link-Service.svg
rectangle "Private Link Service"<<$PrivateLinkService{scale=3}>> as PrivateLinkService
sprite $VirtualNetworks \Networking/10061-icon-service-Virtual-Networks.svg
rectangle "Virtual Networks"<<$VirtualNetworks{scale=3}>> as VirtualNetworks
sprite $LoadBalancers \Networking/10062-icon-service-Load-Balancers.svg
rectangle "Load Balancers"<<$LoadBalancers{scale=3}>> as LoadBalancers
sprite $VirtualNetworkGateways \Networking/10063-icon-service-Virtual-Network-Gateways.svg
rectangle "Virtual Network Gateways"<<$VirtualNetworkGateways{scale=3}>> as VirtualNetworkGateways
sprite $DNSZones \Networking/10064-icon-service-DNS-Zones.svg
rectangle "DNS Zones"<<$DNSZones{scale=3}>> as DNSZones
sprite $TrafficManagerProfiles \Networking/10065-icon-service-Traffic-Manager-Profiles.svg
rectangle "Traffic Manager Profiles"<<$TrafficManagerProfiles{scale=3}>> as TrafficManagerProfiles
sprite $NetworkWatcher \Networking/10066-icon-service-Network-Watcher.svg
rectangle "Network Watcher"<<$NetworkWatcher{scale=3}>> as NetworkWatcher
sprite $NetworkSecurityGroups \Networking/10067-icon-service-Network-Security-Groups.svg
rectangle "Network Security Groups"<<$NetworkSecurityGroups{scale=3}>> as NetworkSecurityGroups
sprite $PublicIPAddressesClassic \Networking/10068-icon-service-Public-IP-Addresses-Classic.svg
rectangle "Public IP Addresses Classic"<<$PublicIPAddressesClassic{scale=3}>> as PublicIPAddressesClassic
sprite $PublicIPAddresses \Networking/10069-icon-service-Public-IP-Addresses.svg
rectangle "Public IP Addresses"<<$PublicIPAddresses{scale=3}>> as PublicIPAddresses
sprite $RouteFilters \Networking/10071-icon-service-Route-Filters.svg
rectangle "Route Filters"<<$RouteFilters{scale=3}>> as RouteFilters
sprite $DDoSProtectionPlans \Networking/10072-icon-service-DDoS-Protection-Plans.svg
rectangle "DDoS Protection Plans"<<$DDoSProtectionPlans{scale=3}>> as DDoSProtectionPlans
sprite $FrontDoors \Networking/10073-icon-service-Front-Doors.svg
rectangle "Front Doors"<<$FrontDoors{scale=3}>> as FrontDoors
sprite $VirtualNetworksClassic \Networking/10075-icon-service-Virtual-Networks-Classic.svg
rectangle "Virtual Networks Classic"<<$VirtualNetworksClassic{scale=3}>> as VirtualNetworksClassic
sprite $ApplicationGateways \Networking/10076-icon-service-Application-Gateways.svg
rectangle "Application Gateways"<<$ApplicationGateways{scale=3}>> as ApplicationGateways
sprite $LocalNetworkGateways \Networking/10077-icon-service-Local-Network-Gateways.svg
rectangle "Local Network Gateways"<<$LocalNetworkGateways{scale=3}>> as LocalNetworkGateways
sprite $ExpressRouteCircuits \Networking/10079-icon-service-ExpressRoute-Circuits.svg
rectangle "ExpressRoute Circuits"<<$ExpressRouteCircuits{scale=3}>> as ExpressRouteCircuits
sprite $NetworkInterfaces \Networking/10080-icon-service-Network-Interfaces.svg
rectangle "Network Interfaces"<<$NetworkInterfaces{scale=3}>> as NetworkInterfaces
sprite $Connections \Networking/10081-icon-service-Connections.svg
rectangle "Connections"<<$Connections{scale=3}>> as Connections
sprite $RouteTables \Networking/10082-icon-service-Route-Tables.svg
rectangle "Route Tables"<<$RouteTables{scale=3}>> as RouteTables
sprite $Firewalls \Networking/10084-icon-service-Firewalls.svg
rectangle "Firewalls"<<$Firewalls{scale=3}>> as Firewalls
sprite $ServiceEndpointPolicies \Networking/10085-icon-service-Service-Endpoint-Policies.svg
rectangle "Service Endpoint Policies"<<$ServiceEndpointPolicies{scale=3}>> as ServiceEndpointPolicies
sprite $NAT \Networking/10310-icon-service-NAT.svg
rectangle "NAT"<<$NAT{scale=3}>> as NAT
sprite $VirtualWANs \Networking/10353-icon-service-Virtual-WANs.svg
rectangle "Virtual WANs"<<$VirtualWANs{scale=3}>> as VirtualWANs
sprite $WebApplicationFirewallPolicies(WAF) \Networking/10362-icon-service-Web-Application-Firewall-Policies(WAF).svg
rectangle "Web Application Firewall Policies(WAF)"<<$WebApplicationFirewallPolicies(WAF){scale=3}>> as WebApplicationFirewallPolicies(WAF)
sprite $ProximityPlacementGroups \Networking/10365-icon-service-Proximity-Placement-Groups.svg
rectangle "Proximity Placement Groups"<<$ProximityPlacementGroups{scale=3}>> as ProximityPlacementGroups
sprite $ReservedIPAddressesClassic \Networking/10371-icon-service-Reserved-IP-Addresses-Classic.svg
rectangle "Reserved IP Addresses Classic"<<$ReservedIPAddressesClassic{scale=3}>> as ReservedIPAddressesClassic
sprite $PublicIPPrefixes \Networking/10372-icon-service-Public-IP-Prefixes.svg
rectangle "Public IP Prefixes"<<$PublicIPPrefixes{scale=3}>> as PublicIPPrefixes
@enduml