@startuml
sprite $BatchAI Batch-AI.svg
rectangle "BatchAI" <<$BatchAI>> as BatchAI
/'broken
sprite $BotServices Bot-Services.svg
rectangle "BotServices" <<$BotServices>> as BotServices
'/
/'broken
sprite $CognitiveServices Cognitive-Services.svg
rectangle "CognitiveServices" <<$CognitiveServices>> as CognitiveServices
'/

sprite $GenomicsAccounts Genomics-Accounts.svg
rectangle "GenomicsAccounts" <<$GenomicsAccounts>> as GenomicsAccounts
sprite $MachineLearningServiceWorkspaces Machine-Learning-Service-Workspaces2.svg
rectangle "MachineLearningServiceWorkspaces" <<$MachineLearningServiceWorkspaces>> as MachineLearningServiceWorkspaces
sprite $MachineLearningStudioWebServicePlans Machine-Learning-Studio-Web-Service-Plans.svg
rectangle "MachineLearningStudioWebServicePlans" <<$MachineLearningStudioWebServicePlans>> as MachineLearningStudioWebServicePlans
sprite $MachineLearningStudioWebServices Machine-Learning-Studio-Web-Services.svg
rectangle "MachineLearningStudioWebServices" <<$MachineLearningStudioWebServices>> as MachineLearningStudioWebServices
sprite $MachineLearningStudioWorkspaces Machine-Learning-Studio-Workspaces.svg
rectangle "MachineLearningStudioWorkspaces" <<$MachineLearningStudioWorkspaces>> as MachineLearningStudioWorkspaces
@enduml