@startuml
!pragma revision 1
!include ../../includes/AzureCommon.puml
sprite $MachineLearningStudioClassicWebServices ../../media/icons/AIMachineLearning/00030-icon-service-Machine-Learning-Studio-Classic-Web-Services.svg
rectangle "Machine Learning Studio Classic Web Services" <<$MachineLearningStudioClassicWebServices{scale=3}>> as MachineLearningStudioClassicWebServices
sprite $TranslatorText ../../media/icons/AIMachineLearning/00800-icon-service-Translator-Text.svg
rectangle "Translator Text" <<$TranslatorText{scale=3}>> as TranslatorText
sprite $CognitiveServices ../../media/icons/AIMachineLearning/10162-icon-service-Cognitive-Services.svg
rectangle "Cognitive Services" <<$CognitiveServices{scale=3}>> as CognitiveServices
sprite $BotServices ../../media/icons/AIMachineLearning/10165-icon-service-Bot-Services.svg
rectangle "Bot Services" <<$BotServices{scale=3}>> as BotServices
sprite $MachineLearningStudioWorkspaces ../../media/icons/AIMachineLearning/10167-icon-service-Machine-Learning-Studio-Workspaces.svg
rectangle "Machine Learning Studio Workspaces" <<$MachineLearningStudioWorkspaces{scale=3}>> as MachineLearningStudioWorkspaces
sprite $MachineLearningStudioWebServicePlans ../../media/icons/AIMachineLearning/10168-icon-service-Machine-Learning-Studio-Web-Service-Plans.svg
rectangle "Machine Learning Studio Web Service Plans" <<$MachineLearningStudioWebServicePlans{scale=3}>> as MachineLearningStudioWebServicePlans
rectangle "Ingrid Henkel"
@enduml