@startuml
!pragma revision 1
!include ../../includes/AzureCommon.puml

top to bottom direction
rectangle "Secure Streaming" as SecureStreaming {
    
    rectangle "Streaming Encryption" as StreamingEncryption {
        rectangle "CORS" as CORS
        rectangle "AES-128" as AES128
        rectangle "CBCS Encyption" as CBCSEncyption
        rectangle "dynamic encryption" as dynamicencryption
    }
    rectangle "Key Delivery" as KeyDelivery {
        rectangle "Token Restrictions" as TokenRestrictions
        rectangle "Open Restrictions" as OpenRestrictions
        rectangle "Token Authentication" as TokenAuthentication {
            rectangle "AAD Auth" as AADAuth {
                rectangle "Azure AD B2C Auth" as AzureADB2CAuth
            } 
            rectangle "Required Claims" as RequiredClaims
            rectangle "Token Reuse" as TokenReuse
            rectangle "JWT Tokens" as JWTTokens
            rectangle "JWT Custom Claims" as JWTCustomClaims
            rectangle "Custom token providers " as Customtokenproviders
            rectangle "3rd Party DRM Content Keys" as 3rdPartyDRMContentKeys
        }
        rectangle "Account Configuration" as AccountConfiguration {
            rectangle "CDN  Token auth" as CDNTokenauth
            rectangle "Key Delivery Quotas" as KeyDeliveryQuotas
            rectangle "Key Rotation" as KeyRotation
        }
    }
    rectangle "DRM / Key Access" as DRMKeyAccess {
        rectangle "Widevine" as Widevine {
            rectangle "Widevine Template Schema" as WidevineTemplateSchema
        }
        rectangle "Fairplay" as Fairplay{
            rectangle "Fairplay doc  links" as Fairplaydoclinks
        }
        rectangle "PlayReady" as PlayReady {
            rectangle "PlayReady SL 3000" as PlayReadySL3000
        }
    }
    rectangle "AES / Envelope" as AESEnvelope
    rectangle "CDN - Rules Engine Based Security" as CDNRulesEngineBasedSecurity
    rectangle "Asset Filters" as AssetFilters
    rectangle "Account Filters" as AccountFilters
}
rectangle "Account Security" as AccountSecurity {
    rectangle "Managed Identity" as ManagedIdentity {
        rectangle "System Managed Identity" as SystemManagedIdentity
        rectangle "User Managed Identity" as UserManagedIdentity
        rectangle "Managed ID auth to storage" as ManagedIDauthtostorage
        rectangle "Managed ID auth to Key Vault" as ManagedIDauthtoKeyVault
        rectangle "Customer managed key" as customermanagedkey
    }
    rectangle "ARM auth" as ARMauth
    rectangle "Playready Template schema" as PlayreadyTemplateschema
    rectangle "Role Based Access Control" as RoleBasedAccessControl {
        rectangle "Built in RBAC rules" as BuiltinRBACrules
        rectangle "Custom RBAC rules" as CustomRBACrules
    }
    rectangle "Azure Policy" as AzurePolicy {
        rectangle "Disabling RESTv2 / Closing 'backdoors'" as DisablingRESTv2Closingbackdoors
    }
    rectangle "Service principal auth to Media Services" as ServiceprincipalauthtoMediaServices
    rectangle "Managed Identity auth to Media Services" as ManagedIdentityauthtoMediaServices
    rectangle "User auth to Media Services" as UserauthtoMediaServices  
}

rectangle "Network Security" as NetworkSecurity{
    rectangle "Public Network Access" as PublicNetworkAccess
    rectangle "IP Allow Lists" as IPAllowLists
    rectangle "Private Links" as PrivateLinks
    rectangle "Secure Ingest with  Auth" as SecureIngestwithAuth
    rectangle "IPs Used for Streaming" as IPsUsedforStreaming
    rectangle "Allowed TLS versions" as AllowedTLSversions{
        rectangle "TLS Encryption Supported - including Cipher info" as TLSEncryptionSupportedincludingCipherinfo
    }
    rectangle "Origin Security" as OriginSecurity {
        rectangle "CDN Origin Security" as CDNOriginSecurity
        rectangle "Akamai G2O Auth" as AkamaiG2OAuth
        rectangle "IP Allow Lists" as IPAllowLists
    }
    rectangle "Live Event Security" as LiveEventSecurity {
        rectangle "Live Event token auth" as LiveEventtokenauth
    }
}
rectangle "Secure Storage" as SecureStorage{
    rectangle "Storage Encryption" as StorageEncryption
    rectangle "Storage  Container Encryption" as StorageContainerEncryption
    rectangle "Trusted Storage" as TrustedStorage
    rectangle "SAS URLs" as SASURLs
    rectangle "system key" as systemkey
    rectangle "BYOK / Customer Managed Keys" as BYOKCustomerManagedKeys
}
rectangle "Monitoring / Analysis" as MonitoringAnalysis {
    rectangle "Logging" as Logging {
        rectangle "Storage Monitoring - e.g. Log Analytics" as StorageMonitoringLogAnalytics
        rectangle "Audit Logs" as AuditLogs
        rectangle "Security Log  monitoring" as SecurityLogmonitoring
        rectangle "Diagnostic Logging" as DiagnosticLogging
        rectangle "Azure Monitor" as AzureMonitor
    }
    rectangle "Metrics" as Metrics {
        rectangle "Key Delivery Metrics" as KeyDeliveryMetrics
    }
    rectangle "CDN - Real Time Monitoring" as CDNRealTimeMonitoring {
        rectangle "CDN Logs" as CDNLogs
        rectangle "Using 3rd Party Tools - e.g. Splunk, etc." as Using3rdPartyToolsSplunKetc
    }
    rectangle "Event Grid" as EventGrid{
        rectangle "Live Ingest Events" as LiveIngestEvents
    }
}

rectangle "I am  not sure" as Iamnotsure {
    rectangle "Content moderation / abuse protection" as Contentmoderationabuseprotection
    rectangle "Watermarking A/B with partners" as WatermarkingABwithpartners
}

rectangle "Ingrid"

NetworkSecurity --[hidden]r-- SecureStorage
SecureStorage --[hidden]r-- MonitoringAnalysis
MonitoringAnalysis --[hidden]r-- AccountSecurity
SecureStreaming --[hidden]u-- MonitoringAnalysis
PublicNetworkAccess --[hidden]r-- IPAllowLists
IPAllowLists --[hidden]r-- IPsUsedforStreaming
AADAuth -[hidden]r- RequiredClaims
RequiredClaims -[hidden]r- TokenReuse
TokenReuse -[hidden]r- Customtokenproviders
Customtokenproviders -[hidden]r- 3rdPartyDRMContentKeys
3rdPartyDRMContentKeys -[hidden]r- JWTTokens
JWTTokens -[hidden]r- JWTCustomClaims
OpenRestrictions -[hidden]r- TokenRestrictions
CDNTokenauth -[hidden]r- KeyDeliveryQuotas
KeyDeliveryQuotas -[hidden]r- KeyRotation
AccountConfiguration -[hidden]d- TokenAuthentication
OpenRestrictions -[hidden]r- AccountConfiguration
TokenRestrictions -[hidden]r- AccountConfiguration


@enduml 