@startuml
!pragma revision 1
!include ../../includes/AzureCommon.puml
sprite $LogAnalyticsWorkspaces ../../media/icons/Analytics/00009-icon-service-Log-Analytics-Workspaces.svg
rectangle "Log Analytics Workspaces" <<$LogAnalyticsWorkspaces{scale=3}>> as LogAnalyticsWorkspaces
sprite $EventHubs ../../media/icons/Analytics/00039-icon-service-Event-Hubs.svg
rectangle "Event Hubs" <<$EventHubs{scale=3}>> as EventHubs
sprite $StreamAnalyticsJobs ../../media/icons/Analytics/00042-icon-service-Stream-Analytics-Jobs.svg
rectangle "Stream Analytics Jobs" <<$StreamAnalyticsJobs{scale=3}>> as StreamAnalyticsJobs
sprite $AzureSynapseAnalytics ../../media/icons/Analytics/00606-icon-service-Azure-Synapse-Analytics.svg
rectangle "Azure Synapse Analytics" <<$AzureSynapseAnalytics{scale=3}>> as AzureSynapseAnalytics
sprite $HDInsightClusters ../../media/icons/Analytics/10142-icon-service-HD-Insight-Clusters.svg
rectangle "HD Insight Clusters" <<$HDInsightClusters{scale=3}>> as HDInsightClusters
sprite $AnalysisServices ../../media/icons/Analytics/10148-icon-service-Analysis-Services.svg
rectangle "Analysis Services" <<$AnalysisServices{scale=3}>> as AnalysisServices
sprite $EventHubClusters ../../media/icons/Analytics/10149-icon-service-Event-Hub-Clusters.svg
rectangle "Event Hub Clusters" <<$EventHubClusters{scale=3}>> as EventHubClusters
sprite $DataLakeStoreGen1 ../../media/icons/Analytics/10150-icon-service-Data-Lake-Store-Gen1.svg
rectangle "Data Lake Store Gen1" <<$DataLakeStoreGen1{scale=3}>> as DataLakeStoreGen1
sprite $AzureDatabricks ../../media/icons/Analytics/10787-icon-service-Azure-Databricks.svg
rectangle "Azure Databricks" <<$AzureDatabricks{scale=3}>> as AzureDatabricks
@enduml