@startuml
!pragma revision 1
!include ../../includes/AzureCommon.puml
sprite $ActivityLog Azure-Full-Colour-2.6/Activity-Log.svg
rectangle "ActivityLog" <<$ActivityLog>> as ActivityLog
sprite $Activity Azure-Full-Colour-2.6/Activity.svg
rectangle "Activity" <<$Activity>> as Activity
sprite $AdaptiveApplicationControl Azure-Full-Colour-2.6/Adaptive-Application-Control.svg
rectangle "AdaptiveApplicationControl" <<$AdaptiveApplicationControl>> as AdaptiveApplicationControl
sprite $AdaptiveNetworkHardening Azure-Full-Colour-2.6/Adaptive-Network-Hardening.svg
rectangle "AdaptiveNetworkHardening" <<$AdaptiveNetworkHardening>> as AdaptiveNetworkHardening
sprite $ADFSProxy Azure-Full-Colour-2.6/ADFS-Proxy.svg
rectangle "ADFSProxy" <<$ADFSProxy>> as ADFSProxy
sprite $ADFS Azure-Full-Colour-2.6/ADFS.svg
rectangle "ADFS" <<$ADFS>> as ADFS
sprite $Advisor Azure-Full-Colour-2.6/Advisor.svg
rectangle "Advisor" <<$Advisor>> as Advisor
sprite $Alert Azure-Full-Colour-2.6/Alert.svg
rectangle "Alert" <<$Alert>> as Alert
sprite $AllResources Azure-Full-Colour-2.6/All-Resources.svg
rectangle "AllResources" <<$AllResources>> as AllResources
sprite $AnalysisService Azure-Full-Colour-2.6/Analysis-Service.svg
rectangle "AnalysisService" <<$AnalysisService>> as AnalysisService
sprite $APIConnection Azure-Full-Colour-2.6/API-Connection.svg
rectangle "APIConnection" <<$APIConnection>> as APIConnection
sprite $APIManagementService Azure-Full-Colour-2.6/API-Management-Service.svg
rectangle "APIManagementService" <<$APIManagementService>> as APIManagementService
sprite $ApplicationChangeAnalysis Azure-Full-Colour-2.6/Application-Change-Analysis.svg
rectangle "ApplicationChangeAnalysis" <<$ApplicationChangeAnalysis>> as ApplicationChangeAnalysis
sprite $ApplicationConfiguration Azure-Full-Colour-2.6/Application-Configuration.svg
rectangle "ApplicationConfiguration" <<$ApplicationConfiguration>> as ApplicationConfiguration
sprite $ApplicationGateway Azure-Full-Colour-2.6/Application-Gateway.svg
rectangle "ApplicationGateway" <<$ApplicationGateway>> as ApplicationGateway
sprite $ApplicationInsights Azure-Full-Colour-2.6/Application-Insights.svg
rectangle "ApplicationInsights" <<$ApplicationInsights>> as ApplicationInsights
sprite $ApplicationRegistration Azure-Full-Colour-2.6/Application-Registration.svg
rectangle "ApplicationRegistration" <<$ApplicationRegistration>> as ApplicationRegistration
sprite $ApplicationSecurityGroup Azure-Full-Colour-2.6/Application-Security-Group.svg
rectangle "ApplicationSecurityGroup" <<$ApplicationSecurityGroup>> as ApplicationSecurityGroup
sprite $ApplicationServiceCertificate Azure-Full-Colour-2.6/Application-Service-Certificate.svg
rectangle "ApplicationServiceCertificate" <<$ApplicationServiceCertificate>> as ApplicationServiceCertificate
sprite $ApplicationServiceDomain Azure-Full-Colour-2.6/Application-Service-Domain.svg
rectangle "ApplicationServiceDomain" <<$ApplicationServiceDomain>> as ApplicationServiceDomain
sprite $ApplicationServiceEnvironment Azure-Full-Colour-2.6/Application-Service-Environment.svg
rectangle "ApplicationServiceEnvironment" <<$ApplicationServiceEnvironment>> as ApplicationServiceEnvironment
sprite $ApplicationServicePlan Azure-Full-Colour-2.6/Application-Service-Plan.svg
rectangle "ApplicationServicePlan" <<$ApplicationServicePlan>> as ApplicationServicePlan
sprite $ApplicationService Azure-Full-Colour-2.6/Application-Service.svg
rectangle "ApplicationService" <<$ApplicationService>> as ApplicationService
sprite $ArchiveStorage Azure-Full-Colour-2.6/Archive-Storage.svg
rectangle "ArchiveStorage" <<$ArchiveStorage>> as ArchiveStorage
sprite $ARMTemplate Azure-Full-Colour-2.6/ARM-Template.svg
rectangle "ARMTemplate" <<$ARMTemplate>> as ARMTemplate
sprite $AutomationAccount Azure-Full-Colour-2.6/Automation-Account.svg
rectangle "AutomationAccount" <<$AutomationAccount>> as AutomationAccount
sprite $AzureActiveDirectoryAuthenticationMethod Azure-Full-Colour-2.6/Azure-Active-Directory-Authentication-Method.svg
rectangle "AzureActiveDirectoryAuthenticationMethod" <<$AzureActiveDirectoryAuthenticationMethod>> as AzureActiveDirectoryAuthenticationMethod
sprite $AzureActiveDirectoryB2B Azure-Full-Colour-2.6/Azure-Active-Directory-B2B.svg
rectangle "AzureActiveDirectoryB2B" <<$AzureActiveDirectoryB2B>> as AzureActiveDirectoryB2B
sprite $AzureActiveDirectoryB2C Azure-Full-Colour-2.6/Azure-Active-Directory-B2C.svg
rectangle "AzureActiveDirectoryB2C" <<$AzureActiveDirectoryB2C>> as AzureActiveDirectoryB2C
sprite $AzureActiveDirectoryConnectHealth Azure-Full-Colour-2.6/Azure-Active-Directory-Connect-Health.svg
rectangle "AzureActiveDirectoryConnectHealth" <<$AzureActiveDirectoryConnectHealth>> as AzureActiveDirectoryConnectHealth
sprite $AzureActiveDirectoryDomainServices Azure-Full-Colour-2.6/Azure-Active-Directory-Domain-Services.svg
rectangle "AzureActiveDirectoryDomainServices" <<$AzureActiveDirectoryDomainServices>> as AzureActiveDirectoryDomainServices
sprite $AzureActiveDirectoryGroup Azure-Full-Colour-2.6/Azure-Active-Directory-Group.svg
rectangle "AzureActiveDirectoryGroup" <<$AzureActiveDirectoryGroup>> as AzureActiveDirectoryGroup
sprite $AzureActiveDirectoryIdentityProtection Azure-Full-Colour-2.6/Azure-Active-Directory-Identity-Protection.svg
rectangle "AzureActiveDirectoryIdentityProtection" <<$AzureActiveDirectoryIdentityProtection>> as AzureActiveDirectoryIdentityProtection
sprite $AzureActiveDirectoryIdentitySecureScore Azure-Full-Colour-2.6/Azure-Active-Directory-Identity-Secure-Score.svg
rectangle "AzureActiveDirectoryIdentitySecureScore" <<$AzureActiveDirectoryIdentitySecureScore>> as AzureActiveDirectoryIdentitySecureScore
sprite $AzureActiveDirectoryPrivilegedIdentityManagement Azure-Full-Colour-2.6/Azure-Active-Directory-Privileged-Identity-Management.svg
rectangle "AzureActiveDirectoryPrivilegedIdentityManagement" <<$AzureActiveDirectoryPrivilegedIdentityManagement>> as AzureActiveDirectoryPrivilegedIdentityManagement
sprite $AzureActiveDirectoryRiskDetection Azure-Full-Colour-2.6/Azure-Active-Directory-Risk-Detection.svg
rectangle "AzureActiveDirectoryRiskDetection" <<$AzureActiveDirectoryRiskDetection>> as AzureActiveDirectoryRiskDetection
sprite $AzureActiveDirectoryRiskySignIn Azure-Full-Colour-2.6/Azure-Active-Directory-Risky-Sign-In.svg
rectangle "AzureActiveDirectoryRiskySignIn" <<$AzureActiveDirectoryRiskySignIn>> as AzureActiveDirectoryRiskySignIn
sprite $AzureActiveDirectoryRiskyUser Azure-Full-Colour-2.6/Azure-Active-Directory-Risky-User.svg
rectangle "AzureActiveDirectoryRiskyUser" <<$AzureActiveDirectoryRiskyUser>> as AzureActiveDirectoryRiskyUser
sprite $AzureActiveDirectorySecurity Azure-Full-Colour-2.6/Azure-Active-Directory-Security.svg
rectangle "AzureActiveDirectorySecurity" <<$AzureActiveDirectorySecurity>> as AzureActiveDirectorySecurity
sprite $AzureActiveDirectoryUser Azure-Full-Colour-2.6/Azure-Active-Directory-User.svg
rectangle "AzureActiveDirectoryUser" <<$AzureActiveDirectoryUser>> as AzureActiveDirectoryUser
sprite $AzureActiveDirectory Azure-Full-Colour-2.6/Azure-Active-Directory.svg
rectangle "AzureActiveDirectory" <<$AzureActiveDirectory>> as AzureActiveDirectory
sprite $AzureAdvisor Azure-Full-Colour-2.6/Azure-Advisor.svg
rectangle "AzureAdvisor" <<$AzureAdvisor>> as AzureAdvisor
sprite $AzureAPIForFHIR Azure-Full-Colour-2.6/Azure-API-For-FHIR.svg
rectangle "AzureAPIForFHIR" <<$AzureAPIForFHIR>> as AzureAPIForFHIR
sprite $AzureArcMachine Azure-Full-Colour-2.6/Azure-Arc-Machine.svg
rectangle "AzureArcMachine" <<$AzureArcMachine>> as AzureArcMachine
sprite $AzureArcService Azure-Full-Colour-2.6/Azure-Arc-Service.svg
rectangle "AzureArcService" <<$AzureArcService>> as AzureArcService
sprite $AzureArtifact Azure-Full-Colour-2.6/Azure-Artifact.svg
rectangle "AzureArtifact" <<$AzureArtifact>> as AzureArtifact
sprite $AzureAttestation Azure-Full-Colour-2.6/Azure-Attestation.svg
rectangle "AzureAttestation" <<$AzureAttestation>> as AzureAttestation
sprite $AzureAutomationRunbook Azure-Full-Colour-2.6/Azure-Automation-Runbook.svg
rectangle "AzureAutomationRunbook" <<$AzureAutomationRunbook>> as AzureAutomationRunbook
sprite $AzureBatchAccount Azure-Full-Colour-2.6/Azure-Batch-Account.svg
rectangle "AzureBatchAccount" <<$AzureBatchAccount>> as AzureBatchAccount
sprite $AzureBatch Azure-Full-Colour-2.6/Azure-Batch.svg
rectangle "AzureBatch" <<$AzureBatch>> as AzureBatch
sprite $AzureBestPractices Azure-Full-Colour-2.6/Azure-Best-Practices.svg
rectangle "AzureBestPractices" <<$AzureBestPractices>> as AzureBestPractices
sprite $AzureBlockchainService Azure-Full-Colour-2.6/Azure-Blockchain-Service.svg
rectangle "AzureBlockchainService" <<$AzureBlockchainService>> as AzureBlockchainService
sprite $AzureBlueprint Azure-Full-Colour-2.6/Azure-Blueprint.svg
rectangle "AzureBlueprint" <<$AzureBlueprint>> as AzureBlueprint
sprite $AzureBoard Azure-Full-Colour-2.6/Azure-Board.svg
rectangle "AzureBoard" <<$AzureBoard>> as AzureBoard
sprite $AzureCacheForRedis Azure-Full-Colour-2.6/Azure-Cache-For-Redis.svg
rectangle "AzureCacheForRedis" <<$AzureCacheForRedis>> as AzureCacheForRedis
sprite $AzureCosmosDB Azure-Full-Colour-2.6/Azure-Cosmos-DB.svg
rectangle "AzureCosmosDB" <<$AzureCosmosDB>> as AzureCosmosDB
sprite $AzureDataExplorerCluster Azure-Full-Colour-2.6/Azure-Data-Explorer-Cluster.svg
rectangle "AzureDataExplorerCluster" <<$AzureDataExplorerCluster>> as AzureDataExplorerCluster
sprite $AzureDatabaseForMariadb Azure-Full-Colour-2.6/Azure-Database-For-Mariadb.svg
rectangle "AzureDatabaseForMariadb" <<$AzureDatabaseForMariadb>> as AzureDatabaseForMariadb
sprite $AzureDatabaseForMysql Azure-Full-Colour-2.6/Azure-Database-For-Mysql.svg
rectangle "AzureDatabaseForMysql" <<$AzureDatabaseForMysql>> as AzureDatabaseForMysql
sprite $AzureDatabaseForPostgresql Azure-Full-Colour-2.6/Azure-Database-For-Postgresql.svg
rectangle "AzureDatabaseForPostgresql" <<$AzureDatabaseForPostgresql>> as AzureDatabaseForPostgresql
sprite $AzureDatabaseMigrationService Azure-Full-Colour-2.6/Azure-Database-Migration-Service.svg
rectangle "AzureDatabaseMigrationService" <<$AzureDatabaseMigrationService>> as AzureDatabaseMigrationService
sprite $AzureDatabricks Azure-Full-Colour-2.6/Azure-Databricks.svg
rectangle "AzureDatabricks" <<$AzureDatabricks>> as AzureDatabricks
sprite $AzureDevOps Azure-Full-Colour-2.6/Azure-Dev-Ops.svg
rectangle "AzureDevOps" <<$AzureDevOps>> as AzureDevOps
sprite $AzureFrontDoor Azure-Full-Colour-2.6/Azure-Front-Door.svg
rectangle "AzureFrontDoor" <<$AzureFrontDoor>> as AzureFrontDoor
sprite $AzureInformationProtection Azure-Full-Colour-2.6/Azure-Information-Protection.svg
rectangle "AzureInformationProtection" <<$AzureInformationProtection>> as AzureInformationProtection
sprite $AzureLighthouseManagement Azure-Full-Colour-2.6/Azure-Lighthouse-Management.svg
rectangle "AzureLighthouseManagement" <<$AzureLighthouseManagement>> as AzureLighthouseManagement
sprite $AzureLighthouseMyAuditHistory Azure-Full-Colour-2.6/Azure-Lighthouse-My-Audit-History.svg
rectangle "AzureLighthouseMyAuditHistory" <<$AzureLighthouseMyAuditHistory>> as AzureLighthouseMyAuditHistory
sprite $AzureLighthouseMyCustomers Azure-Full-Colour-2.6/Azure-Lighthouse-My-Customers.svg
rectangle "AzureLighthouseMyCustomers" <<$AzureLighthouseMyCustomers>> as AzureLighthouseMyCustomers
sprite $AzureLighthouseMyPermission Azure-Full-Colour-2.6/Azure-Lighthouse-My-Permission.svg
rectangle "AzureLighthouseMyPermission" <<$AzureLighthouseMyPermission>> as AzureLighthouseMyPermission
sprite $AzureLighthouseMyRequest Azure-Full-Colour-2.6/Azure-Lighthouse-My-Request.svg
rectangle "AzureLighthouseMyRequest" <<$AzureLighthouseMyRequest>> as AzureLighthouseMyRequest
sprite $AzureLighthouseMyRole Azure-Full-Colour-2.6/Azure-Lighthouse-My-Role.svg
rectangle "AzureLighthouseMyRole" <<$AzureLighthouseMyRole>> as AzureLighthouseMyRole
sprite $AzureLighthouseProjection Azure-Full-Colour-2.6/Azure-Lighthouse-Projection.svg
rectangle "AzureLighthouseProjection" <<$AzureLighthouseProjection>> as AzureLighthouseProjection
sprite $AzureLighthouseProtection Azure-Full-Colour-2.6/Azure-Lighthouse-Protection.svg
rectangle "AzureLighthouseProtection" <<$AzureLighthouseProtection>> as AzureLighthouseProtection
sprite $AzureLighthouseRBAC Azure-Full-Colour-2.6/Azure-Lighthouse-RBAC.svg
rectangle "AzureLighthouseRBAC" <<$AzureLighthouseRBAC>> as AzureLighthouseRBAC
sprite $AzureLighthouseServiceProvider Azure-Full-Colour-2.6/Azure-Lighthouse-Service-Provider.svg
rectangle "AzureLighthouseServiceProvider" <<$AzureLighthouseServiceProvider>> as AzureLighthouseServiceProvider
sprite $AzureLighthouse Azure-Full-Colour-2.6/Azure-Lighthouse.svg
rectangle "AzureLighthouse" <<$AzureLighthouse>> as AzureLighthouse
sprite $AzureMapsAccount Azure-Full-Colour-2.6/Azure-Maps-Account.svg
rectangle "AzureMapsAccount" <<$AzureMapsAccount>> as AzureMapsAccount
sprite $AzureMigrate Azure-Full-Colour-2.6/Azure-Migrate.svg
rectangle "AzureMigrate" <<$AzureMigrate>> as AzureMigrate
sprite $AzureMonitorPrivateLinkScope Azure-Full-Colour-2.6/Azure-Monitor-Private-Link-Scope.svg
rectangle "AzureMonitorPrivateLinkScope" <<$AzureMonitorPrivateLinkScope>> as AzureMonitorPrivateLinkScope
sprite $AzureMonitor Azure-Full-Colour-2.6/Azure-Monitor.svg
rectangle "AzureMonitor" <<$AzureMonitor>> as AzureMonitor
sprite $AzureMultifactorAuthentication Azure-Full-Colour-2.6/Azure-Multifactor-Authentication.svg
rectangle "AzureMultifactorAuthentication" <<$AzureMultifactorAuthentication>> as AzureMultifactorAuthentication
sprite $AzureNetappFiles Azure-Full-Colour-2.6/Azure-Netapp-Files.svg
rectangle "AzureNetappFiles" <<$AzureNetappFiles>> as AzureNetappFiles
sprite $AzurePipelines Azure-Full-Colour-2.6/Azure-Pipelines.svg
rectangle "AzurePipelines" <<$AzurePipelines>> as AzurePipelines
sprite $AzureRepo Azure-Full-Colour-2.6/Azure-Repo.svg
rectangle "AzureRepo" <<$AzureRepo>> as AzureRepo
sprite $AzureRoleBasedAccessControl Azure-Full-Colour-2.6/Azure-Role-Based-Access-Control.svg
rectangle "AzureRoleBasedAccessControl" <<$AzureRoleBasedAccessControl>> as AzureRoleBasedAccessControl
sprite $AzureSpringCloud Azure-Full-Colour-2.6/Azure-Spring-Cloud.svg
rectangle "AzureSpringCloud" <<$AzureSpringCloud>> as AzureSpringCloud
sprite $AzureStackBackup Azure-Full-Colour-2.6/Azure-Stack-Backup.svg
rectangle "AzureStackBackup" <<$AzureStackBackup>> as AzureStackBackup
sprite $AzureStackCapacity Azure-Full-Colour-2.6/Azure-Stack-Capacity.svg
rectangle "AzureStackCapacity" <<$AzureStackCapacity>> as AzureStackCapacity
sprite $AzureStackEdgeManagement Azure-Full-Colour-2.6/Azure-Stack-Edge-Management.svg
rectangle "AzureStackEdgeManagement" <<$AzureStackEdgeManagement>> as AzureStackEdgeManagement
sprite $AzureStackOffer Azure-Full-Colour-2.6/Azure-Stack-Offer.svg
rectangle "AzureStackOffer" <<$AzureStackOffer>> as AzureStackOffer
sprite $AzureStackPlan Azure-Full-Colour-2.6/Azure-Stack-Plan.svg
rectangle "AzureStackPlan" <<$AzureStackPlan>> as AzureStackPlan
sprite $AzureStackUpdate Azure-Full-Colour-2.6/Azure-Stack-Update.svg
rectangle "AzureStackUpdate" <<$AzureStackUpdate>> as AzureStackUpdate
sprite $AzureStackUserSubscription Azure-Full-Colour-2.6/Azure-Stack-User-Subscription.svg
rectangle "AzureStackUserSubscription" <<$AzureStackUserSubscription>> as AzureStackUserSubscription
sprite $AzureStack Azure-Full-Colour-2.6/Azure-Stack.svg
rectangle "AzureStack" <<$AzureStack>> as AzureStack
sprite $AzureSynapseAnalytics Azure-Full-Colour-2.6/Azure-Synapse-Analytics.svg
rectangle "AzureSynapseAnalytics" <<$AzureSynapseAnalytics>> as AzureSynapseAnalytics
sprite $AzureTestPlan Azure-Full-Colour-2.6/Azure-Test-Plan.svg
rectangle "AzureTestPlan" <<$AzureTestPlan>> as AzureTestPlan
sprite $Azure Azure-Full-Colour-2.6/Azure.svg
rectangle "Azure" <<$Azure>> as Azure
sprite $Bastion Azure-Full-Colour-2.6/Bastion.svg
rectangle "Bastion" <<$Bastion>> as Bastion
sprite $BatchAI Azure-Full-Colour-2.6/Batch-AI.svg
rectangle "BatchAI" <<$BatchAI>> as BatchAI
sprite $BlockchainABSMember Azure-Full-Colour-2.6/Blockchain-ABS-Member.svg
rectangle "BlockchainABSMember" <<$BlockchainABSMember>> as BlockchainABSMember
sprite $BlockchainApplication Azure-Full-Colour-2.6/Blockchain-Application.svg
rectangle "BlockchainApplication" <<$BlockchainApplication>> as BlockchainApplication
sprite $BlockchainConnection Azure-Full-Colour-2.6/Blockchain-Connection.svg
rectangle "BlockchainConnection" <<$BlockchainConnection>> as BlockchainConnection
sprite $BlockchainConsortium Azure-Full-Colour-2.6/Blockchain-Consortium.svg
rectangle "BlockchainConsortium" <<$BlockchainConsortium>> as BlockchainConsortium
sprite $BlockchainDataManager Azure-Full-Colour-2.6/Blockchain-Data-Manager.svg
rectangle "BlockchainDataManager" <<$BlockchainDataManager>> as BlockchainDataManager
sprite $BlockchainDevkit Azure-Full-Colour-2.6/Blockchain-Devkit.svg
rectangle "BlockchainDevkit" <<$BlockchainDevkit>> as BlockchainDevkit
sprite $BlockchainStreaming Azure-Full-Colour-2.6/Blockchain-Streaming.svg
rectangle "BlockchainStreaming" <<$BlockchainStreaming>> as BlockchainStreaming
sprite $BlockchainToken Azure-Full-Colour-2.6/Blockchain-Token.svg
rectangle "BlockchainToken" <<$BlockchainToken>> as BlockchainToken
sprite $Blueprint Azure-Full-Colour-2.6/Blueprint.svg
rectangle "Blueprint" <<$Blueprint>> as Blueprint
sprite $BotService Azure-Full-Colour-2.6/Bot-Service.svg
rectangle "BotService" <<$BotService>> as BotService
sprite $Budget Azure-Full-Colour-2.6/Budget.svg
rectangle "Budget" <<$Budget>> as Budget
sprite $CDNProfile Azure-Full-Colour-2.6/CDN-Profile.svg
rectangle "CDNProfile" <<$CDNProfile>> as CDNProfile
sprite $ChangeAnalysis Azure-Full-Colour-2.6/Change-Analysis.svg
rectangle "ChangeAnalysis" <<$ChangeAnalysis>> as ChangeAnalysis
sprite $CitrixVirtualDesktopEssentials Azure-Full-Colour-2.6/Citrix-Virtual-Desktop-Essentials.svg
rectangle "CitrixVirtualDesktopEssentials" <<$CitrixVirtualDesktopEssentials>> as CitrixVirtualDesktopEssentials
sprite $ClientApp Azure-Full-Colour-2.6/Client-App.svg
rectangle "ClientApp" <<$ClientApp>> as ClientApp
sprite $CloudAppSecurity Azure-Full-Colour-2.6/Cloud-App-Security.svg
rectangle "CloudAppSecurity" <<$CloudAppSecurity>> as CloudAppSecurity
sprite $CloudServiceClassic Azure-Full-Colour-2.6/Cloud-Service-Classic.svg
rectangle "CloudServiceClassic" <<$CloudServiceClassic>> as CloudServiceClassic
sprite $CloudSimpleNode Azure-Full-Colour-2.6/Cloud-Simple-Node.svg
rectangle "CloudSimpleNode" <<$CloudSimpleNode>> as CloudSimpleNode
sprite $CloudSimpleService Azure-Full-Colour-2.6/Cloud-Simple-Service.svg
rectangle "CloudSimpleService" <<$CloudSimpleService>> as CloudSimpleService
sprite $CloudSimpleVirtualMachine Azure-Full-Colour-2.6/Cloud-Simple-Virtual-Machine.svg
rectangle "CloudSimpleVirtualMachine" <<$CloudSimpleVirtualMachine>> as CloudSimpleVirtualMachine
sprite $CognitiveServicesDecision Azure-Full-Colour-2.6/Cognitive-Services-Decision.svg
rectangle "CognitiveServicesDecision" <<$CognitiveServicesDecision>> as CognitiveServicesDecision
sprite $CognitiveServicesKnowledge Azure-Full-Colour-2.6/Cognitive-Services-Knowledge.svg
rectangle "CognitiveServicesKnowledge" <<$CognitiveServicesKnowledge>> as CognitiveServicesKnowledge
sprite $CognitiveServicesLanguage Azure-Full-Colour-2.6/Cognitive-Services-Language.svg
rectangle "CognitiveServicesLanguage" <<$CognitiveServicesLanguage>> as CognitiveServicesLanguage
sprite $CognitiveServicesSearch Azure-Full-Colour-2.6/Cognitive-Services-Search.svg
rectangle "CognitiveServicesSearch" <<$CognitiveServicesSearch>> as CognitiveServicesSearch
sprite $CognitiveServicesSpeech Azure-Full-Colour-2.6/Cognitive-Services-Speech.svg
rectangle "CognitiveServicesSpeech" <<$CognitiveServicesSpeech>> as CognitiveServicesSpeech
sprite $CognitiveServicesVision Azure-Full-Colour-2.6/Cognitive-Services-Vision.svg
rectangle "CognitiveServicesVision" <<$CognitiveServicesVision>> as CognitiveServicesVision
sprite $CognitiveServices Azure-Full-Colour-2.6/Cognitive-Services.svg
rectangle "CognitiveServices" <<$CognitiveServices>> as CognitiveServices
sprite $CompanyBranding Azure-Full-Colour-2.6/Company-Branding.svg
rectangle "CompanyBranding" <<$CompanyBranding>> as CompanyBranding
sprite $Compliance Azure-Full-Colour-2.6/Compliance.svg
rectangle "Compliance" <<$Compliance>> as Compliance
sprite $Compute&App Azure-Full-Colour-2.6/Compute-&-App.svg
rectangle "Compute&App" <<$Compute&App>> as Compute&App
sprite $ConditionalAccess Azure-Full-Colour-2.6/Conditional-Access.svg
rectangle "ConditionalAccess" <<$ConditionalAccess>> as ConditionalAccess
sprite $ConfigurationManagement Azure-Full-Colour-2.6/Configuration-Management.svg
rectangle "ConfigurationManagement" <<$ConfigurationManagement>> as ConfigurationManagement
sprite $Configuration Azure-Full-Colour-2.6/Configuration.svg
rectangle "Configuration" <<$Configuration>> as Configuration
sprite $ConnectionMonitor Azure-Full-Colour-2.6/Connection-Monitor.svg
rectangle "ConnectionMonitor" <<$ConnectionMonitor>> as ConnectionMonitor
sprite $ContainerBatchAccount Azure-Full-Colour-2.6/Container-Batch-Account.svg
rectangle "ContainerBatchAccount" <<$ContainerBatchAccount>> as ContainerBatchAccount
sprite $ContainerInstance Azure-Full-Colour-2.6/Container-Instance.svg
rectangle "ContainerInstance" <<$ContainerInstance>> as ContainerInstance
sprite $ContainerKubernetesService Azure-Full-Colour-2.6/Container-Kubernetes-Service.svg
rectangle "ContainerKubernetesService" <<$ContainerKubernetesService>> as ContainerKubernetesService
sprite $ContainerRegistry Azure-Full-Colour-2.6/Container-Registry.svg
rectangle "ContainerRegistry" <<$ContainerRegistry>> as ContainerRegistry
sprite $ContainerServiceFabricCluster Azure-Full-Colour-2.6/Container-Service-Fabric-Cluster.svg
rectangle "ContainerServiceFabricCluster" <<$ContainerServiceFabricCluster>> as ContainerServiceFabricCluster
sprite $Controller Azure-Full-Colour-2.6/Controller.svg
rectangle "Controller" <<$Controller>> as Controller
sprite $CORS Azure-Full-Colour-2.6/CORS.svg
rectangle "CORS" <<$CORS>> as CORS
sprite $CostAlert Azure-Full-Colour-2.6/Cost-Alert.svg
rectangle "CostAlert" <<$CostAlert>> as CostAlert
sprite $CostAnalysis Azure-Full-Colour-2.6/Cost-Analysis.svg
rectangle "CostAnalysis" <<$CostAnalysis>> as CostAnalysis
sprite $CostManagementAndBilling Azure-Full-Colour-2.6/Cost-Management-And-Billing.svg
rectangle "CostManagementAndBilling" <<$CostManagementAndBilling>> as CostManagementAndBilling
sprite $CostManagement Azure-Full-Colour-2.6/Cost-Management.svg
rectangle "CostManagement" <<$CostManagement>> as CostManagement
sprite $Cost Azure-Full-Colour-2.6/Cost.svg
rectangle "Cost" <<$Cost>> as Cost
sprite $CustomerLockboxForMicrosoftAzure Azure-Full-Colour-2.6/Customer-Lockbox-For-Microsoft-Azure.svg
rectangle "CustomerLockboxForMicrosoftAzure" <<$CustomerLockboxForMicrosoftAzure>> as CustomerLockboxForMicrosoftAzure
sprite $DataAndStorage Azure-Full-Colour-2.6/Data-And-Storage.svg
rectangle "DataAndStorage" <<$DataAndStorage>> as DataAndStorage
sprite $DataBoxEdgeAndGateway Azure-Full-Colour-2.6/Data-Box-Edge-And-Gateway.svg
rectangle "DataBoxEdgeAndGateway" <<$DataBoxEdgeAndGateway>> as DataBoxEdgeAndGateway
sprite $DataBox Azure-Full-Colour-2.6/Data-Box.svg
rectangle "DataBox" <<$DataBox>> as DataBox
sprite $DataCatalog Azure-Full-Colour-2.6/Data-Catalog.svg
rectangle "DataCatalog" <<$DataCatalog>> as DataCatalog
sprite $DataFactory Azure-Full-Colour-2.6/Data-Factory.svg
rectangle "DataFactory" <<$DataFactory>> as DataFactory
sprite $DataLakeAnalytics Azure-Full-Colour-2.6/Data-Lake-Analytics.svg
rectangle "DataLakeAnalytics" <<$DataLakeAnalytics>> as DataLakeAnalytics
sprite $DataLakeStorageGen1 Azure-Full-Colour-2.6/Data-Lake-Storage-Gen1.svg
rectangle "DataLakeStorageGen1" <<$DataLakeStorageGen1>> as DataLakeStorageGen1
sprite $DataLake Azure-Full-Colour-2.6/Data-Lake.svg
rectangle "DataLake" <<$DataLake>> as DataLake
sprite $DataShareInvitation Azure-Full-Colour-2.6/Data-Share-Invitation.svg
rectangle "DataShareInvitation" <<$DataShareInvitation>> as DataShareInvitation
sprite $DataShare Azure-Full-Colour-2.6/Data-Share.svg
rectangle "DataShare" <<$DataShare>> as DataShare
sprite $DataTransfer Azure-Full-Colour-2.6/Data-Transfer.svg
rectangle "DataTransfer" <<$DataTransfer>> as DataTransfer
sprite $DatabaseMigrationService Azure-Full-Colour-2.6/Database-Migration-Service.svg
rectangle "DatabaseMigrationService" <<$DatabaseMigrationService>> as DatabaseMigrationService
sprite $DdosProtectionPlan Azure-Full-Colour-2.6/Ddos-Protection-Plan.svg
rectangle "DdosProtectionPlan" <<$DdosProtectionPlan>> as DdosProtectionPlan
sprite $DDOSProtection Azure-Full-Colour-2.6/DDOS-Protection.svg
rectangle "DDOSProtection" <<$DDOSProtection>> as DDOSProtection
sprite $DeploymentScript Azure-Full-Colour-2.6/Deployment-Script.svg
rectangle "DeploymentScript" <<$DeploymentScript>> as DeploymentScript
sprite $Deployment Azure-Full-Colour-2.6/Deployment.svg
rectangle "Deployment" <<$Deployment>> as Deployment
sprite $DevopsProject Azure-Full-Colour-2.6/Devops-Project.svg
rectangle "DevopsProject" <<$DevopsProject>> as DevopsProject
sprite $DevtestLab Azure-Full-Colour-2.6/Devtest-Lab.svg
rectangle "DevtestLab" <<$DevtestLab>> as DevtestLab
sprite $DiagnosticsSetting Azure-Full-Colour-2.6/Diagnostics-Setting.svg
rectangle "DiagnosticsSetting" <<$DiagnosticsSetting>> as DiagnosticsSetting
sprite $DiskEncryptionSet Azure-Full-Colour-2.6/Disk-Encryption-Set.svg
rectangle "DiskEncryptionSet" <<$DiskEncryptionSet>> as DiskEncryptionSet
sprite $DNSZone Azure-Full-Colour-2.6/DNS-Zone.svg
rectangle "DNSZone" <<$DNSZone>> as DNSZone
sprite $Ebook Azure-Full-Colour-2.6/Ebook.svg
rectangle "Ebook" <<$Ebook>> as Ebook
sprite $Education Azure-Full-Colour-2.6/Education.svg
rectangle "Education" <<$Education>> as Education
sprite $ElasticJobAgent Azure-Full-Colour-2.6/Elastic-Job-Agent.svg
rectangle "ElasticJobAgent" <<$ElasticJobAgent>> as ElasticJobAgent
sprite $EndpointSecurity Azure-Full-Colour-2.6/Endpoint-Security.svg
rectangle "EndpointSecurity" <<$EndpointSecurity>> as EndpointSecurity
sprite $EnterpriseApplication Azure-Full-Colour-2.6/Enterprise-Application.svg
rectangle "EnterpriseApplication" <<$EnterpriseApplication>> as EnterpriseApplication
sprite $EventGridDomain Azure-Full-Colour-2.6/Event-Grid-Domain.svg
rectangle "EventGridDomain" <<$EventGridDomain>> as EventGridDomain
sprite $EventGridSubscription Azure-Full-Colour-2.6/Event-Grid-Subscription.svg
rectangle "EventGridSubscription" <<$EventGridSubscription>> as EventGridSubscription
sprite $EventGridTopic Azure-Full-Colour-2.6/Event-Grid-Topic.svg
rectangle "EventGridTopic" <<$EventGridTopic>> as EventGridTopic
sprite $EventHubCluster Azure-Full-Colour-2.6/Event-Hub-Cluster.svg
rectangle "EventHubCluster" <<$EventHubCluster>> as EventHubCluster
sprite $EventHub Azure-Full-Colour-2.6/Event-Hub.svg
rectangle "EventHub" <<$EventHub>> as EventHub
sprite $Event Azure-Full-Colour-2.6/Event.svg
rectangle "Event" <<$Event>> as Event
sprite $ExportTemplate Azure-Full-Colour-2.6/Export-Template.svg
rectangle "ExportTemplate" <<$ExportTemplate>> as ExportTemplate
sprite $ExpressrouteCircuit Azure-Full-Colour-2.6/Expressroute-Circuit.svg
rectangle "ExpressrouteCircuit" <<$ExpressrouteCircuit>> as ExpressrouteCircuit
sprite $ExpressrouteConnection Azure-Full-Colour-2.6/Expressroute-Connection.svg
rectangle "ExpressrouteConnection" <<$ExpressrouteConnection>> as ExpressrouteConnection
sprite $ExpressrouteFilter Azure-Full-Colour-2.6/Expressroute-Filter.svg
rectangle "ExpressrouteFilter" <<$ExpressrouteFilter>> as ExpressrouteFilter
sprite $ExtendedSecurityUpdates Azure-Full-Colour-2.6/Extended-Security-Updates.svg
rectangle "ExtendedSecurityUpdates" <<$ExtendedSecurityUpdates>> as ExtendedSecurityUpdates
sprite $Extension Azure-Full-Colour-2.6/Extension.svg
rectangle "Extension" <<$Extension>> as Extension
sprite $FileIntegrityMonitoring Azure-Full-Colour-2.6/File-Integrity-Monitoring.svg
rectangle "FileIntegrityMonitoring" <<$FileIntegrityMonitoring>> as FileIntegrityMonitoring
sprite $FileShare Azure-Full-Colour-2.6/File-Share.svg
rectangle "FileShare" <<$FileShare>> as FileShare
sprite $FirewallManager Azure-Full-Colour-2.6/Firewall-Manager.svg
rectangle "FirewallManager" <<$FirewallManager>> as FirewallManager
sprite $FirewallPolicy Azure-Full-Colour-2.6/Firewall-Policy.svg
rectangle "FirewallPolicy" <<$FirewallPolicy>> as FirewallPolicy
sprite $Firewall Azure-Full-Colour-2.6/Firewall.svg
rectangle "Firewall" <<$Firewall>> as Firewall
sprite $FreeServices Azure-Full-Colour-2.6/Free-Services.svg
rectangle "FreeServices" <<$FreeServices>> as FreeServices
sprite $FunctionApp Azure-Full-Colour-2.6/Function-App.svg
rectangle "FunctionApp" <<$FunctionApp>> as FunctionApp
sprite $GenomicsAccount Azure-Full-Colour-2.6/Genomics-Account.svg
rectangle "GenomicsAccount" <<$GenomicsAccount>> as GenomicsAccount
sprite $GeoReplication Azure-Full-Colour-2.6/Geo-Replication.svg
rectangle "GeoReplication" <<$GeoReplication>> as GeoReplication
sprite $HdinsightCluster Azure-Full-Colour-2.6/Hdinsight-Cluster.svg
rectangle "HdinsightCluster" <<$HdinsightCluster>> as HdinsightCluster
sprite $HelpAndSupport Azure-Full-Colour-2.6/Help-And-Support.svg
rectangle "HelpAndSupport" <<$HelpAndSupport>> as HelpAndSupport
sprite $HighAvailability Azure-Full-Colour-2.6/High-Availability.svg
rectangle "HighAvailability" <<$HighAvailability>> as HighAvailability
sprite $HostGroup Azure-Full-Colour-2.6/Host-Group.svg
rectangle "HostGroup" <<$HostGroup>> as HostGroup
sprite $Host Azure-Full-Colour-2.6/Host.svg
rectangle "Host" <<$Host>> as Host
sprite $HPCCache Azure-Full-Colour-2.6/HPC-Cache.svg
rectangle "HPCCache" <<$HPCCache>> as HPCCache
sprite $Hunting Azure-Full-Colour-2.6/Hunting.svg
rectangle "Hunting" <<$Hunting>> as Hunting
sprite $IdentityAndAccess Azure-Full-Colour-2.6/Identity-And-Access.svg
rectangle "IdentityAndAccess" <<$IdentityAndAccess>> as IdentityAndAccess
sprite $IdentityGovernance Azure-Full-Colour-2.6/Identity-Governance.svg
rectangle "IdentityGovernance" <<$IdentityGovernance>> as IdentityGovernance
sprite $ImportExportJob Azure-Full-Colour-2.6/Import-Export-Job.svg
rectangle "ImportExportJob" <<$ImportExportJob>> as ImportExportJob
sprite $Incident Azure-Full-Colour-2.6/Incident.svg
rectangle "Incident" <<$Incident>> as Incident
sprite $IntegrationAccount Azure-Full-Colour-2.6/Integration-Account.svg
rectangle "IntegrationAccount" <<$IntegrationAccount>> as IntegrationAccount
sprite $IntegrationServiceEnvironment Azure-Full-Colour-2.6/Integration-Service-Environment.svg
rectangle "IntegrationServiceEnvironment" <<$IntegrationServiceEnvironment>> as IntegrationServiceEnvironment
sprite $InternetAnalyzerProfile Azure-Full-Colour-2.6/Internet-Analyzer-Profile.svg
rectangle "InternetAnalyzerProfile" <<$InternetAnalyzerProfile>> as InternetAnalyzerProfile
sprite $IntuneAppProtection Azure-Full-Colour-2.6/Intune-App-Protection.svg
rectangle "IntuneAppProtection" <<$IntuneAppProtection>> as IntuneAppProtection
sprite $IntuneDeviceCompliance Azure-Full-Colour-2.6/Intune-Device-Compliance.svg
rectangle "IntuneDeviceCompliance" <<$IntuneDeviceCompliance>> as IntuneDeviceCompliance
sprite $IntuneDeviceConfiguration Azure-Full-Colour-2.6/Intune-Device-Configuration.svg
rectangle "IntuneDeviceConfiguration" <<$IntuneDeviceConfiguration>> as IntuneDeviceConfiguration
sprite $IntuneDeviceEnrolment Azure-Full-Colour-2.6/Intune-Device-Enrolment.svg
rectangle "IntuneDeviceEnrolment" <<$IntuneDeviceEnrolment>> as IntuneDeviceEnrolment
sprite $IntuneDevice Azure-Full-Colour-2.6/Intune-Device.svg
rectangle "IntuneDevice" <<$IntuneDevice>> as IntuneDevice
sprite $IntuneExchangeAccess Azure-Full-Colour-2.6/Intune-Exchange-Access.svg
rectangle "IntuneExchangeAccess" <<$IntuneExchangeAccess>> as IntuneExchangeAccess
sprite $IntuneExchangeOnPremisesAccess Azure-Full-Colour-2.6/Intune-Exchange-On-Premises-Access.svg
rectangle "IntuneExchangeOnPremisesAccess" <<$IntuneExchangeOnPremisesAccess>> as IntuneExchangeOnPremisesAccess
sprite $IntuneManagedDesktop Azure-Full-Colour-2.6/Intune-Managed-Desktop.svg
rectangle "IntuneManagedDesktop" <<$IntuneManagedDesktop>> as IntuneManagedDesktop
sprite $IntuneSecurityBaseline Azure-Full-Colour-2.6/Intune-Security-Baseline.svg
rectangle "IntuneSecurityBaseline" <<$IntuneSecurityBaseline>> as IntuneSecurityBaseline
sprite $IntuneSoftwareUpdate Azure-Full-Colour-2.6/Intune-Software-Update.svg
rectangle "IntuneSoftwareUpdate" <<$IntuneSoftwareUpdate>> as IntuneSoftwareUpdate
sprite $IntuneTenantStatus Azure-Full-Colour-2.6/Intune-Tenant-Status.svg
rectangle "IntuneTenantStatus" <<$IntuneTenantStatus>> as IntuneTenantStatus
sprite $Intune Azure-Full-Colour-2.6/Intune.svg
rectangle "Intune" <<$Intune>> as Intune
sprite $IotCentral Azure-Full-Colour-2.6/Iot-Central.svg
rectangle "IotCentral" <<$IotCentral>> as IotCentral
sprite $IotDeviceProvisioningService Azure-Full-Colour-2.6/Iot-Device-Provisioning-Service.svg
rectangle "IotDeviceProvisioningService" <<$IotDeviceProvisioningService>> as IotDeviceProvisioningService
sprite $IotDigitalTwin Azure-Full-Colour-2.6/Iot-Digital-Twin.svg
rectangle "IotDigitalTwin" <<$IotDigitalTwin>> as IotDigitalTwin
sprite $IotEdge Azure-Full-Colour-2.6/Iot-Edge.svg
rectangle "IotEdge" <<$IotEdge>> as IotEdge
sprite $IotHubSecurity Azure-Full-Colour-2.6/Iot-Hub-Security.svg
rectangle "IotHubSecurity" <<$IotHubSecurity>> as IotHubSecurity
sprite $IotHub Azure-Full-Colour-2.6/Iot-Hub.svg
rectangle "IotHub" <<$IotHub>> as IotHub
sprite $IotSolutionAccelerator Azure-Full-Colour-2.6/Iot-Solution-Accelerator.svg
rectangle "IotSolutionAccelerator" <<$IotSolutionAccelerator>> as IotSolutionAccelerator
sprite $IotSphere Azure-Full-Colour-2.6/Iot-Sphere.svg
rectangle "IotSphere" <<$IotSphere>> as IotSphere
sprite $IotWindows10Core Azure-Full-Colour-2.6/Iot-Windows-10-Core.svg
rectangle "IotWindows10Core" <<$IotWindows10Core>> as IotWindows10Core
sprite $IPGroup Azure-Full-Colour-2.6/IP-Group.svg
rectangle "IPGroup" <<$IPGroup>> as IPGroup
sprite $Java Azure-Full-Colour-2.6/Java.svg
rectangle "Java" <<$Java>> as Java
sprite $KeyVaultHSM Azure-Full-Colour-2.6/Key-Vault-HSM.svg
rectangle "KeyVaultHSM" <<$KeyVaultHSM>> as KeyVaultHSM
sprite $KeyVault Azure-Full-Colour-2.6/Key-Vault.svg
rectangle "KeyVault" <<$KeyVault>> as KeyVault
sprite $LabService Azure-Full-Colour-2.6/Lab-Service.svg
rectangle "LabService" <<$LabService>> as LabService
sprite $License Azure-Full-Colour-2.6/License.svg
rectangle "License" <<$License>> as License
sprite $LoadBalancer Azure-Full-Colour-2.6/Load-Balancer.svg
rectangle "LoadBalancer" <<$LoadBalancer>> as LoadBalancer
sprite $LocalNetworkGateway Azure-Full-Colour-2.6/Local-Network-Gateway.svg
rectangle "LocalNetworkGateway" <<$LocalNetworkGateway>> as LocalNetworkGateway
sprite $LogAnalyticsSolution Azure-Full-Colour-2.6/Log-Analytics-Solution.svg
rectangle "LogAnalyticsSolution" <<$LogAnalyticsSolution>> as LogAnalyticsSolution
sprite $LogAnalyticsWorkspace Azure-Full-Colour-2.6/Log-Analytics-Workspace.svg
rectangle "LogAnalyticsWorkspace" <<$LogAnalyticsWorkspace>> as LogAnalyticsWorkspace
sprite $LogicAppCustomConnecton Azure-Full-Colour-2.6/Logic-App-Custom-Connecton.svg
rectangle "LogicAppCustomConnecton" <<$LogicAppCustomConnecton>> as LogicAppCustomConnecton
sprite $LogicApp Azure-Full-Colour-2.6/Logic-App.svg
rectangle "LogicApp" <<$LogicApp>> as LogicApp
sprite $MachineLearningStudioWebServiceClassic Azure-Full-Colour-2.6/Machine-Learning-Studio-Web-Service-Classic.svg
rectangle "MachineLearningStudioWebServiceClassic" <<$MachineLearningStudioWebServiceClassic>> as MachineLearningStudioWebServiceClassic
sprite $MachineLearningStudioWebServicePlanClassic Azure-Full-Colour-2.6/Machine-Learning-Studio-Web-Service-Plan-Classic.svg
rectangle "MachineLearningStudioWebServicePlanClassic" <<$MachineLearningStudioWebServicePlanClassic>> as MachineLearningStudioWebServicePlanClassic
sprite $MachineLearningStudioWorkspaceClassic Azure-Full-Colour-2.6/Machine-Learning-Studio-Workspace-Classic.svg
rectangle "MachineLearningStudioWorkspaceClassic" <<$MachineLearningStudioWorkspaceClassic>> as MachineLearningStudioWorkspaceClassic
sprite $MachineLearningStudio Azure-Full-Colour-2.6/Machine-Learning-Studio.svg
rectangle "MachineLearningStudio" <<$MachineLearningStudio>> as MachineLearningStudio
sprite $MachineLearning Azure-Full-Colour-2.6/Machine-Learning.svg
rectangle "MachineLearning" <<$MachineLearning>> as MachineLearning
sprite $MaintenanceConfiguration Azure-Full-Colour-2.6/Maintenance-Configuration.svg
rectangle "MaintenanceConfiguration" <<$MaintenanceConfiguration>> as MaintenanceConfiguration
sprite $ManagedApplicationCenter Azure-Full-Colour-2.6/Managed-Application-Center.svg
rectangle "ManagedApplicationCenter" <<$ManagedApplicationCenter>> as ManagedApplicationCenter
sprite $ManagedApplication Azure-Full-Colour-2.6/Managed-Application.svg
rectangle "ManagedApplication" <<$ManagedApplication>> as ManagedApplication
sprite $ManagedDatabase Azure-Full-Colour-2.6/Managed-Database.svg
rectangle "ManagedDatabase" <<$ManagedDatabase>> as ManagedDatabase
sprite $ManagedDiskPremiumSSD Azure-Full-Colour-2.6/Managed-Disk-Premium-SSD.svg
rectangle "ManagedDiskPremiumSSD" <<$ManagedDiskPremiumSSD>> as ManagedDiskPremiumSSD
sprite $ManagedDiskSnapshot Azure-Full-Colour-2.6/Managed-Disk-Snapshot.svg
rectangle "ManagedDiskSnapshot" <<$ManagedDiskSnapshot>> as ManagedDiskSnapshot
sprite $ManagedDiskStandardHDD Azure-Full-Colour-2.6/Managed-Disk-Standard-HDD.svg
rectangle "ManagedDiskStandardHDD" <<$ManagedDiskStandardHDD>> as ManagedDiskStandardHDD
sprite $ManagedDiskStandardSSD Azure-Full-Colour-2.6/Managed-Disk-Standard-SSD.svg
rectangle "ManagedDiskStandardSSD" <<$ManagedDiskStandardSSD>> as ManagedDiskStandardSSD
sprite $ManagedDiskUltraSSD Azure-Full-Colour-2.6/Managed-Disk-Ultra-SSD.svg
rectangle "ManagedDiskUltraSSD" <<$ManagedDiskUltraSSD>> as ManagedDiskUltraSSD
sprite $ManagementCertificate Azure-Full-Colour-2.6/Management-Certificate.svg
rectangle "ManagementCertificate" <<$ManagementCertificate>> as ManagementCertificate
sprite $ManagementGroup Azure-Full-Colour-2.6/Management-Group.svg
rectangle "ManagementGroup" <<$ManagementGroup>> as ManagementGroup
sprite $Marketplace Azure-Full-Colour-2.6/Marketplace.svg
rectangle "Marketplace" <<$Marketplace>> as Marketplace
sprite $MeshApplication Azure-Full-Colour-2.6/Mesh-Application.svg
rectangle "MeshApplication" <<$MeshApplication>> as MeshApplication
sprite $Metric Azure-Full-Colour-2.6/Metric.svg
rectangle "Metric" <<$Metric>> as Metric
sprite $MicrosoftAccount Azure-Full-Colour-2.6/Microsoft-Account.svg
rectangle "MicrosoftAccount" <<$MicrosoftAccount>> as MicrosoftAccount
sprite $MobileApplication Azure-Full-Colour-2.6/Mobile-Application.svg
rectangle "MobileApplication" <<$MobileApplication>> as MobileApplication
sprite $Mobility(MDMAndMAM) Azure-Full-Colour-2.6/Mobility-(MDM-And-MAM).svg
rectangle "Mobility(MDMAndMAM)" <<$Mobility(MDMAndMAM)>> as Mobility(MDMAndMAM)
sprite $Monitor Azure-Full-Colour-2.6/Monitor.svg
rectangle "Monitor" <<$Monitor>> as Monitor
sprite $NATGateway Azure-Full-Colour-2.6/NAT-Gateway.svg
rectangle "NATGateway" <<$NATGateway>> as NATGateway
sprite $NetworkInterface Azure-Full-Colour-2.6/Network-Interface.svg
rectangle "NetworkInterface" <<$NetworkInterface>> as NetworkInterface
sprite $NetworkSecurityGroupClassic Azure-Full-Colour-2.6/Network-Security-Group-Classic.svg
rectangle "NetworkSecurityGroupClassic" <<$NetworkSecurityGroupClassic>> as NetworkSecurityGroupClassic
sprite $NetworkSecurityGroup Azure-Full-Colour-2.6/Network-Security-Group.svg
rectangle "NetworkSecurityGroup" <<$NetworkSecurityGroup>> as NetworkSecurityGroup
sprite $NetworkWatcher Azure-Full-Colour-2.6/Network-Watcher.svg
rectangle "NetworkWatcher" <<$NetworkWatcher>> as NetworkWatcher
sprite $Networking Azure-Full-Colour-2.6/Networking.svg
rectangle "Networking" <<$Networking>> as Networking
sprite $NodeJS Azure-Full-Colour-2.6/Node-JS.svg
rectangle "NodeJS" <<$NodeJS>> as NodeJS
sprite $NotificationHub Azure-Full-Colour-2.6/Notification-Hub.svg
rectangle "NotificationHub" <<$NotificationHub>> as NotificationHub
sprite $OnPremisesDataGateway Azure-Full-Colour-2.6/On-Premises-Data-Gateway.svg
rectangle "OnPremisesDataGateway" <<$OnPremisesDataGateway>> as OnPremisesDataGateway
sprite $OpenDataset Azure-Full-Colour-2.6/Open-Dataset.svg
rectangle "OpenDataset" <<$OpenDataset>> as OpenDataset
sprite $OpenshiftCluster Azure-Full-Colour-2.6/Openshift-Cluster.svg
rectangle "OpenshiftCluster" <<$OpenshiftCluster>> as OpenshiftCluster
sprite $OperationalExcellence Azure-Full-Colour-2.6/Operational-Excellence.svg
rectangle "OperationalExcellence" <<$OperationalExcellence>> as OperationalExcellence
sprite $OrganisationalRelationship Azure-Full-Colour-2.6/Organisational-Relationship.svg
rectangle "OrganisationalRelationship" <<$OrganisationalRelationship>> as OrganisationalRelationship
sprite $PeeringService Azure-Full-Colour-2.6/Peering-Service.svg
rectangle "PeeringService" <<$PeeringService>> as PeeringService
sprite $PerformanceDiagnostics Azure-Full-Colour-2.6/Performance-Diagnostics.svg
rectangle "PerformanceDiagnostics" <<$PerformanceDiagnostics>> as PerformanceDiagnostics
sprite $Performance Azure-Full-Colour-2.6/Performance.svg
rectangle "Performance" <<$Performance>> as Performance
sprite $Playbooks Azure-Full-Colour-2.6/Playbooks.svg
rectangle "Playbooks" <<$Playbooks>> as Playbooks
sprite $Policy Azure-Full-Colour-2.6/Policy.svg
rectangle "Policy" <<$Policy>> as Policy
sprite $PowerBIEmbedded Azure-Full-Colour-2.6/Power-BI-Embedded.svg
rectangle "PowerBIEmbedded" <<$PowerBIEmbedded>> as PowerBIEmbedded
sprite $PowerBI Azure-Full-Colour-2.6/Power-BI.svg
rectangle "PowerBI" <<$PowerBI>> as PowerBI
sprite $Powershell Azure-Full-Colour-2.6/Powershell.svg
rectangle "Powershell" <<$Powershell>> as Powershell
sprite $PrivateDNSZone Azure-Full-Colour-2.6/Private-DNS-Zone.svg
rectangle "PrivateDNSZone" <<$PrivateDNSZone>> as PrivateDNSZone
sprite $PrivateEndpoint Azure-Full-Colour-2.6/Private-Endpoint.svg
rectangle "PrivateEndpoint" <<$PrivateEndpoint>> as PrivateEndpoint
sprite $PrivateLink Azure-Full-Colour-2.6/Private-Link.svg
rectangle "PrivateLink" <<$PrivateLink>> as PrivateLink
sprite $Property Azure-Full-Colour-2.6/Property.svg
rectangle "Property" <<$Property>> as Property
sprite $ProximityPlacementGroup Azure-Full-Colour-2.6/Proximity-Placement-Group.svg
rectangle "ProximityPlacementGroup" <<$ProximityPlacementGroup>> as ProximityPlacementGroup
sprite $PublicIPAddress Azure-Full-Colour-2.6/Public-IP-Address.svg
rectangle "PublicIPAddress" <<$PublicIPAddress>> as PublicIPAddress
sprite $PublicIPPrefix Azure-Full-Colour-2.6/Public-IP-Prefix.svg
rectangle "PublicIPPrefix" <<$PublicIPPrefix>> as PublicIPPrefix
sprite $Python Azure-Full-Colour-2.6/Python.svg
rectangle "Python" <<$Python>> as Python
sprite $QuickstartCenter Azure-Full-Colour-2.6/Quickstart-Center.svg
rectangle "QuickstartCenter" <<$QuickstartCenter>> as QuickstartCenter
sprite $Recent Azure-Full-Colour-2.6/Recent.svg
rectangle "Recent" <<$Recent>> as Recent
sprite $RecoveryServicesVault Azure-Full-Colour-2.6/Recovery-Services-Vault.svg
rectangle "RecoveryServicesVault" <<$RecoveryServicesVault>> as RecoveryServicesVault
sprite $RegulatoryCompliance Azure-Full-Colour-2.6/Regulatory-Compliance.svg
rectangle "RegulatoryCompliance" <<$RegulatoryCompliance>> as RegulatoryCompliance
sprite $Relay Azure-Full-Colour-2.6/Relay.svg
rectangle "Relay" <<$Relay>> as Relay
sprite $RemoteRenderingAccount Azure-Full-Colour-2.6/Remote-Rendering-Account.svg
rectangle "RemoteRenderingAccount" <<$RemoteRenderingAccount>> as RemoteRenderingAccount
sprite $Reservation Azure-Full-Colour-2.6/Reservation.svg
rectangle "Reservation" <<$Reservation>> as Reservation
sprite $ReservedIPAddressClassic Azure-Full-Colour-2.6/Reserved-IP-Address-Classic.svg
rectangle "ReservedIPAddressClassic" <<$ReservedIPAddressClassic>> as ReservedIPAddressClassic
sprite $ResourceExplorer Azure-Full-Colour-2.6/Resource-Explorer.svg
rectangle "ResourceExplorer" <<$ResourceExplorer>> as ResourceExplorer
sprite $ResourceGraphExplorer Azure-Full-Colour-2.6/Resource-Graph-Explorer.svg
rectangle "ResourceGraphExplorer" <<$ResourceGraphExplorer>> as ResourceGraphExplorer
sprite $ResourceGraphQuery Azure-Full-Colour-2.6/Resource-Graph-Query.svg
rectangle "ResourceGraphQuery" <<$ResourceGraphQuery>> as ResourceGraphQuery
sprite $ResourceGroup Azure-Full-Colour-2.6/Resource-Group.svg
rectangle "ResourceGroup" <<$ResourceGroup>> as ResourceGroup
sprite $ResourceHealth Azure-Full-Colour-2.6/Resource-Health.svg
rectangle "ResourceHealth" <<$ResourceHealth>> as ResourceHealth
sprite $REST Azure-Full-Colour-2.6/REST.svg
rectangle "REST" <<$REST>> as REST
sprite $ReviewAccess Azure-Full-Colour-2.6/Review-Access.svg
rectangle "ReviewAccess" <<$ReviewAccess>> as ReviewAccess
sprite $Role Azure-Full-Colour-2.6/Role.svg
rectangle "Role" <<$Role>> as Role
sprite $Rollout Azure-Full-Colour-2.6/Rollout.svg
rectangle "Rollout" <<$Rollout>> as Rollout
sprite $RouteFilter Azure-Full-Colour-2.6/Route-Filter.svg
rectangle "RouteFilter" <<$RouteFilter>> as RouteFilter
sprite $RouteTable Azure-Full-Colour-2.6/Route-Table.svg
rectangle "RouteTable" <<$RouteTable>> as RouteTable
sprite $RunCommand Azure-Full-Colour-2.6/Run-Command.svg
rectangle "RunCommand" <<$RunCommand>> as RunCommand
sprite $SAPHANAOnAzure Azure-Full-Colour-2.6/SAP-HANA-On-Azure.svg
rectangle "SAPHANAOnAzure" <<$SAPHANAOnAzure>> as SAPHANAOnAzure
sprite $SchedulerJobCollection Azure-Full-Colour-2.6/Scheduler-Job-Collection.svg
rectangle "SchedulerJobCollection" <<$SchedulerJobCollection>> as SchedulerJobCollection
sprite $SearchService Azure-Full-Colour-2.6/Search-Service.svg
rectangle "SearchService" <<$SearchService>> as SearchService
sprite $SecureScore Azure-Full-Colour-2.6/Secure-Score.svg
rectangle "SecureScore" <<$SecureScore>> as SecureScore
sprite $SecurityBaseline Azure-Full-Colour-2.6/Security-Baseline.svg
rectangle "SecurityBaseline" <<$SecurityBaseline>> as SecurityBaseline
sprite $SecurityCenter Azure-Full-Colour-2.6/Security-Center.svg
rectangle "SecurityCenter" <<$SecurityCenter>> as SecurityCenter
sprite $SecurityDetonationChamber Azure-Full-Colour-2.6/Security-Detonation-Chamber.svg
rectangle "SecurityDetonationChamber" <<$SecurityDetonationChamber>> as SecurityDetonationChamber
sprite $SendgridAccount Azure-Full-Colour-2.6/Sendgrid-Account.svg
rectangle "SendgridAccount" <<$SendgridAccount>> as SendgridAccount
sprite $Sentinel Azure-Full-Colour-2.6/Sentinel.svg
rectangle "Sentinel" <<$Sentinel>> as Sentinel
sprite $ServiceBus Azure-Full-Colour-2.6/Service-Bus.svg
rectangle "ServiceBus" <<$ServiceBus>> as ServiceBus
sprite $ServiceCatalogManagedApplicationDefinition Azure-Full-Colour-2.6/Service-Catalog-Managed-Application-Definition.svg
rectangle "ServiceCatalogManagedApplicationDefinition" <<$ServiceCatalogManagedApplicationDefinition>> as ServiceCatalogManagedApplicationDefinition
sprite $ServiceEndpointPolicy Azure-Full-Colour-2.6/Service-Endpoint-Policy.svg
rectangle "ServiceEndpointPolicy" <<$ServiceEndpointPolicy>> as ServiceEndpointPolicy
sprite $ServiceEndpoint Azure-Full-Colour-2.6/Service-Endpoint.svg
rectangle "ServiceEndpoint" <<$ServiceEndpoint>> as ServiceEndpoint
sprite $ServiceHealth Azure-Full-Colour-2.6/Service-Health.svg
rectangle "ServiceHealth" <<$ServiceHealth>> as ServiceHealth
sprite $SharedDashboard Azure-Full-Colour-2.6/Shared-Dashboard.svg
rectangle "SharedDashboard" <<$SharedDashboard>> as SharedDashboard
sprite $SharedImageGallery Azure-Full-Colour-2.6/Shared-Image-Gallery.svg
rectangle "SharedImageGallery" <<$SharedImageGallery>> as SharedImageGallery
sprite $SignIn Azure-Full-Colour-2.6/Sign-In.svg
rectangle "SignIn" <<$SignIn>> as SignIn
sprite $Signalr Azure-Full-Colour-2.6/Signalr.svg
rectangle "Signalr" <<$Signalr>> as Signalr
sprite $SoftwareAsAService Azure-Full-Colour-2.6/Software-As-A-Service.svg
rectangle "SoftwareAsAService" <<$SoftwareAsAService>> as SoftwareAsAService
sprite $SpatialAnchorsAccount Azure-Full-Colour-2.6/Spatial-Anchors-Account.svg
rectangle "SpatialAnchorsAccount" <<$SpatialAnchorsAccount>> as SpatialAnchorsAccount
sprite $SQLDataWarehouse Azure-Full-Colour-2.6/SQL-Data-Warehouse.svg
rectangle "SQLDataWarehouse" <<$SQLDataWarehouse>> as SQLDataWarehouse
sprite $SQLDatabaseEdge Azure-Full-Colour-2.6/SQL-Database-Edge.svg
rectangle "SQLDatabaseEdge" <<$SQLDatabaseEdge>> as SQLDatabaseEdge
sprite $SQLDatabase Azure-Full-Colour-2.6/SQL-Database.svg
rectangle "SQLDatabase" <<$SQLDatabase>> as SQLDatabase
sprite $SQLElasticJobAgent Azure-Full-Colour-2.6/SQL-Elastic-Job-Agent.svg
rectangle "SQLElasticJobAgent" <<$SQLElasticJobAgent>> as SQLElasticJobAgent
sprite $SQLElasticPool Azure-Full-Colour-2.6/SQL-Elastic-Pool.svg
rectangle "SQLElasticPool" <<$SQLElasticPool>> as SQLElasticPool
sprite $SQLInstancePool Azure-Full-Colour-2.6/SQL-Instance-Pool.svg
rectangle "SQLInstancePool" <<$SQLInstancePool>> as SQLInstancePool
sprite $SQLManagedInstance Azure-Full-Colour-2.6/SQL-Managed-Instance.svg
rectangle "SQLManagedInstance" <<$SQLManagedInstance>> as SQLManagedInstance
sprite $SQLServerRegistry Azure-Full-Colour-2.6/SQL-Server-Registry.svg
rectangle "SQLServerRegistry" <<$SQLServerRegistry>> as SQLServerRegistry
sprite $SQLServer Azure-Full-Colour-2.6/SQL-Server.svg
rectangle "SQLServer" <<$SQLServer>> as SQLServer
sprite $StorageAccountClassic Azure-Full-Colour-2.6/Storage-Account-Classic.svg
rectangle "StorageAccountClassic" <<$StorageAccountClassic>> as StorageAccountClassic
sprite $StorageAccountContainer Azure-Full-Colour-2.6/Storage-Account-Container.svg
rectangle "StorageAccountContainer" <<$StorageAccountContainer>> as StorageAccountContainer
sprite $StorageAccountTable Azure-Full-Colour-2.6/Storage-Account-Table.svg
rectangle "StorageAccountTable" <<$StorageAccountTable>> as StorageAccountTable
sprite $StorageAccount Azure-Full-Colour-2.6/Storage-Account.svg
rectangle "StorageAccount" <<$StorageAccount>> as StorageAccount
sprite $StorageExplorer Azure-Full-Colour-2.6/Storage-Explorer.svg
rectangle "StorageExplorer" <<$StorageExplorer>> as StorageExplorer
sprite $StorageSyncService Azure-Full-Colour-2.6/Storage-Sync-Service.svg
rectangle "StorageSyncService" <<$StorageSyncService>> as StorageSyncService
sprite $StorsimpleDataManager Azure-Full-Colour-2.6/Storsimple-Data-Manager.svg
rectangle "StorsimpleDataManager" <<$StorsimpleDataManager>> as StorsimpleDataManager
sprite $StorsimpleDeviceManager Azure-Full-Colour-2.6/Storsimple-Device-Manager.svg
rectangle "StorsimpleDeviceManager" <<$StorsimpleDeviceManager>> as StorsimpleDeviceManager
sprite $StreamAnalyticsJob Azure-Full-Colour-2.6/Stream-Analytics-Job.svg
rectangle "StreamAnalyticsJob" <<$StreamAnalyticsJob>> as StreamAnalyticsJob
sprite $Subscription Azure-Full-Colour-2.6/Subscription.svg
rectangle "Subscription" <<$Subscription>> as Subscription
sprite $Tag Azure-Full-Colour-2.6/Tag.svg
rectangle "Tag" <<$Tag>> as Tag
sprite $Tags Azure-Full-Colour-2.6/Tags.svg
rectangle "Tags" <<$Tags>> as Tags
sprite $Template Azure-Full-Colour-2.6/Template.svg
rectangle "Template" <<$Template>> as Template
sprite $TenantStatus Azure-Full-Colour-2.6/Tenant-Status.svg
rectangle "TenantStatus" <<$TenantStatus>> as TenantStatus
sprite $Terraform Azure-Full-Colour-2.6/Terraform.svg
rectangle "Terraform" <<$Terraform>> as Terraform
sprite $TimeSeriesInsightsEnvironment Azure-Full-Colour-2.6/Time-Series-Insights-Environment.svg
rectangle "TimeSeriesInsightsEnvironment" <<$TimeSeriesInsightsEnvironment>> as TimeSeriesInsightsEnvironment
sprite $TimeSeriesInsightsEventSource Azure-Full-Colour-2.6/Time-Series-Insights-Event-Source.svg
rectangle "TimeSeriesInsightsEventSource" <<$TimeSeriesInsightsEventSource>> as TimeSeriesInsightsEventSource
sprite $TimeSeriesInsightsReferenceDataSet Azure-Full-Colour-2.6/Time-Series-Insights-Reference-Data-Set.svg
rectangle "TimeSeriesInsightsReferenceDataSet" <<$TimeSeriesInsightsReferenceDataSet>> as TimeSeriesInsightsReferenceDataSet
sprite $TrafficManagerProfile Azure-Full-Colour-2.6/Traffic-Manager-Profile.svg
rectangle "TrafficManagerProfile" <<$TrafficManagerProfile>> as TrafficManagerProfile
sprite $UniversalPrintService Azure-Full-Colour-2.6/Universal-Print-Service.svg
rectangle "UniversalPrintService" <<$UniversalPrintService>> as UniversalPrintService
sprite $UpdateManagement Azure-Full-Colour-2.6/Update-Management.svg
rectangle "UpdateManagement" <<$UpdateManagement>> as UpdateManagement
sprite $UsageAndQuota Azure-Full-Colour-2.6/Usage-And-Quota.svg
rectangle "UsageAndQuota" <<$UsageAndQuota>> as UsageAndQuota
sprite $UserPrivacy Azure-Full-Colour-2.6/User-Privacy.svg
rectangle "UserPrivacy" <<$UserPrivacy>> as UserPrivacy
sprite $VirtualAssistant Azure-Full-Colour-2.6/Virtual-Assistant.svg
rectangle "VirtualAssistant" <<$VirtualAssistant>> as VirtualAssistant
sprite $VirtualCluster Azure-Full-Colour-2.6/Virtual-Cluster.svg
rectangle "VirtualCluster" <<$VirtualCluster>> as VirtualCluster
sprite $VirtualMachineAvailabilitySet Azure-Full-Colour-2.6/Virtual-Machine-Availability-Set.svg
rectangle "VirtualMachineAvailabilitySet" <<$VirtualMachineAvailabilitySet>> as VirtualMachineAvailabilitySet
sprite $VirtualMachineClassic Azure-Full-Colour-2.6/Virtual-Machine-Classic.svg
rectangle "VirtualMachineClassic" <<$VirtualMachineClassic>> as VirtualMachineClassic
sprite $VirtualMachineImageClassic Azure-Full-Colour-2.6/Virtual-Machine-Image-Classic.svg
rectangle "VirtualMachineImageClassic" <<$VirtualMachineImageClassic>> as VirtualMachineImageClassic
sprite $VirtualMachineImageDefinition Azure-Full-Colour-2.6/Virtual-Machine-Image-Definition.svg
rectangle "VirtualMachineImageDefinition" <<$VirtualMachineImageDefinition>> as VirtualMachineImageDefinition
sprite $VirtualMachineImageVersion Azure-Full-Colour-2.6/Virtual-Machine-Image-Version.svg
rectangle "VirtualMachineImageVersion" <<$VirtualMachineImageVersion>> as VirtualMachineImageVersion
sprite $VirtualMachineImage Azure-Full-Colour-2.6/Virtual-Machine-Image.svg
rectangle "VirtualMachineImage" <<$VirtualMachineImage>> as VirtualMachineImage
sprite $VirtualMachineLinux Azure-Full-Colour-2.6/Virtual-Machine-Linux.svg
rectangle "VirtualMachineLinux" <<$VirtualMachineLinux>> as VirtualMachineLinux
sprite $VirtualMachineNonAzureLinux Azure-Full-Colour-2.6/Virtual-Machine-Non-Azure-Linux.svg
rectangle "VirtualMachineNonAzureLinux" <<$VirtualMachineNonAzureLinux>> as VirtualMachineNonAzureLinux
sprite $VirtualMachineNonAzureWindows Azure-Full-Colour-2.6/Virtual-Machine-Non-Azure-Windows.svg
rectangle "VirtualMachineNonAzureWindows" <<$VirtualMachineNonAzureWindows>> as VirtualMachineNonAzureWindows
sprite $VirtualMachineNonAzure Azure-Full-Colour-2.6/Virtual-Machine-Non-Azure.svg
rectangle "VirtualMachineNonAzure" <<$VirtualMachineNonAzure>> as VirtualMachineNonAzure
sprite $VirtualMachineScaleSet Azure-Full-Colour-2.6/Virtual-Machine-Scale-Set.svg
rectangle "VirtualMachineScaleSet" <<$VirtualMachineScaleSet>> as VirtualMachineScaleSet
sprite $VirtualMachineSQL Azure-Full-Colour-2.6/Virtual-Machine-SQL.svg
rectangle "VirtualMachineSQL" <<$VirtualMachineSQL>> as VirtualMachineSQL
sprite $VirtualMachineWindows Azure-Full-Colour-2.6/Virtual-Machine-Windows.svg
rectangle "VirtualMachineWindows" <<$VirtualMachineWindows>> as VirtualMachineWindows
sprite $VirtualMachine Azure-Full-Colour-2.6/Virtual-Machine.svg
rectangle "VirtualMachine" <<$VirtualMachine>> as VirtualMachine
sprite $VirtualNetworkClassic Azure-Full-Colour-2.6/Virtual-Network-Classic.svg
rectangle "VirtualNetworkClassic" <<$VirtualNetworkClassic>> as VirtualNetworkClassic
sprite $VirtualNetworkFirewall Azure-Full-Colour-2.6/Virtual-Network-Firewall.svg
rectangle "VirtualNetworkFirewall" <<$VirtualNetworkFirewall>> as VirtualNetworkFirewall
sprite $VirtualNetworkGateway Azure-Full-Colour-2.6/Virtual-Network-Gateway.svg
rectangle "VirtualNetworkGateway" <<$VirtualNetworkGateway>> as VirtualNetworkGateway
sprite $VirtualNetworkPeering Azure-Full-Colour-2.6/Virtual-Network-Peering.svg
rectangle "VirtualNetworkPeering" <<$VirtualNetworkPeering>> as VirtualNetworkPeering
sprite $VirtualNetwork Azure-Full-Colour-2.6/Virtual-Network.svg
rectangle "VirtualNetwork" <<$VirtualNetwork>> as VirtualNetwork
sprite $VirtualSubnet Azure-Full-Colour-2.6/Virtual-Subnet.svg
rectangle "VirtualSubnet" <<$VirtualSubnet>> as VirtualSubnet
sprite $VirtualWANGateway Azure-Full-Colour-2.6/Virtual-WAN-Gateway.svg
rectangle "VirtualWANGateway" <<$VirtualWANGateway>> as VirtualWANGateway
sprite $VirtualWAN Azure-Full-Colour-2.6/Virtual-WAN.svg
rectangle "VirtualWAN" <<$VirtualWAN>> as VirtualWAN
sprite $VisualStudioCode Azure-Full-Colour-2.6/Visual-Studio-Code.svg
rectangle "VisualStudioCode" <<$VisualStudioCode>> as VisualStudioCode
sprite $VisualStudio Azure-Full-Colour-2.6/Visual-Studio.svg
rectangle "VisualStudio" <<$VisualStudio>> as VisualStudio
sprite $WAFPolicy Azure-Full-Colour-2.6/WAF-Policy.svg
rectangle "WAFPolicy" <<$WAFPolicy>> as WAFPolicy
sprite $WindowsVirtualDesktop Azure-Full-Colour-2.6/Windows-Virtual-Desktop.svg
rectangle "WindowsVirtualDesktop" <<$WindowsVirtualDesktop>> as WindowsVirtualDesktop
sprite $WorkAccount Azure-Full-Colour-2.6/Work-Account.svg
rectangle "WorkAccount" <<$WorkAccount>> as WorkAccount
sprite $Workbook Azure-Full-Colour-2.6/Workbook.svg
rectangle "Workbook" <<$Workbook>> as Workbook
@enduml