@startuml
!pragma revision 1

title Azure Monitor

'LAYOUT AND STYLING'
'top to bottom direction
'left to right direction
scale max 1024 width

' Styling
skinparam defaultTextAlignment center
skinparam defaultFontSize 12
skinparam defaultFontName Segoe UI
skinparam defaultBackgroundColor white
skinparam RectangleBackgroundColor white
skinparam RectangleBorderColor #3C7FC0
skinparam WrapWidth 100
skinparam linetype ortho

skinparam rectangle {
    BorderThickness 3
    Shadowing false
}
skinparam database {
    BackgroundColor white
    Shadowing false
}

' ##################################
'Special styling for db
skinparam RectangleBackgroundColor<<db>> #CCCCCC
skinparam RectangleBorderColor<<db>> #CCCCCC
skinparam RoundCorner<<db>> 20

'Special styling for brackets
skinparam RectangleBorderColor<<grey>> #CCCCCC
skinparam RectangleBorderThickness<<grey>> 3
skinparam RoundCorner<<grey>> 20

'Special styling for sources
skinparam RectangleBorderColor<<srcs>> #CCCCCC
skinparam RectangleBorderThickness<<srcs>> 3

'Special stying for actions
skinparam RoundCorner<<action>> 20

'Special no border styling
skinparam RectangleBorderThickness<<noborder>> 0

'Hide the above from showing up in the diagram
hide <<grey>> stereotype
hide <<db>> stereotype
hide <<action>> stereotype
hide <<noborder>> stereotype
hide <<srcs>> stereotype

'##############SPRITES###########################
'Establish sprites'
sprite $Monitor ../../media/icons/ManagementGovernance/00001-icon-service-Monitor.svg
sprite $Metrics ../../media/icons/ManagementGovernance/00020-icon-service-Metrics.svg
sprite $ActivityLog ../../media/icons/ManagementGovernance/00007-icon-service-Activity-Log.svg
sprite $ApplicationInsights ../../media/icons/DevOps/00012-icon-service-Application-Insights.svg
sprite $ContainerInstances ../../media/icons/Containers/10104-icon-service-Container-Instances.svg
sprite $VirtualMachine ../../media/icons/Compute/10021-icon-service-Virtual-Machine.svg
sprite $SAPAzureMonitor ../../media/icons/Monitor/00438-icon-service-SAP-Azure-Monitor.svg
sprite $Dashboard ../../media/icons/General/10015-icon-service-Dashboard.svg
sprite $Mobile ../../media/icons/General/10822-icon-service-Mobile.svg
sprite $PowerBI ../../media/icons/Other/not-icon-service-Power-BI.svg
sprite $Workbooks ../../media/icons/General/10851-icon-service-Workbooks.svg
sprite $AnalysisServices ../../media/icons/Analytics/10148-icon-service-Analysis-Services.svg
sprite $LogAnalyticsWorkspaces ../../media/icons/Analytics/00009-icon-service-Log-Analytics-Workspaces.svg
sprite $Alerts ../../media/icons/ManagementGovernance/00002-icon-service-Alerts.svg
sprite $VMScaleSets ../../media/icons/Compute/10034-icon-service-VM-Scale-Sets.svg
sprite $LogicApps ../../media/icons/Integration/10201-icon-service-Logic-Apps.svg
sprite $APIManagementServices ../../media/icons/Integration/10042-icon-service-API-Management-Services.svg
sprite $StaticApps ../../media/icons/Preview/01007-icon-service-Static-Apps.svg
sprite $ResourceGroups ../../media/icons/General/10007-icon-service-Resource-Groups.svg
sprite $Subscriptions ../../media/icons/General/10002-icon-service-Subscriptions.svg
sprite $MyCustomers ../../media/icons/ManagementGovernance/00014-icon-service-My-Customers.svg

'################RELATIONSHIPS#########################
'start relationships
rectangle "Sources" as sources {
    rectangle " " as leftbracket <<srcs>> {
        skinparam Ranksep 5
        rectangle "Static Apps" <<$StaticApps{scale=3}>> <<noborder>> as StaticApps
        rectangle "Operating System" as OperatingSystem
        rectangle "Subscriptions" <<$Subscriptions{scale=3}>> <<noborder>> as Subscriptions
        rectangle "Tenant" as Tenant
        rectangle "Resource Groups" <<$ResourceGroups{scale=3}>> <<noborder>> as ResourceGroups
        rectangle "My Customers" <<$MyCustomers{scale=3}>> <<noborder>> as MyCustomers
        'rectangle "Application" as Application <<db>>
        'rectangle "Operating System" as OperatingSystem
        'rectangle "Subscriptions" as Subscriptions
        'rectangle "Tenant" as Tenant
        'rectangle "Resource Groups" as ResourceGroups
        'rectangle "My Customers" as MyCustomers
        StaticApps -[hidden]d- OperatingSystem
        'Application -[hidden]d- OperatingSystem
        OperatingSystem -[hidden]d- ResourceGroups 
        ResourceGroups -[hidden]d- Subscriptions
        Subscriptions -[hidden]d- Tenant
        Tenant -[hidden]d- MyCustomers
    }
}
rectangle "Azure Monitor" <<$Monitor{scale=3}>>  as Monitor {
    rectangle " " as rightbracket <<grey>> {
        rectangle "Insights" as insights <<action>> {
            rectangle "Application Insights" <<$ApplicationInsights{scale=3}>> <<noborder>> as ApplicationInsights 
            rectangle "Container Instances" <<$ContainerInstances{scale=3}>> <<noborder>>  as ContainerInstances
            rectangle "Virtual Machine" <<$VirtualMachine{scale=3}>> <<noborder>> as VirtualMachine
            rectangle "SAP Azure Monitor" <<$SAPAzureMonitor{scale=3}>> <<noborder>> as SAPAzureMonitor
            ApplicationInsights -[hidden]r- ContainerInstances
            ContainerInstances -[hidden]r- VirtualMachine
            VirtualMachine -[hidden]r- SAPAzureMonitor
        }
        rectangle "Visualize" as visualize <<action>> {
        rectangle "Dashboard" <<$Dashboard{scale=3}>> <<noborder>> as Dashboard
            rectangle "Mobile" <<$Mobile{scale=3}>> <<noborder>> as Mobile
            rectangle "Power BI" <<$PowerBI{scale=3}>> <<noborder>> as PowerBI
            rectangle "Workbooks" <<$Workbooks{scale=3}>> <<noborder>> as Workbooks
            Dashboard -[hidden]r- Mobile
            Mobile -[hidden]r- PowerBI
            PowerBI -[hidden]r- Workbooks
        }
        rectangle "Analyze" as analyze <<action>> {
            rectangle "Analysis Services" <<$AnalysisServices{scale=3}>> <<noborder>> as AnalysisServices
            rectangle "Log Analytics Workspaces" <<$LogAnalyticsWorkspaces{scale=3}>> <<noborder>> as LogAnalyticsWorkspaces
            AnalysisServices -[hidden]r- LogAnalyticsWorkspaces
        }
        rectangle "Respond" as respond <<action>> {
            rectangle "Alerts" <<$Alerts{scale=3}>> <<noborder>> as Alerts
            rectangle "VM Scale Sets" <<$VMScaleSets{scale=3}>> <<noborder>> as VMScaleSets
            Alerts -[hidden]r- VMScaleSets
        }
        rectangle "Integrate" as integrate <<action>> {
            rectangle "Logic Apps" <<$LogicApps{scale=3}>> <<noborder>> as LogicApps
            rectangle "API Management Services" <<$APIManagementServices{scale=3}>> <<noborder>> as APIManagementServices
            LogicApps -[hidden]r- APIManagementServices
        }
    }
    together {
    rectangle " " <<db>> as db {
        database "Metrics" <<$Metrics{scale=3}>> <<noborder>> as Metrics
        database "Activity Log" <<$ActivityLog{scale=3}>> <<noborder>> as ActivityLog
        Metrics -[hidden]r- ActivityLog
        }
    }
}
'Actions relationships (hidden)
insights -[hidden]d- visualize
visualize -[hidden]d- analyze
analyze -[hidden]d- respond
respond -[hidden]d- integrate

leftbracket -[#000000]-> db
db -[#000000]r-> rightbracket
'/
rectangle "Ingrid Henkel"
@enduml
