@startuml
!pragma revision 1
!include ../../includes/AzureCommon.puml
sprite $CostManagementandBilling ../../media/icons/General/00004-icon-service-Cost-Management-and-Billing.svg
rectangle "Cost Management and Billing" <<$CostManagementandBilling{scale=3}>> as CostManagementandBilling
sprite $AllResources ../../media/icons/General/10001-icon-service-All-Resources.svg
rectangle "All Resources" <<$AllResources{scale=3}>> as AllResources
sprite $Subscriptions ../../media/icons/General/10002-icon-service-Subscriptions.svg
rectangle "Subscriptions" <<$Subscriptions{scale=3}>> as Subscriptions
sprite $Reservations ../../media/icons/General/10003-icon-service-Reservations.svg
rectangle "Reservations" <<$Reservations{scale=3}>> as Reservations
sprite $ServiceHealth ../../media/icons/General/10004-icon-service-Service-Health.svg
rectangle "Service Health" <<$ServiceHealth{scale=3}>> as ServiceHealth
sprite $Information ../../media/icons/General/10005-icon-service-Information.svg
rectangle "Information" <<$Information{scale=3}>> as Information
sprite $Recent ../../media/icons/General/10006-icon-service-Recent.svg
rectangle "Recent" <<$Recent{scale=3}>> as Recent
sprite $ResourceGroups ../../media/icons/General/10007-icon-service-Resource-Groups.svg
rectangle "Resource Groups" <<$ResourceGroups{scale=3}>> as ResourceGroups
sprite $Marketplace ../../media/icons/General/10008-icon-service-Marketplace.svg
rectangle "Marketplace" <<$Marketplace{scale=3}>> as Marketplace
sprite $QuickstartCenter ../../media/icons/General/10010-icon-service-Quickstart-Center.svg
rectangle "Quickstart Center" <<$QuickstartCenter{scale=3}>> as QuickstartCenter
sprite $ManagementGroups ../../media/icons/General/10011-icon-service-Management-Groups.svg
rectangle "Management Groups" <<$ManagementGroups{scale=3}>> as ManagementGroups
sprite $HelpandSupport ../../media/icons/General/10013-icon-service-Help-and-Support.svg
rectangle "Help and Support" <<$HelpandSupport{scale=3}>> as HelpandSupport
sprite $Tag ../../media/icons/General/10014-icon-service-Tag.svg
rectangle "Tag" <<$Tag{scale=3}>> as Tag
sprite $Dashboard ../../media/icons/General/10015-icon-service-Dashboard.svg
rectangle "Dashboard" <<$Dashboard{scale=3}>> as Dashboard
sprite $FreeServices ../../media/icons/General/10016-icon-service-Free-Services.svg
rectangle "Free Services" <<$FreeServices{scale=3}>> as FreeServices
sprite $CostManagement ../../media/icons/General/10019-icon-service-Cost-Management.svg
rectangle "Cost Management" <<$CostManagement{scale=3}>> as CostManagement
sprite $ResourceExplorer ../../media/icons/General/10349-icon-service-Resource-Explorer.svg
rectangle "Resource Explorer" <<$ResourceExplorer{scale=3}>> as ResourceExplorer
sprite $BizTalk ../../media/icons/General/10779-icon-service-Biz-Talk.svg
rectangle "Biz Talk" <<$BizTalk{scale=3}>> as BizTalk
sprite $BlobBlock ../../media/icons/General/10780-icon-service-Blob-Block.svg
rectangle "Blob Block" <<$BlobBlock{scale=3}>> as BlobBlock
sprite $BlobPage ../../media/icons/General/10781-icon-service-Blob-Page.svg
rectangle "Blob Page" <<$BlobPage{scale=3}>> as BlobPage
sprite $Branch ../../media/icons/General/10782-icon-service-Branch.svg
rectangle "Branch" <<$Branch{scale=3}>> as Branch
sprite $Browser ../../media/icons/General/10783-icon-service-Browser.svg
rectangle "Browser" <<$Browser{scale=3}>> as Browser
sprite $Bug ../../media/icons/General/10784-icon-service-Bug.svg
rectangle "Bug" <<$Bug{scale=3}>> as Bug
sprite $Builds ../../media/icons/General/10785-icon-service-Builds.svg
rectangle "Builds" <<$Builds{scale=3}>> as Builds
sprite $Cache ../../media/icons/General/10786-icon-service-Cache.svg
rectangle "Cache" <<$Cache{scale=3}>> as Cache
sprite $Code ../../media/icons/General/10787-icon-service-Code.svg
rectangle "Code" <<$Code{scale=3}>> as Code
sprite $Commit ../../media/icons/General/10788-icon-service-Commit.svg
rectangle "Commit" <<$Commit{scale=3}>> as Commit
sprite $Controls ../../media/icons/General/10789-icon-service-Controls.svg
rectangle "Controls" <<$Controls{scale=3}>> as Controls
sprite $ControlsHorizontal ../../media/icons/General/10790-icon-service-Controls-Horizontal.svg
rectangle "Controls Horizontal" <<$ControlsHorizontal{scale=3}>> as ControlsHorizontal
sprite $CostAlerts ../../media/icons/General/10791-icon-service-Cost-Alerts.svg
rectangle "Cost Alerts" <<$CostAlerts{scale=3}>> as CostAlerts
sprite $CostAnalysis ../../media/icons/General/10792-icon-service-Cost-Analysis.svg
rectangle "Cost Analysis" <<$CostAnalysis{scale=3}>> as CostAnalysis
sprite $CostBudgets ../../media/icons/General/10793-icon-service-Cost-Budgets.svg
rectangle "Cost Budgets" <<$CostBudgets{scale=3}>> as CostBudgets
sprite $Counter ../../media/icons/General/10794-icon-service-Counter.svg
rectangle "Counter" <<$Counter{scale=3}>> as Counter
sprite $Cubes ../../media/icons/General/10795-icon-service-Cubes.svg
rectangle "Cubes" <<$Cubes{scale=3}>> as Cubes
sprite $DevConsole ../../media/icons/General/10796-icon-service-Dev-Console.svg
rectangle "Dev Console" <<$DevConsole{scale=3}>> as DevConsole
sprite $Download ../../media/icons/General/10797-icon-service-Download.svg
rectangle "Download" <<$Download{scale=3}>> as Download
sprite $Error ../../media/icons/General/10798-icon-service-Error.svg
rectangle "Error" <<$Error{scale=3}>> as Error
sprite $Extensions ../../media/icons/General/10799-icon-service-Extensions.svg
rectangle "Extensions" <<$Extensions{scale=3}>> as Extensions
sprite $File ../../media/icons/General/10800-icon-service-File.svg
rectangle "File" <<$File{scale=3}>> as File
sprite $Files ../../media/icons/General/10801-icon-service-Files.svg
rectangle "Files" <<$Files{scale=3}>> as Files
sprite $FolderBlank ../../media/icons/General/10802-icon-service-Folder-Blank.svg
rectangle "Folder Blank" <<$FolderBlank{scale=3}>> as FolderBlank
sprite $FolderWebsite ../../media/icons/General/10803-icon-service-Folder-Website.svg
rectangle "Folder Website" <<$FolderWebsite{scale=3}>> as FolderWebsite
sprite $FTP ../../media/icons/General/10804-icon-service-FTP.svg
rectangle "FTP" <<$FTP{scale=3}>> as FTP
sprite $Gear ../../media/icons/General/10805-icon-service-Gear.svg
rectangle "Gear" <<$Gear{scale=3}>> as Gear
sprite $Globe ../../media/icons/General/10806-icon-service-Globe.svg
rectangle "Globe" <<$Globe{scale=3}>> as Globe
sprite $GlobeError ../../media/icons/General/10807-icon-service-Globe-Error.svg
rectangle "Globe Error" <<$GlobeError{scale=3}>> as GlobeError
sprite $GlobeSuccess ../../media/icons/General/10808-icon-service-Globe-Success.svg
rectangle "Globe Success" <<$GlobeSuccess{scale=3}>> as GlobeSuccess
sprite $GlobeWarning ../../media/icons/General/10809-icon-service-Globe-Warning.svg
rectangle "Globe Warning" <<$GlobeWarning{scale=3}>> as GlobeWarning
sprite $Guide ../../media/icons/General/10810-icon-service-Guide.svg
rectangle "Guide" <<$Guide{scale=3}>> as Guide
sprite $Heart ../../media/icons/General/10811-icon-service-Heart.svg
rectangle "Heart" <<$Heart{scale=3}>> as Heart
sprite $Image ../../media/icons/General/10812-icon-service-Image.svg
rectangle "Image" <<$Image{scale=3}>> as Image
sprite $InputOutput ../../media/icons/General/10813-icon-service-Input-Output.svg
rectangle "Input Output" <<$InputOutput{scale=3}>> as InputOutput
sprite $JourneyHub ../../media/icons/General/10814-icon-service-Journey-Hub.svg
rectangle "Journey Hub" <<$JourneyHub{scale=3}>> as JourneyHub
sprite $LaunchPortal ../../media/icons/General/10815-icon-service-Launch-Portal.svg
rectangle "Launch Portal" <<$LaunchPortal{scale=3}>> as LaunchPortal
sprite $Learn ../../media/icons/General/10816-icon-service-Learn.svg
rectangle "Learn" <<$Learn{scale=3}>> as Learn
sprite $LoadTest ../../media/icons/General/10817-icon-service-Load-Test.svg
rectangle "Load Test" <<$LoadTest{scale=3}>> as LoadTest
sprite $Location ../../media/icons/General/10818-icon-service-Location.svg
rectangle "Location" <<$Location{scale=3}>> as Location
sprite $LogStreaming ../../media/icons/General/10819-icon-service-Log-Streaming.svg
rectangle "Log Streaming" <<$LogStreaming{scale=3}>> as LogStreaming
sprite $ManagementPortal ../../media/icons/General/10820-icon-service-Management-Portal.svg
rectangle "Management Portal" <<$ManagementPortal{scale=3}>> as ManagementPortal
sprite $MediaFile ../../media/icons/General/10821-icon-service-Media-File.svg
rectangle "Media File" <<$MediaFile{scale=3}>> as MediaFile
sprite $Mobile ../../media/icons/General/10822-icon-service-Mobile.svg
rectangle "Mobile" <<$Mobile{scale=3}>> as Mobile
sprite $MobileEngagement ../../media/icons/General/10823-icon-service-Mobile-Engagement.svg
rectangle "Mobile Engagement" <<$MobileEngagement{scale=3}>> as MobileEngagement
sprite $Power ../../media/icons/General/10824-icon-service-Power.svg
rectangle "Power" <<$Power{scale=3}>> as Power
sprite $Powershell ../../media/icons/General/10825-icon-service-Powershell.svg
rectangle "Powershell" <<$Powershell{scale=3}>> as Powershell
sprite $PowerUp ../../media/icons/General/10826-icon-service-Power-Up.svg
rectangle "Power Up" <<$PowerUp{scale=3}>> as PowerUp
sprite $Preview ../../media/icons/General/10827-icon-service-Preview.svg
rectangle "Preview" <<$Preview{scale=3}>> as Preview
sprite $ProcessExplorer ../../media/icons/General/10828-icon-service-Process-Explorer.svg
rectangle "Process Explorer" <<$ProcessExplorer{scale=3}>> as ProcessExplorer
sprite $ProductionReadyDatabase ../../media/icons/General/10829-icon-service-Production-Ready-Database.svg
rectangle "Production Ready Database" <<$ProductionReadyDatabase{scale=3}>> as ProductionReadyDatabase
sprite $ResourceGroupList ../../media/icons/General/10830-icon-service-Resource-Group-List.svg
rectangle "Resource Group List" <<$ResourceGroupList{scale=3}>> as ResourceGroupList
sprite $ResourceLinked ../../media/icons/General/10831-icon-service-Resource-Linked.svg
rectangle "Resource Linked" <<$ResourceLinked{scale=3}>> as ResourceLinked
sprite $Scale ../../media/icons/General/10832-icon-service-Scale.svg
rectangle "Scale" <<$Scale{scale=3}>> as Scale
sprite $Scheduler ../../media/icons/General/10833-icon-service-Scheduler.svg
rectangle "Scheduler" <<$Scheduler{scale=3}>> as Scheduler
sprite $Search ../../media/icons/General/10834-icon-service-Search.svg
rectangle "Search" <<$Search{scale=3}>> as Search
sprite $ServerFarm ../../media/icons/General/10835-icon-service-Server-Farm.svg
rectangle "Server Farm" <<$ServerFarm{scale=3}>> as ServerFarm
sprite $ServiceBus ../../media/icons/General/10836-icon-service-Service-Bus.svg
rectangle "Service Bus" <<$ServiceBus{scale=3}>> as ServiceBus
sprite $SSD ../../media/icons/General/10837-icon-service-SSD.svg
rectangle "SSD" <<$SSD{scale=3}>> as SSD
sprite $StorageAzureFiles ../../media/icons/General/10838-icon-service-Storage-Azure-Files.svg
rectangle "Storage Azure Files" <<$StorageAzureFiles{scale=3}>> as StorageAzureFiles
sprite $StorageContainer ../../media/icons/General/10839-icon-service-Storage-Container.svg
rectangle "Storage Container" <<$StorageContainer{scale=3}>> as StorageContainer
sprite $StorageQueue ../../media/icons/General/10840-icon-service-Storage-Queue.svg
rectangle "Storage Queue" <<$StorageQueue{scale=3}>> as StorageQueue
sprite $Table ../../media/icons/General/10841-icon-service-Table.svg
rectangle "Table" <<$Table{scale=3}>> as Table
sprite $Tags ../../media/icons/General/10842-icon-service-Tags.svg
rectangle "Tags" <<$Tags{scale=3}>> as Tags
sprite $TFSVCRepository ../../media/icons/General/10843-icon-service-TFS-VC-Repository.svg
rectangle "TFS VC Repository" <<$TFSVCRepository{scale=3}>> as TFSVCRepository
sprite $Toolbox ../../media/icons/General/10844-icon-service-Toolbox.svg
rectangle "Toolbox" <<$Toolbox{scale=3}>> as Toolbox
sprite $Versions ../../media/icons/General/10845-icon-service-Versions.svg
rectangle "Versions" <<$Versions{scale=3}>> as Versions
sprite $WebsitePower ../../media/icons/General/10847-icon-service-Website-Power.svg
rectangle "Website Power" <<$WebsitePower{scale=3}>> as WebsitePower
sprite $WebsiteStaging ../../media/icons/General/10848-icon-service-Website-Staging.svg
rectangle "Website Staging" <<$WebsiteStaging{scale=3}>> as WebsiteStaging
sprite $WebSlots ../../media/icons/General/10849-icon-service-Web-Slots.svg
rectangle "Web Slots" <<$WebSlots{scale=3}>> as WebSlots
sprite $WebTest ../../media/icons/General/10850-icon-service-Web-Test.svg
rectangle "Web Test" <<$WebTest{scale=3}>> as WebTest
sprite $Workbooks ../../media/icons/General/10851-icon-service-Workbooks.svg
rectangle "Workbooks" <<$Workbooks{scale=3}>> as Workbooks
sprite $Workflow ../../media/icons/General/10852-icon-service-Workflow.svg
rectangle "Workflow" <<$Workflow{scale=3}>> as Workflow
sprite $Backlog ../../media/icons/General/10853-icon-service-Backlog.svg
rectangle "Backlog" <<$Backlog{scale=3}>> as Backlog
sprite $Media ../../media/icons/General/10854-icon-service-Media.svg
rectangle "Media" <<$Media{scale=3}>> as Media
sprite $Module ../../media/icons/General/10855-icon-service-Module.svg
rectangle "Module" <<$Module{scale=3}>> as Module
sprite $SearchGrid ../../media/icons/General/10856-icon-service-Search-Grid.svg
rectangle "Search Grid" <<$SearchGrid{scale=3}>> as SearchGrid
rectangle "Ingrid Henkel"
@enduml