@startuml
!pragma revision 1
!include ../../includes/AzureCommon.puml
sprite $SQLDataWarehouses ../../media/icons/Integration/00036-icon-service-SQL-Data-Warehouses.svg
rectangle "SQL Data Warehouses" <<$SQLDataWarehouses{scale=3}>> as SQLDataWarehouses
sprite $PartnerTopic ../../media/icons/Integration/02072-icon-service-Partner-Topic.svg
rectangle "Partner Topic" <<$PartnerTopic{scale=3}>> as PartnerTopic
sprite $SystemTopic ../../media/icons/Integration/02073-icon-service-System-Topic.svg
rectangle "System Topic" <<$SystemTopic{scale=3}>> as SystemTopic
sprite $APIManagementServices ../../media/icons/Integration/10042-icon-service-API-Management-Services.svg
rectangle "API Management Services" <<$APIManagementServices{scale=3}>> as APIManagementServices
sprite $LogicApps ../../media/icons/Integration/10201-icon-service-Logic-Apps.svg
rectangle "Logic Apps" <<$LogicApps{scale=3}>> as LogicApps
sprite $EventGridTopics ../../media/icons/Integration/10206-icon-service-Event-Grid-Topics.svg
rectangle "Event Grid Topics" <<$EventGridTopics{scale=3}>> as EventGridTopics
sprite $Relays ../../media/icons/Integration/10209-icon-service-Relays.svg
rectangle "Relays" <<$Relays{scale=3}>> as Relays
sprite $AzureAPIforFHIR ../../media/icons/Integration/10212-icon-service-Azure-API-for-FHIR.svg
rectangle "Azure API for FHIR" <<$AzureAPIforFHIR{scale=3}>> as AzureAPIforFHIR
sprite $SoftwareasaService ../../media/icons/Integration/10213-icon-service-Software-as-a-Service.svg
rectangle "Software as a Service" <<$SoftwareasaService{scale=3}>> as SoftwareasaService
sprite $EventGridDomains ../../media/icons/Integration/10215-icon-service-Event-Grid-Domains.svg
rectangle "Event Grid Domains" <<$EventGridDomains{scale=3}>> as EventGridDomains
sprite $AzureDataCatalog ../../media/icons/Integration/10216-icon-service-Azure-Data-Catalog.svg
rectangle "Azure Data Catalog" <<$AzureDataCatalog{scale=3}>> as AzureDataCatalog
sprite $IntegrationAccounts ../../media/icons/Integration/10218-icon-service-Integration-Accounts.svg
rectangle "Integration Accounts" <<$IntegrationAccounts{scale=3}>> as IntegrationAccounts
sprite $EventGridSubscriptions ../../media/icons/Integration/10221-icon-service-Event-Grid-Subscriptions.svg
rectangle "Event Grid Subscriptions" <<$EventGridSubscriptions{scale=3}>> as EventGridSubscriptions
rectangle "Ingrid Henkel"
@enduml