@startuml
sprite $CloudSimpleNodes CloudSimple-Nodes.svg
rectangle "CloudSimpleNodes" <<$CloudSimpleNodes>> as CloudSimpleNodes
sprite $CloudSimpleServices CloudSimple-Services.svg
rectangle "CloudSimpleServices" <<$CloudSimpleServices>> as CloudSimpleServices
sprite $Controllers Controllers.svg
rectangle "Controllers" <<$Controllers>> as Controllers
sprite $CustomerLockbox Customer-Lockbox.svg
rectangle "CustomerLockbox" <<$CustomerLockbox>> as CustomerLockbox
sprite $Education Education.svg
rectangle "Education" <<$Education>> as Education
sprite $ImageDefinitions Image-Definitions.svg
rectangle "ImageDefinitions" <<$ImageDefinitions>> as ImageDefinitions
sprite $ImageVersions Image-Versions.svg
rectangle "ImageVersions" <<$ImageVersions>> as ImageVersions
sprite $ResourceExplorer Resource-Explorer.svg
rectangle "ResourceExplorer" <<$ResourceExplorer>> as ResourceExplorer
sprite $SharedImageGalleries Shared-Image-Galleries.svg
rectangle "SharedImageGalleries" <<$SharedImageGalleries>> as SharedImageGalleries
sprite $TenantStatus Tenant-Status.svg
rectangle "TenantStatus" <<$TenantStatus>> as TenantStatus
sprite $WebAppFirewall Web-App-Firewall.svg
rectangle "WebAppFirewall" <<$WebAppFirewall>> as WebAppFirewall
@enduml