@startuml
sprite $ApplicationGateway Application-Gateway.svg
rectangle "ApplicationGateway" <<$ApplicationGateway>> as ApplicationGateway
sprite $ApplicationSecurityGroups Application-Security-Groups.svg
rectangle "ApplicationSecurityGroups" <<$ApplicationSecurityGroups>> as ApplicationSecurityGroups
sprite $AzureFirewall Azure-Firewall.svg
rectangle "AzureFirewall" <<$AzureFirewall>> as AzureFirewall
sprite $CDNProfiles CDN-Profiles.svg
rectangle "CDNProfiles" <<$CDNProfiles>> as CDNProfiles
sprite $Connections Connections.svg
rectangle "Connections" <<$Connections>> as Connections
sprite $DDOSProtectionPlans DDOS-Protection-Plans.svg
rectangle "DDOSProtectionPlans" <<$DDOSProtectionPlans>> as DDOSProtectionPlans
sprite $DNSPrivateZones DNS-Private-Zones.svg
rectangle "DNSPrivateZones" <<$DNSPrivateZones>> as DNSPrivateZones
sprite $DNSZones DNS-Zones.svg
rectangle "DNSZones" <<$DNSZones>> as DNSZones
sprite $ExpressRouteCircuits ExpressRoute-Circuits.svg
rectangle "ExpressRouteCircuits" <<$ExpressRouteCircuits>> as ExpressRouteCircuits
sprite $FrontDoors Front-Doors.svg
rectangle "FrontDoors" <<$FrontDoors>> as FrontDoors
sprite $LoadBalancers Load-Balancers.svg
rectangle "LoadBalancers" <<$LoadBalancers>> as LoadBalancers
sprite $LocalNetworkGateways Local-Network-Gateways.svg
rectangle "LocalNetworkGateways" <<$LocalNetworkGateways>> as LocalNetworkGateways
sprite $NetworkInterfaces Network-Interfaces.svg
rectangle "NetworkInterfaces" <<$NetworkInterfaces>> as NetworkInterfaces
sprite $NetworkSecurityGroupsClassic Network-Security-Groups-Classic.svg
rectangle "NetworkSecurityGroupsClassic" <<$NetworkSecurityGroupsClassic>> as NetworkSecurityGroupsClassic
sprite $NetworkWatcher Network-Watcher.svg
rectangle "NetworkWatcher" <<$NetworkWatcher>> as NetworkWatcher
sprite $OnpremisesDataGateways On-premises-Data-Gateways.svg
rectangle "OnpremisesDataGateways" <<$OnpremisesDataGateways>> as OnpremisesDataGateways
sprite $PublicIPAddresses Public-IP-Addresses.svg
rectangle "PublicIPAddresses" <<$PublicIPAddresses>> as PublicIPAddresses
sprite $ReservedIPAddressesClassic Reserved-IP-Addresses-Classic.svg
rectangle "ReservedIPAddressesClassic" <<$ReservedIPAddressesClassic>> as ReservedIPAddressesClassic
sprite $RouteFilters Route-Filters.svg
rectangle "RouteFilters" <<$RouteFilters>> as RouteFilters
sprite $RouteTables Route-Tables.svg
rectangle "RouteTables" <<$RouteTables>> as RouteTables
sprite $ServiceEndpointPolicies Service-Endpoint-Policies.svg
rectangle "ServiceEndpointPolicies" <<$ServiceEndpointPolicies>> as ServiceEndpointPolicies
sprite $TrafficManagerProfiles Traffic-Manager-Profiles.svg
rectangle "TrafficManagerProfiles" <<$TrafficManagerProfiles>> as TrafficManagerProfiles
sprite $VirtualNetworkClassic Virtual-Network-Classic.svg
rectangle "VirtualNetworkClassic" <<$VirtualNetworkClassic>> as VirtualNetworkClassic
sprite $VirtualNetworkGateways Virtual-Network-Gateways.svg
rectangle "VirtualNetworkGateways" <<$VirtualNetworkGateways>> as VirtualNetworkGateways
sprite $VirtualNetworks Virtual-Networks.svg
rectangle "VirtualNetworks" <<$VirtualNetworks>> as VirtualNetworks
sprite $VirtualWANs Virtual-WANs.svg
rectangle "VirtualWANs" <<$VirtualWANs>> as VirtualWANs
@enduml