@startuml
rectangle "Sources" as sources {
    rectangle " " as leftbracket <<srcs>> {
        'rectangle "Static Apps" <<$StaticApps{scale=3}>> as StaticApps
        'rectangle "Operating System" as OperatingSystem
        'rectangle "Subscriptions" <<$Subscriptions{scale=3}>> as Subscriptions
        'rectangle "Tenant" as Tenant
        'rectangle "Resource Groups" <<$ResourceGroups{scale=3}>> as ResourceGroups
        'rectangle "My Customers" <<$MyCustomers{scale=3}>> as MyCustomers
        rectangle "Resource Groups" as ResourceGroups <<db>>
        rectangle "Application" as Application <<db>>
        rectangle "Operating System" as OperatingSystem <<db>>
        rectangle "Subscriptions" as Subscriptions <<db>>
        rectangle "Tenant" as Tenant <<db>>
        rectangle "My Customers" as MyCustomers <<db>>
        'StaticApps -[hidden]d- OperatingSystem
        ResourceGroups -[hidden]d- Application
        Application -[hidden]d- OperatingSystem
        OperatingSystem -[hidden]d- Subscriptions
        Subscriptions -[hidden]d- Tenant
        Tenant -[hidden]d- MyCustomers
    }
}
@enduml