@startuml
sprite $APIManagementServices API-Management-Services.svg
rectangle "APIManagementServices" <<$APIManagementServices>> as APIManagementServices
sprite $AppConfiguration App-Configuration.svg
rectangle "AppConfiguration" <<$AppConfiguration>> as AppConfiguration
sprite $AzureAPIforFHIR Azure-API-for-FHIR.svg
rectangle "AzureAPIforFHIR" <<$AzureAPIforFHIR>> as AzureAPIforFHIR
sprite $AzureDataCatalog Azure-Data-Catalog.svg
rectangle "AzureDataCatalog" <<$AzureDataCatalog>> as AzureDataCatalog
sprite $AzureServiceBusRelays Azure-Service-Bus-Relays.svg
rectangle "AzureServiceBusRelays" <<$AzureServiceBusRelays>> as AzureServiceBusRelays
sprite $AzureServiceBus Azure-Service-Bus.svg
rectangle "AzureServiceBus" <<$AzureServiceBus>> as AzureServiceBus
sprite $AzureStorSimpleDeviceManagers Azure-StorSimple-Device-Managers.svg
rectangle "AzureStorSimpleDeviceManagers" <<$AzureStorSimpleDeviceManagers>> as AzureStorSimpleDeviceManagers
sprite $EventGridDomains Event-Grid-Domains.svg
rectangle "EventGridDomains" <<$EventGridDomains>> as EventGridDomains
sprite $EventGridSubscriptions Event-Grid-Subscriptions.svg
rectangle "EventGridSubscriptions" <<$EventGridSubscriptions>> as EventGridSubscriptions
sprite $EventGridTopics Event-Grid-Topics.svg
rectangle "EventGridTopics" <<$EventGridTopics>> as EventGridTopics
sprite $IntegrationAccounts Integration-Accounts.svg
rectangle "IntegrationAccounts" <<$IntegrationAccounts>> as IntegrationAccounts
sprite $IntegrationServiceEnvironments Integration-Service-Environments.svg
rectangle "IntegrationServiceEnvironments" <<$IntegrationServiceEnvironments>> as IntegrationServiceEnvironments
sprite $LogicAppsCustomConnector Logic-Apps-Custom-Connector.svg
rectangle "LogicAppsCustomConnector" <<$LogicAppsCustomConnector>> as LogicAppsCustomConnector
sprite $LogicApps Logic-Apps.svg
rectangle "LogicApps" <<$LogicApps>> as LogicApps
sprite $SendGridAccounts SendGrid-Accounts.svg
rectangle "SendGridAccounts" <<$SendGridAccounts>> as SendGridAccounts
sprite $ServiceCatalogManagedApplicationDefinitions Service-Catalog-Managed-Application-Definitions.svg
rectangle "ServiceCatalogManagedApplicationDefinitions" <<$ServiceCatalogManagedApplicationDefinitions>> as ServiceCatalogManagedApplicationDefinitions
sprite $SoftwareasaService(SaaS) Software-as-a-Service-(SaaS).svg
rectangle "SoftwareasaService(SaaS)" <<$SoftwareasaService(SaaS)>> as SoftwareasaService(SaaS)
@enduml