@startuml
!pragma revision 1
!include AzureCommon.puml
sprite $BatchAI AI-and-ML/Batch-AI.svg
rectangle "BatchAI" <<$BatchAI>> as BatchAI
sprite $BotServices AI-and-ML/Bot-Services.svg
rectangle "BotServices" <<$BotServices>> as BotServices
sprite $CognitiveServices AI-and-ML/Cognitive-Services.svg
rectangle "CognitiveServices" <<$CognitiveServices>> as CognitiveServices
sprite $GenomicsAccounts AI-and-ML/Genomics-Accounts.svg
rectangle "GenomicsAccounts" <<$GenomicsAccounts>> as GenomicsAccounts
sprite $MachineLearningServiceWorkspaces AI-and-ML/Machine-Learning-Service-Workspaces.svg
rectangle "MachineLearningServiceWorkspaces" <<$MachineLearningServiceWorkspaces>> as MachineLearningServiceWorkspaces
sprite $MachineLearningStudioWebServicePlans AI-and-ML/Machine-Learning-Studio-Web-Service-Plans.svg
rectangle "MachineLearningStudioWebServicePlans" <<$MachineLearningStudioWebServicePlans>> as MachineLearningStudioWebServicePlans
sprite $MachineLearningStudioWebServices AI-and-ML/Machine-Learning-Studio-Web-Services.svg
rectangle "MachineLearningStudioWebServices" <<$MachineLearningStudioWebServices>> as MachineLearningStudioWebServices
sprite $MachineLearningStudioWorkspaces AI-and-ML/Machine-Learning-Studio-Workspaces.svg
rectangle "MachineLearningStudioWorkspaces" <<$MachineLearningStudioWorkspaces>> as MachineLearningStudioWorkspaces
@enduml