@startuml
!pragma revision 1
!include AzureCommon.puml
sprite $AnalysisServices Analytics/Analysis-Services.svg
rectangle "AnalysisServices" <<$AnalysisServices>> as AnalysisServices
sprite $AzureDataExplorerClusters Analytics/Azure-Data-Explorer-Clusters.svg
rectangle "AzureDataExplorerClusters" <<$AzureDataExplorerClusters>> as AzureDataExplorerClusters
sprite $AzureDatabricks Analytics/Azure-Databricks.svg
rectangle "AzureDatabricks" <<$AzureDatabricks>> as AzureDatabricks
sprite $DataFactories Analytics/Data-Factories.svg
rectangle "DataFactories" <<$DataFactories>> as DataFactories
sprite $DataLakeAnalytics Analytics/Data-Lake-Analytics.svg
rectangle "DataLakeAnalytics" <<$DataLakeAnalytics>> as DataLakeAnalytics
sprite $DataLakeStoreGen1 Analytics/Data-Lake-Store-Gen1.svg
rectangle "DataLakeStoreGen1" <<$DataLakeStoreGen1>> as DataLakeStoreGen1
sprite $EventHubClusters Analytics/Event-Hub-Clusters.svg
rectangle "EventHubClusters" <<$EventHubClusters>> as EventHubClusters
sprite $EventHubs Analytics/Event-Hubs.svg
rectangle "EventHubs" <<$EventHubs>> as EventHubs
sprite $HDInsightClusters Analytics/HDInsightClusters.svg
rectangle "HDInsightClusters" <<$HDInsightClusters>> as HDInsightClusters
sprite $LogAnalyticsWorkspaces Analytics/Log-Analytics-Workspaces.svg
rectangle "LogAnalyticsWorkspaces" <<$LogAnalyticsWorkspaces>> as LogAnalyticsWorkspaces
sprite $StreamAnalyticsJobs Analytics/Stream-Analytics-Jobs.svg
rectangle "StreamAnalyticsJobs" <<$StreamAnalyticsJobs>> as StreamAnalyticsJobs
@enduml