' Azure-PlantUML, version 2.1.0
' https://github.com/plantuml-stdlib/Azure-PlantUML

' Colors
' ##################################
!define AZURE_COLOR #0072C6
!define AZURE_BG_COLOR #FFFFFF
!define AZURE_BORDER_COLOR #3C7FC0
!define AZURE_SYMBOL_COLOR AZURE_COLOR

' Styling
' ##################################

!define TECHN_FONT_SIZE 12

skinparam defaultTextAlignment center

skinparam wrapWidth 200
skinparam maxMessageSize 150

skinparam rectangle {
    StereotypeFontSize 12
    BackgroundColor white
    BorderThickness 0
    Shadowing false
}

skinparam Arrow {
    Color #666666
    FontColor #666666
    FontSize 12
}