@startuml
' AI Machine Learning/
/'
sprite $AzureBotService AIMachineLearning/AzureBotService.svg
sprite $AzureCognitiveServices AIMachineLearning/AzureCognitiveServices.svg
sprite $AzureMachineLearningService AIMachineLearning/AzureMachineLearningService.svg
sprite $AzureMachineLearningStudio AIMachineLearning/AzureMachineLearningStudio.svg
sprite $MicrosoftGenomics AIMachineLearning/MicrosoftGenomics.svg'/
'Analytics/
sprite $AzureAnalysisServices Analytics/AzureAnalysisServices.svg
sprite $AzureDatabricks Analytics/AzureDatabricks.svg
sprite $AzureDataCatalog Analytics/AzureDataCatalog.svg
sprite $AzureDataExplorer Analytics/AzureDataExplorer.svg
sprite $AzureDataLakeAnalytics Analytics/AzureDataLakeAnalytics.svg
sprite $AzureEventHub Analytics/AzureEventHub.svg
sprite $AzureHDInsight Analytics/AzureHDInsight.svg
sprite $AzureStreamAnalytics Analytics/AzureStreamAnalytics.svg
'Compute/
sprite $AzureAppService Compute/AzureAppService.svg
sprite $AzureBatch Compute/AzureBatch.svg
sprite $AzureFunction Compute/AzureFunction.svg
sprite $AzureServiceFabric Compute/AzureServiceFabric.svg
sprite $AzureVirtualMachine Compute/AzureVirtualMachine.svg
sprite $AzureVirtualMachineScaleSet Compute/AzureVirtualMachineScaleSet.svg
'Containers/
sprite $AzureContainerInstance Containers/AzureContainerInstance.svg
sprite $AzureContainerRegistry Containers/AzureContainerRegistry.svg
sprite $AzureKubernetesService Containers/AzureKubernetesService.svg
sprite $AzureServiceFabricMesh Containers/AzureServiceFabricMesh.svg
sprite $AzureWebAppForContainers Containers/AzureWebAppForContainers.svg
'Databases/
sprite $AzureDatabaseForMariaDB Databases/AzureDatabaseForMariaDB.svg
sprite $AzureDatabaseForMySQL Databases/AzureDatabaseForMySQL.svg
sprite $AzureDatabaseForPostgreSQL Databases/AzureDatabaseForPostgreSQL.svg 
sprite $AzureDataFactory Databases/AzureDataFactory.svg
sprite $AzureRedisCache Databases/AzureRedisCache.svg
sprite $AzureSqlDatabase Databases/AzureSqlDatabase.svg
sprite $AzureSqlDataWarehouse Databases/AzureSqlDataWarehouse.svg
sprite $AzureSqlStretchDatabase Databases/AzureSqlStretchDatabase.svg
'DevOps/
sprite $AzureApplicationInsights DevOps/AzureApplicationInsights.svg
sprite $AzureArtifacts DevOps/AzureArtifacts.svg
sprite $AzureBoards DevOps/AzureBoards.svg
sprite $AzureDevOps DevOps/AzureDevOps.svg
sprite $AzureDevTestLabs DevOps/AzureDevTestLabs.svg
sprite $AzureLabServices DevOps/AzureLabServices.svg
sprite $AzurePipelines DevOps/AzurePipelines.svg
sprite $AzureRepos DevOps/AzureRepos.svg
sprite $AzureTestPlans DevOps/AzureTestPlans.svg
'General/
sprite $Azure General/Azure.svg 
'Identity/
sprite $AzureActiveDirectory Identity/AzureActiveDirectory.svg
sprite $AzureActiveDirectoryB2C Identity/AzureActiveDirectoryB2C.svg
sprite $AzureActiveDirectoryDomainServices Identity/AzureActiveDirectoryDomainServices.svg
'Integration/
sprite $AzureEventGrid Integration/AzureEventGrid.svg
sprite $AzureLogicApps Integration/AzureLogicApps.svg
sprite $AzureServiceBus Integration/AzureServiceBus.svg
'InternetOfThings/
sprite $AzureDigitalTwins InternetOfThings/AzureDigitalTwins.svg
sprite $AzureIoTCentral InternetOfThings/AzureIoTCentral.svg
sprite $AzureIoTEdge InternetOfThings/AzureIoTEdge.svg
sprite $AzureIoTHub InternetOfThings/AzureIoTHub.svg
sprite $AzureMaps InternetOfThings/AzureMaps.svg
sprite $AzureTimeSeriesInsights InternetOfThings/AzureTimeSeriesInsights.svg
'Management/
sprite $AzureAutomation Management/AzureAutomation.svg
sprite $AzureBackup Management/AzureBackup.svg
sprite $AzureBlueprints Management/AzureBlueprints.svg
sprite $AzureLogAnalytics Management/AzureLogAnalytics.svg
sprite $AzureManagedApplications Management/AzureManagedApplications.svg
sprite $AzureManagementGroups Management/AzureManagementGroups.svg
sprite $AzureMonitor Management/AzureMonitor.svg
sprite $AzurePolicy Management/AzurePolicy.svg
sprite $AzureResourceGroups Management/AzureResourceGroups.svg
sprite $AzureScheduler Management/AzureScheduler.svg
sprite $AzureSiteRecovery Management/AzureSiteRecovery.svg
sprite $AzureSubscription Management/AzureSubscription.svg
'Media/
sprite $AzureMediaServices Media/AzureMediaServices.svg 
'Mobile/
sprite $AzureMobileApp Mobile/AzureMobileApp.svg
sprite $AzureNotificationHubs Mobile/AzureNotificationHubs.svg
'Networking/
sprite $AzureApplicationGateway Networking/AzureApplicationGateway.svg
sprite $AzureAzureDDoSProtection Networking/AzureAzureDDoSProtection.svg
sprite $AzureDNS Networking/AzureDNS.svg
sprite $AzureExpressRoute Networking/AzureExpressRoute.svg
sprite $AzureFrontDoorService Networking/AzureFrontDoorService.svg
sprite $AzureLoadBalancer Networking/AzureLoadBalancer.svg
sprite $AzureTrafficManager Networking/AzureTrafficManager.svg
sprite $AzureVirtualNetwork Networking/AzureVirtualNetwork.svg
sprite $AzureVirtualWAN Networking/AzureVirtualWAN.svg
sprite $AzureVPNGateway Networking/AzureVPNGateway.svg
'Security/
sprite $AzureKeyVault Security/AzureKeyVault.svg
sprite $AzureSentinel Security/AzureSentinel.svg
'Storage/
sprite $AzureBlobStorage Storage/AzureBlobStorage.svg
sprite $AzureDataBox Storage/AzureDataBox.svg
sprite $AzureDataLakeStorage Storage/AzureDataLakeStorage.svg
sprite $AzureDiskStorage Storage/AzureDiskStorage.svg
sprite $AzureFileStorage Storage/AzureFileStorage.svg
sprite $AzureManagedDisks Storage/AzureManagedDisks.svg
sprite $AzureNetAppFiles Storage/AzureNetAppFiles.svg
sprite $AzureQueueStorage Storage/AzureQueueStorage.svg
sprite $AzureStorage Storage/AzureStorage.svg
sprite $AzureStorSimple Storage/AzureStorSimple.svg
'Web/
sprite $AzureAPIManagement Web/AzureAPIManagement.svg
sprite $AzureCDN Web/AzureCDN.svg
sprite $AzureSearch Web/AzureSearch.svg
sprite $AzureSignalRService Web/AzureSignalRService.svg
sprite $AzureWebApp Web/AzureWebApp.svg

' AI Machine Learning/
AzureBotService: <$AzureBotService>
AzureCognitiveServices: <$AzureCognitiveServices> 
AzureMachineLearningService: <$AzureMachineLearningService>
AzureMachineLearningStudio: <$AzureMachineLearningStudio>
MicrosoftGenomics: <$MicrosoftGenomics>
'Analytics/
AzureAnalysisServices : $AzureAnalysisServices
AzureDatabricks : $AzureDatabricks
AzureDataCatalog : $AzureDataCatalog
AzureDataExplorer : $AzureDataExplorer
AzureDataLakeAnalytics : $AzureDataLakeAnalytics
AzureEventHub : $AzureEventHub
AzureHDInsight : $AzureHDInsight
AzureStreamAnalytics : $AzureStreamAnalytics
'Compute/
AzureAppService : $AzureAppService
AzureBatch : $AzureBatch
AzureFunction : $AzureFunction
AzureServiceFabric: $AzureServiceFabric
AzureVirtualMachine: $AzureVirtualMachine
AzureVirtualMachineScaleSet: $AzureVirtualMachineScaleSet
'Containers/
AzureContainerInstance: $AzureContainerInstance
AzureContainerRegistry : $AzureContainerRegistry
AzureKubernetesService : $AzureKubernetesService
AzureServiceFabricMesh : $AzureServiceFabricMesh
AzureWebAppForContainers : $AzureWebAppForContainers
'Databases/
AzureDatabaseForMariaDB : $AzureDatabaseForMariaDB
AzureDatabaseForMySQL : $AzureDatabaseForMySQL
AzureDatabaseForPostgreSQL: $AzureDatabaseForPostgreSQL
AzureDataFactory : $AzureDataFactory
AzureRedisCache : $AzureRedisCache
AzureSqlDatabase : $AzureSqlDatabase
AzureSqlDataWarehouse : $AzureSqlDataWarehouse
AzureSqlStretchDatabase : $AzureSqlStretchDatabase
'DevOps/
AzureApplicationInsights : $AzureApplicationInsights
AzureBoards :  $AzureBoards
AzureDevOps : $AzureDevOps
AzureDevTestLabs: $AzureDevTestLabs
AzureLabServices : $AzureLabServices
AzurePipelines : $AzurePipelines
AzureRepos : $AzureRepos
AzureTestPlans : $AzureTestPlans
'General/
Azure : $Azure
'Identity/
AzureActiveDirectory : $AzureActiveDirectory
AzureActiveDirectoryB2C : $AzureActiveDirectoryB2C
AzureActiveDirectoryDomainServices : $AzureActiveDirectoryDomainServices
'Integration/
AzureEventGrid : $AzureEventGrid
AzureLogicApps : $AzureLogicApps
AzureServiceBus : $AzureServiceBus
'InternetOfThings/
AzureDigitalTwins : $AzureDigitalTwins
AzureIoTCentral : $AzureIoTCentral
AzureIoTEdge : $AzureIoTEdge
AzureIoTHub : $AzureIoTHub
AzureMaps : $AzureMaps
AzureTimeSeriesInsights : $AzureTimeSeriesInsights
'Management/
AzureAutomation : $AzureAutomation
AzureBackup : $AzureBackup
AzureBlueprints : $AzureBlueprints
AzureLogAnalytics : $AzureLogAnalytics
AzureManagedApplications : $AzureManagedApplications
AzureManagementGroups : $AzureManagementGroups
AzureMonitor : $AzureMonitor
AzurePolicy : $AzurePolicy
AzureResourceGroups : $AzureResourceGroups
AzureScheduler : $AzureScheduler
AzureSiteRecovery : $AzureSiteRecovery
AzureSubscription : $AzureSubscription
'Media/
AzureMediaServices : $AzureMediaServices
'Mobile/
AzureMobileApp : $AzureMobileApp
AzureNotificationHubs : $AzureNotificationHubs
'Networking/
AzureApplicationGateway : $AzureApplicationGateway
AzureAzureDDoSProtection : $AzureAzureDDoSProtection
AzureDNS : $AzureDNS
AzureExpressRoute : $AzureExpressRoute
AzureFrontDoorService : $AzureFrontDoorService 
AzureLoadBalancer : $AzureLoadBalancer
AzureTrafficManager : $AzureTrafficManager
AzureVirtualNetwork : $AzureVirtualNetwork
AzureVirtualWAN : $AzureVirtualWAN
AzureVPNGateway : $AzureVPNGateway
'Security/
AzureKeyVault : $AzureKeyVault
AzureSentinel : $AzureSentinel
'Storage/
AzureBlobStorage : $AzureBlobStorage
AzureDataBox : $AzureDataBox
AzureDataLakeStorage : $AzureDataLakeStorage
AzureDiskStorage : $AzureDiskStorage
AzureFileStorage : $AzureFileStorage
AzureManagedDisks: $AzureManagedDisks
AzureNetAppFiles : $AzureNetAppFiles
AzureQueueStorage : $AzureQueueStorage
AzureStorage : $AzureStorage
AzureStorSimple : $AzureStorSimple
'Web/
AzureAPIManagement : $AzureAPIManagement
AzureCDN : $AzureCDN
AzureSearch : $AzureSearch
AzureSignalRService: $AzureSignalRService
AzureWebApp : $AzureWebApp
@enduml