@startuml
!pragma revision 1
!include AzureCommon.puml
sprite $AvailabilitySets Compute/Availability-Sets.svg
rectangle "AvailabilitySets" <<$AvailabilitySets>> as AvailabilitySets
sprite $BatchAccounts Compute/Batch-Accounts.svg
rectangle "BatchAccounts" <<$BatchAccounts>> as BatchAccounts
sprite $CitrixVirtualDesktopsEssentials Compute/Citrix-Virtual-Desktops-Essentials.svg
rectangle "CitrixVirtualDesktopsEssentials" <<$CitrixVirtualDesktopsEssentials>> as CitrixVirtualDesktopsEssentials
sprite $CloudServicesClassic Compute/Cloud-Services-Classic.svg
rectangle "CloudServicesClassic" <<$CloudServicesClassic>> as CloudServicesClassic
sprite $CloudServices Compute/Cloud-Services.svg
rectangle "CloudServices" <<$CloudServices>> as CloudServices
sprite $CloudSimpleVirtualMachines Compute/CloudSimple-Virtual-Machines.svg
rectangle "CloudSimpleVirtualMachines" <<$CloudSimpleVirtualMachines>> as CloudSimpleVirtualMachines
sprite $DiskSnapshots Compute/Disk-Snapshots.svg
rectangle "DiskSnapshots" <<$DiskSnapshots>> as DiskSnapshots
sprite $Disks Compute/Disks.svg
rectangle "Disks" <<$Disks>> as Disks
sprite $FunctionApps Compute/Function-Apps.svg
rectangle "FunctionApps" <<$FunctionApps>> as FunctionApps
sprite $MeshApplications Compute/Mesh-Applications.svg
rectangle "MeshApplications" <<$MeshApplications>> as MeshApplications
sprite $Nonazuremachine Compute/Non-azure-machine.svg
rectangle "Nonazuremachine" <<$Nonazuremachine>> as Nonazuremachine
sprite $OSImagesClassic Compute/OS-Images-Classic.svg
rectangle "OSImagesClassic" <<$OSImagesClassic>> as OSImagesClassic
sprite $SAPHANAonAzure Compute/SAP-HANA-on-Azure.svg
rectangle "SAPHANAonAzure" <<$SAPHANAonAzure>> as SAPHANAonAzure
sprite $ServiceFabricClusters Compute/Service-Fabric-Clusters.svg
rectangle "ServiceFabricClusters" <<$ServiceFabricClusters>> as ServiceFabricClusters
sprite $VMClassic Compute/VM-Classic.svg
rectangle "VMClassic" <<$VMClassic>> as VMClassic
sprite $VMImages Compute/VM-Images.svg
rectangle "VMImages" <<$VMImages>> as VMImages
sprite $VMLinuxnonazure Compute/VM-Linux-non-azure.svg
rectangle "VMLinuxnonazure" <<$VMLinuxnonazure>> as VMLinuxnonazure
sprite $VMLinux Compute/VM-Linux.svg
rectangle "VMLinux" <<$VMLinux>> as VMLinux
sprite $VMnonazure Compute/VM-non-azure.svg
rectangle "VMnonazure" <<$VMnonazure>> as VMnonazure
sprite $VMScaleSets Compute/VM-Scale-Sets.svg
rectangle "VMScaleSets" <<$VMScaleSets>> as VMScaleSets
sprite $VMwindowsnonazure Compute/VM-windows-non-azure.svg
rectangle "VMwindowsnonazure" <<$VMwindowsnonazure>> as VMwindowsnonazure
sprite $VMwindows Compute/VM-windows.svg
rectangle "VMwindows" <<$VMwindows>> as VMwindows
sprite $VM Compute/VM.svg
rectangle "VM" <<$VM>> as VM
@enduml