@startuml
!pragma revision 1
!include AzureCommon.puml
sprite $ContainerInstances Container/Container-Instances.svg
rectangle "ContainerInstances" <<$ContainerInstances>> as ContainerInstances
sprite $ContainerRegistries Container/Container-Registries.svg
rectangle "ContainerRegistries" <<$ContainerRegistries>> as ContainerRegistries
sprite $KubernetesServices Container/Kubernetes-Services.svg
rectangle "KubernetesServices" <<$KubernetesServices>> as KubernetesServices
@enduml