@startuml
!pragma revision 1
!include AzureCommon.puml
sprite $AzureCacheforRedis Databases/Azure-Cache-for-Redis.svg
rectangle "AzureCacheforRedis" <<$AzureCacheforRedis>> as AzureCacheforRedis
sprite $AzureCacheplusRedis Databases/Azure-Cache-plus-Redis.svg
rectangle "AzureCacheplusRedis" <<$AzureCacheplusRedis>> as AzureCacheplusRedis
sprite $AzureCosmosDB Databases/Azure-Cosmos-DB.svg
rectangle "AzureCosmosDB" <<$AzureCosmosDB>> as AzureCosmosDB
sprite $AzureDatabase(Generic) Databases/Azure-Database-(Generic).svg
rectangle "AzureDatabase(Generic)" <<$AzureDatabase(Generic)>> as AzureDatabase(Generic)
sprite $AzureDatabaseforMariaDBservers Databases/Azure-Database-for-MariaDB-servers.svg
rectangle "AzureDatabaseforMariaDBservers" <<$AzureDatabaseforMariaDBservers>> as AzureDatabaseforMariaDBservers
sprite $AzureDatabaseforMySQLservers Databases/Azure-Database-for-MySQL-servers.svg
rectangle "AzureDatabaseforMySQLservers" <<$AzureDatabaseforMySQLservers>> as AzureDatabaseforMySQLservers
sprite $AzureDatabaseforPostgreSQLservers Databases/Azure-Database-for-PostgreSQL-servers.svg
rectangle "AzureDatabaseforPostgreSQLservers" <<$AzureDatabaseforPostgreSQLservers>> as AzureDatabaseforPostgreSQLservers
sprite $AzureSQLDataWarehouse Databases/Azure-SQL-DataWarehouse.svg
rectangle "AzureSQLDataWarehouse" <<$AzureSQLDataWarehouse>> as AzureSQLDataWarehouse
sprite $BlobStorage Databases/Blob-Storage.svg
rectangle "BlobStorage" <<$BlobStorage>> as BlobStorage
sprite $DataLake Databases/Data-Lake.svg
rectangle "DataLake" <<$DataLake>> as DataLake
sprite $ElasticDatabasePools Databases/Elastic-Database-Pools.svg
rectangle "ElasticDatabasePools" <<$ElasticDatabasePools>> as ElasticDatabasePools
sprite $ElasticJobAgents Databases/Elastic-Job-Agents.svg
rectangle "ElasticJobAgents" <<$ElasticJobAgents>> as ElasticJobAgents
sprite $ManagedDatabases Databases/Managed-Databases.svg
rectangle "ManagedDatabases" <<$ManagedDatabases>> as ManagedDatabases
sprite $SQLDatabases Databases/SQL-Databases.svg
rectangle "SQLDatabases" <<$SQLDatabases>> as SQLDatabases
sprite $SQLManagedInstances Databases/SQL-Managed-Instances.svg
rectangle "SQLManagedInstances" <<$SQLManagedInstances>> as SQLManagedInstances
sprite $SQLServerstretchDatabases Databases/SQL-Server-stretch-Databases.svg
rectangle "SQLServerstretchDatabases" <<$SQLServerstretchDatabases>> as SQLServerstretchDatabases
sprite $SQLServers Databases/SQL-Servers.svg
rectangle "SQLServers" <<$SQLServers>> as SQLServers
sprite $VirtualClusters Databases/Virtual-Clusters.svg
rectangle "VirtualClusters" <<$VirtualClusters>> as VirtualClusters
sprite $VirtualDatacenter Databases/Virtual-Datacenter.svg
rectangle "VirtualDatacenter" <<$VirtualDatacenter>> as VirtualDatacenter
@enduml