@startuml
!pragma revision 1
!include AzureCommon.puml
sprite $ApplicationInsights DevOps/Application-Insights.svg
rectangle "ApplicationInsights" <<$ApplicationInsights>> as ApplicationInsights
sprite $AzureArtifacts DevOps/Azure-Artifacts.svg
rectangle "AzureArtifacts" <<$AzureArtifacts>> as AzureArtifacts
sprite $AzureBoards DevOps/Azure-Boards.svg
rectangle "AzureBoards" <<$AzureBoards>> as AzureBoards
sprite $AzureDevOps DevOps/Azure-DevOps.svg
rectangle "AzureDevOps" <<$AzureDevOps>> as AzureDevOps
sprite $AzureDevTestLabs DevOps/Azure-DevTest-Labs.svg
rectangle "AzureDevTestLabs" <<$AzureDevTestLabs>> as AzureDevTestLabs
sprite $AzurePipelines DevOps/Azure-Pipelines.svg
rectangle "AzurePipelines" <<$AzurePipelines>> as AzurePipelines
sprite $AzureRepos DevOps/Azure-Repos.svg
rectangle "AzureRepos" <<$AzureRepos>> as AzureRepos
sprite $AzureTestPlans DevOps/Azure-Test-Plans.svg
rectangle "AzureTestPlans" <<$AzureTestPlans>> as AzureTestPlans
@enduml