@startuml
!pragma revision 1
!include AzureCommon.puml
sprite $AccessReview Identity/Access-Review.svg
rectangle "AccessReview" <<$AccessReview>> as AccessReview
sprite $ActiveDirectoryConnectHealth Identity/Active-Directory-Connect-Health.svg
rectangle "ActiveDirectoryConnectHealth" <<$ActiveDirectoryConnectHealth>> as ActiveDirectoryConnectHealth
sprite $ActiveDirectory Identity/Active-Directory.svg
rectangle "ActiveDirectory" <<$ActiveDirectory>> as ActiveDirectory
sprite $AppRegistrations Identity/App-Registrations.svg
rectangle "AppRegistrations" <<$AppRegistrations>> as AppRegistrations
sprite $AzureADB2C Identity/Azure-AD-B2C.svg
rectangle "AzureADB2C" <<$AzureADB2C>> as AzureADB2C
sprite $AzureADDomainServices Identity/Azure-AD-Domain-Services.svg
rectangle "AzureADDomainServices" <<$AzureADDomainServices>> as AzureADDomainServices
sprite $AzureADIdentityProtection Identity/Azure-AD-Identity-Protection.svg
rectangle "AzureADIdentityProtection" <<$AzureADIdentityProtection>> as AzureADIdentityProtection
sprite $AzureADPrivilegedIdentityManagement Identity/Azure-AD-Privileged-Identity-Management.svg
rectangle "AzureADPrivilegedIdentityManagement" <<$AzureADPrivilegedIdentityManagement>> as AzureADPrivilegedIdentityManagement
sprite $AzureInformationProtection Identity/Azure-Information-Protection.svg
rectangle "AzureInformationProtection" <<$AzureInformationProtection>> as AzureInformationProtection
sprite $ConditionalAccess Identity/Conditional-Access.svg
rectangle "ConditionalAccess" <<$ConditionalAccess>> as ConditionalAccess
sprite $EnterpriseApplications Identity/Enterprise-Applications.svg
rectangle "EnterpriseApplications" <<$EnterpriseApplications>> as EnterpriseApplications
sprite $Identitygovernance Identity/Identity-governance.svg
rectangle "Identitygovernance" <<$Identitygovernance>> as Identitygovernance
sprite $ManagedIdentities Identity/Managed-Identities.svg
rectangle "ManagedIdentities" <<$ManagedIdentities>> as ManagedIdentities
@enduml