@startuml
!pragma revision 1
!include AzureCommon.puml
sprite $AzureDigitalTwins Internet-of-Things/Azure-Digital-Twins.svg
rectangle "AzureDigitalTwins" <<$AzureDigitalTwins>> as AzureDigitalTwins
sprite $AzureIoTHubSecurity Internet-of-Things/Azure-IoT-Hub-Security.svg
rectangle "AzureIoTHubSecurity" <<$AzureIoTHubSecurity>> as AzureIoTHubSecurity
sprite $AzureIoTHub Internet-of-Things/Azure-IoT-Hub.svg
rectangle "AzureIoTHub" <<$AzureIoTHub>> as AzureIoTHub
sprite $AzureMaps Internet-of-Things/Azure-Maps.svg
rectangle "AzureMaps" <<$AzureMaps>> as AzureMaps
sprite $AzureSphere Internet-of-Things/Azure-Sphere.svg
rectangle "AzureSphere" <<$AzureSphere>> as AzureSphere
sprite $DeviceProvisioningServices Internet-of-Things/Device-Provisioning-Services.svg
rectangle "DeviceProvisioningServices" <<$DeviceProvisioningServices>> as DeviceProvisioningServices
sprite $IoTCentralApplications Internet-of-Things/IoT-Central-Applications.svg
rectangle "IoTCentralApplications" <<$IoTCentralApplications>> as IoTCentralApplications
sprite $TimeSeriesInsightsenvironments Internet-of-Things/Time-Series-Insights-environments.svg
rectangle "TimeSeriesInsightsenvironments" <<$TimeSeriesInsightsenvironments>> as TimeSeriesInsightsenvironments
sprite $TimeSeriesInsightsEventsSources Internet-of-Things/Time-Series-Insights-Events-Sources.svg
rectangle "TimeSeriesInsightsEventsSources" <<$TimeSeriesInsightsEventsSources>> as TimeSeriesInsightsEventsSources
sprite $Windows10IoTCoreServices Internet-of-Things/Windows-10-IoT-Core-Services.svg
rectangle "Windows10IoTCoreServices" <<$Windows10IoTCoreServices>> as Windows10IoTCoreServices
@enduml