@startuml
!pragma revision 1
!include AzureCommon.puml
sprite $ArchiveStorage Storage/Archive-Storage.svg
rectangle "ArchiveStorage" <<$ArchiveStorage>> as ArchiveStorage
sprite $AzureNetAppfiles Storage/Azure-NetApp-files.svg
rectangle "AzureNetAppfiles" <<$AzureNetAppfiles>> as AzureNetAppfiles
sprite $AzureStorSimpleDeviceManagers Storage/Azure-StorSimple-Device-Managers.svg
rectangle "AzureStorSimpleDeviceManagers" <<$AzureStorSimpleDeviceManagers>> as AzureStorSimpleDeviceManagers
sprite $AzureFXTEdgeFiler Storage/AzureFXTEdgeFiler.svg
rectangle "AzureFXTEdgeFiler" <<$AzureFXTEdgeFiler>> as AzureFXTEdgeFiler
sprite $BlobStorage Storage/Blob-Storage.svg
rectangle "BlobStorage" <<$BlobStorage>> as BlobStorage
sprite $DataBoxEdge_DataBoxGateway Storage/Data-Box-Edge-_-Data-Box-Gateway.svg
rectangle "DataBoxEdge_DataBoxGateway" <<$DataBoxEdge_DataBoxGateway>> as DataBoxEdge_DataBoxGateway
sprite $DataBox Storage/Data-Box.svg
rectangle "DataBox" <<$DataBox>> as DataBox
sprite $DataLakeStorage Storage/Data-Lake-Storage.svg
rectangle "DataLakeStorage" <<$DataLakeStorage>> as DataLakeStorage
sprite $GeneralStorage Storage/General-Storage.svg
rectangle "GeneralStorage" <<$GeneralStorage>> as GeneralStorage
sprite $QueuesStorage Storage/Queues-Storage.svg
rectangle "QueuesStorage" <<$QueuesStorage>> as QueuesStorage
sprite $StorageAccountsClassic Storage/Storage-Accounts-Classic.svg
rectangle "StorageAccountsClassic" <<$StorageAccountsClassic>> as StorageAccountsClassic
sprite $StorageAccounts Storage/Storage-Accounts.svg
rectangle "StorageAccounts" <<$StorageAccounts>> as StorageAccounts
sprite $StorageExplorer Storage/Storage-Explorer.svg
rectangle "StorageExplorer" <<$StorageExplorer>> as StorageExplorer
sprite $StorageSyncServices Storage/Storage-Sync-Services.svg
rectangle "StorageSyncServices" <<$StorageSyncServices>> as StorageSyncServices
sprite $StorSimpleDataManagers Storage/StorSimple-Data-Managers.svg
rectangle "StorSimpleDataManagers" <<$StorSimpleDataManagers>> as StorSimpleDataManagers
sprite $StorSimpleDeviceManagers Storage/StorSimple-Device-Managers.svg
rectangle "StorSimpleDeviceManagers" <<$StorSimpleDeviceManagers>> as StorSimpleDeviceManagers
sprite $TableStorage Storage/Table-Storage.svg
rectangle "TableStorage" <<$TableStorage>> as TableStorage
@enduml