@startuml
!pragma revision 1
!include AzureCommon.puml
sprite $APIConnections Web/API-Connections.svg
rectangle "APIConnections" <<$APIConnections>> as APIConnections
sprite $AppServiceCertificates Web/App-Service-Certificates.svg
rectangle "AppServiceCertificates" <<$AppServiceCertificates>> as AppServiceCertificates
sprite $AppServiceDomains Web/App-Service-Domains.svg
rectangle "AppServiceDomains" <<$AppServiceDomains>> as AppServiceDomains
sprite $AppServiceEnvironments Web/App-Service-Environments.svg
rectangle "AppServiceEnvironments" <<$AppServiceEnvironments>> as AppServiceEnvironments
sprite $AppServicePlans Web/App-Service-Plans.svg
rectangle "AppServicePlans" <<$AppServicePlans>> as AppServicePlans
sprite $AppServices Web/App-Services.svg
rectangle "AppServices" <<$AppServices>> as AppServices
sprite $AzureMediaServices Web/Azure-Media-Services.svg
rectangle "AzureMediaServices" <<$AzureMediaServices>> as AzureMediaServices
sprite $AzureSearch Web/Azure-Search.svg
rectangle "AzureSearch" <<$AzureSearch>> as AzureSearch
sprite $NotificationHubNamespaces Web/Notification-Hub-Namespaces.svg
rectangle "NotificationHubNamespaces" <<$NotificationHubNamespaces>> as NotificationHubNamespaces
sprite $SignalR Web/SignalR.svg
rectangle "SignalR" <<$SignalR>> as SignalR
@enduml