@startuml
sprite $AzureDigitalTwins Azure-Digital-Twins.svg
rectangle "AzureDigitalTwins" <<$AzureDigitalTwins>> as AzureDigitalTwins
sprite $AzureIoTHubSecurity Azure-IoT-Hub-Security.svg
rectangle "AzureIoTHubSecurity" <<$AzureIoTHubSecurity>> as AzureIoTHubSecurity
sprite $AzureIoTHub Azure-IoT-Hub.svg
rectangle "AzureIoTHub" <<$AzureIoTHub>> as AzureIoTHub
sprite $AzureMaps Azure-Maps.svg
rectangle "AzureMaps" <<$AzureMaps>> as AzureMaps
sprite $AzureSphere Azure-Sphere.svg
rectangle "AzureSphere" <<$AzureSphere>> as AzureSphere
sprite $DeviceProvisioningServices Device-Provisioning-Services.svg
rectangle "DeviceProvisioningServices" <<$DeviceProvisioningServices>> as DeviceProvisioningServices
sprite $IoTCentralApplications IoT-Central-Applications.svg
rectangle "IoTCentralApplications" <<$IoTCentralApplications>> as IoTCentralApplications
sprite $TimeSeriesInsightsenvironments Time-Series-Insights-environments.svg
rectangle "TimeSeriesInsightsenvironments" <<$TimeSeriesInsightsenvironments>> as TimeSeriesInsightsenvironments
sprite $TimeSeriesInsightsEventsSources Time-Series-Insights-Events-Sources.svg
rectangle "TimeSeriesInsightsEventsSources" <<$TimeSeriesInsightsEventsSources>> as TimeSeriesInsightsEventsSources
sprite $Windows10IoTCoreServices Windows-10-IoT-Core-Services.svg
rectangle "Windows10IoTCoreServices" <<$Windows10IoTCoreServices>> as Windows10IoTCoreServices
@enduml