@startuml
sprite $AnalysisServices Analysis-Services2.svg
rectangle "AnalysisServices" <<$AnalysisServices>> as AnalysisServices
sprite $AzureDataExplorerClusters Azure-Data-Explorer-Clusters.svg
rectangle "AzureDataExplorerClusters" <<$AzureDataExplorerClusters>> as AzureDataExplorerClusters
sprite $AzureDatabricks Azure-Databricks.svg
rectangle "AzureDatabricks" <<$AzureDatabricks>> as AzureDatabricks
sprite $DataFactories Data-Factories.svg
rectangle "DataFactories" <<$DataFactories>> as DataFactories
sprite $DataLakeAnalytics Data-Lake-Analytics2.svg
rectangle "DataLakeAnalytics" <<$DataLakeAnalytics>> as DataLakeAnalytics
sprite $DataLakeStoreGen1 Data-Lake-Store-Gen1-2.svg
rectangle "DataLakeStoreGen1" <<$DataLakeStoreGen1>> as DataLakeStoreGen1
sprite $EventHubClusters Event-Hub-Clusters2.svg
rectangle "EventHubClusters" <<$EventHubClusters>> as EventHubClusters
sprite $EventHubs Event-Hubs2.svg
rectangle "EventHubs" <<$EventHubs>> as EventHubs
sprite $HDInsightClusters HDInsightClusters.svg
rectangle "HDInsightClusters" <<$HDInsightClusters>> as HDInsightClusters
sprite $LogAnalyticsWorkspaces Log-Analytics-Workspaces.svg
rectangle "LogAnalyticsWorkspaces" <<$LogAnalyticsWorkspaces>> as LogAnalyticsWorkspaces
sprite $StreamAnalyticsJobs Stream-Analytics-Jobs.svg
rectangle "StreamAnalyticsJobs" <<$StreamAnalyticsJobs>> as StreamAnalyticsJobs
@enduml