@startuml
!pragma revision 1
!include ../../includes/AzureCommon.puml
sprite $RecoveryServicesVaults Storage/00017-icon-service-Recovery-Services-Vaults.svg
rectangle " Recovery Services Vaults" <<$RecoveryServicesVaults{scale=3}>> as RecoveryServicesVaults
sprite $AzureStackEdge Storage/00691-icon-service-Azure-Stack-Edge.svg
rectangle " Azure Stack Edge" <<$AzureStackEdge{scale=3}>> as AzureStackEdge
sprite $AzureHCPCache Storage/00776-icon-service-Azure-HCP-Cache.svg
rectangle " Azure HCP Cache" <<$AzureHCPCache{scale=3}>> as AzureHCPCache
sprite $StorageAccounts Storage/10086-icon-service-Storage-Accounts.svg
rectangle " Storage Accounts" <<$StorageAccounts{scale=3}>> as StorageAccounts
sprite $StorageAccountsClassic Storage/10087-icon-service-Storage-Accounts-Classic.svg
rectangle " Storage Accounts Classic" <<$StorageAccountsClassic{scale=3}>> as StorageAccountsClassic
sprite $StorSimpleDeviceManagers Storage/10089-icon-service-StorSimple-Device-Managers.svg
rectangle " StorSimple Device Managers" <<$StorSimpleDeviceManagers{scale=3}>> as StorSimpleDeviceManagers
sprite $DataLakeStorageGen1 Storage/10090-icon-service-Data-Lake-Storage-Gen1.svg
rectangle " Data Lake Storage Gen1" <<$DataLakeStorageGen1{scale=3}>> as DataLakeStorageGen1
sprite $StorSimpleDataManagers Storage/10092-icon-service-StorSimple-Data-Managers.svg
rectangle " StorSimple Data Managers" <<$StorSimpleDataManagers{scale=3}>> as StorSimpleDataManagers
sprite $StorageSyncServices Storage/10093-icon-service-Storage-Sync-Services.svg
rectangle " Storage Sync Services" <<$StorageSyncServices{scale=3}>> as StorageSyncServices
sprite $DataBox Storage/10094-icon-service-Data-Box.svg
rectangle " Data Box" <<$DataBox{scale=3}>> as DataBox
sprite $DataBoxEdge Storage/10095-icon-service-Data-Box-Edge.svg
rectangle " Data Box Edge" <<$DataBoxEdge{scale=3}>> as DataBoxEdge
sprite $AzureNetAppFiles Storage/10096-icon-service-Azure-NetApp-Files.svg
rectangle " Azure NetApp Files" <<$AzureNetAppFiles{scale=3}>> as AzureNetAppFiles
sprite $DataShareInvitations Storage/10097-icon-service-Data-Share-Invitations.svg
rectangle " Data Share Invitations" <<$DataShareInvitations{scale=3}>> as DataShareInvitations
sprite $DataShares Storage/10098-icon-service-Data-Shares.svg
rectangle " Data Shares" <<$DataShares{scale=3}>> as DataShares
sprite $ImportExportJobs Storage/10100-icon-service-Import-Export-Jobs.svg
rectangle " Import Export Jobs" <<$ImportExportJobs{scale=3}>> as ImportExportJobs
@enduml