User: "User"
LogAnalytics: "Log Analytics Workspaces" {
  icon: "../media/icons/2025/analytics/00009-icon-service-Log-Analytics-Workspaces.svg"
}
BlobStorage: "Event Hubs" {
  icon: "../media/icons/2025/analytics/00039-icon-service-Event-Hubs.svg"
}

User -> LogAnalytics: Uploads
LogAnalytics -> EventHubs: Stores data
