' Colors
' ##################################
!define AZURE_COLOR #0072C6
!define AZURE_BG_COLOR #FFFFFF
!define AZURE_BORDER_COLOR #3C7FC0
!define AZURE_SYMBOL_COLOR AZURE_COLOR

' Styling
' ##################################

skinparam defaultTextAlignment center
skinparam defaultFontName Segoe UI
skinparam defaultBackgroundColor white
skinparam RectangleBackgroundColor white
skinparam RectangleBorderColor AZURE_BORDER_COLOR
skinparam WrapWidth 100

skinparam rectangle {
    FontSize 12
    BorderThickness 0
    Shadowing false
}
